#!/bin/bash

#envs:
#GIT_AUTHOR_DATE=@1737615274 +0100
#GIT_AUTHOR_EMAIL=
#GIT_AUTHOR_NAME=
#GIT_EDITOR=:
#GIT_EXEC_PATH=/usr/lib/git-core
#GIT_INDEX_FILE=.git/index
#GIT_PREFIX=

set -e

# maintain sync/* branches mirroring the every other branch,
# so you can push these sync/* branches to non-bare repos,
# without messing up the currently checked out branch there.

branch=`git symbolic-ref --quiet --short HEAD`
if [ -n "$branch" ] && ! [[ $branch =~ ^sync/ ]]
then
	if git show-ref --verify --quiet refs/heads/sync/$branch
	then
		git merge-into "sync/$branch"
	else
	git branch "sync/$branch"
	fi
fi
