#!/bin/bash

set -e
set -o pipefail
set -u

remoteName=$1
remoteURL=$2

# when we're pushing to a non-bare repo,
# initialize it first, so new repos are synced seamlessly.

if [[ $remoteURL =~ /\.git$ ]]
then
	if [[ $remoteURL =~ ^([^:]+):(.+/)\.git$ ]]
	then
		remoteHost=${BASH_REMATCH[1]}
		remotePath=${BASH_REMATCH[2]}
		
		ssh "$remoteHost" multicmd --delimiter + --errexit mkdir -p "$remotePath" + git init -q "$remotePath"
	fi
fi
