#!/bin/bash

usage_help_text="qls [<OPTIONS>] [<ID>]
List items in the queue, or show a particular task's details if <ID> is given.
Fields:
  ID       task unique id
  ADDED    when the task was added
  STATE    queued, running, ended, ended(<CODE>), gone
  COMMAND  command to run, shown either in multiple lines (2nd and following lines prepended by TABs)
           or in a single line with backslash and newline chars escaped by backslash
OPTIONS:
  -q, --quiet
  --multiline  (default)
  -M, --no-multiline, --escape-command
  -d, --queue-dir <DIR>
  -H, --no-header
  -h, --hide-state <STATE>
  -e, --show-exit-code"

qls_multiline=yes
qls_header=yes
qls_show_exit_status=''
qls_hide_states=''

. qadd-common


if [ ! $quiet ]
then
	echo "qls: $queue_dir" >&2
fi

if [ $# -gt 0 ]
then
	for item_id in "$@"
	do
		itemfile=$queue_dir/$item_id.comm
		load_command_global "$itemfile"
		echo -n "Command:	"
		declare -p command | cut -d= -f2-
		
		state=`qtask_state "$item_id"`
		echo "State:	$state"
		
		pidfile=$queue_dir/$item_id.pid
		if [ -e "$pidfile" ]
		then
			pid=`cat "$pidfile" 2>/dev/null`
			echo -n "Pid:	$pid"
			task_pidns=`cat "$queue_dir/$item_id.pidns" 2>/dev/null`
			curr_pidns=`readlink /proc/self/ns/pid`
			if [ "$task_pidns" != "$curr_pidns" ]; then echo " pidns=${task_pidns#*:}"; else echo; fi
			
			timestamp=`stat -c %Y "$itemfile"`
			datetime=`date +"%F %T" -d @$timestamp`
			echo "Added:	$datetime"
			
			timestamp=`stat -c %Y "$pidfile"`
			datetime=`date +"%F %T" -d @$timestamp`
			echo "Started:	$datetime"
			
			if [ -d /proc/$pid ]
			then
				load_command_global "/proc/$pid/cmdline"
				echo -n "Process:	"
				declare -p command | cut -d= -f2-
				process_status=`grep "^State:" /proc/$pid/status 2>/dev/null | sed -e 's/^[^:]\+:\s*//'`
				echo "Process Status:	$process_status"
			fi
		fi
		
		endfile=$queue_dir/$item_id.end
		if [ -e "$endfile" ]
		then
			timestamp=`stat -c %Y "$endfile"`
			datetime=`date +"%F %T" -d @$timestamp`
			echo "Ended:	$datetime"
			
			code=`cat "$endfile"`
			echo "Returned:	$code"
		fi
	done
	
	exit
fi

if [ $qls_header ]
then
	echo "ID	ADDED	STATE	COMMAND"
fi

shopt -s nullglob

for itemfile in "$queue_dir"/?.comm "$queue_dir"/??.comm "$queue_dir"/???.comm "$queue_dir"/????.comm "$queue_dir"/?????.comm "$queue_dir"/??????.comm "$queue_dir"/???????.comm 
do
	item_id=`basename "$itemfile" .comm`
	state=`qtask_state "$item_id"`
	state_shown=$state
	
	if grep -qw "$state" <<< "$qls_hide_states"
	then
		continue
	fi
	
	timestamp=`stat -c %Y "$itemfile"`
	datetime=`date +"%F %T" -d @$timestamp`
	load_command_global "$itemfile"
	command_str=${command[*]}
	
	if [ $qls_show_exit_status ]
	then
		if [ "$state" = ended ]
		then
			code=`cat "$queue_dir/$item_id.end"`
			code=${code:-NA}
			state_shown="$state($code)"
		fi
	fi
	
	if [ $qls_multiline ]
	then
		command_shown=${command_str//$'\n'/$'\n\t\t\t'}
	else
		command_shown=${command_str//\\/\\\\}
		command_shown=${command_shown//$'\n'/\\n}
	fi
	
	echo "$item_id	$datetime	$state_shown	$command_shown"
done
