#!/bin/bash

find "$2$1" -mindepth 1 -maxdepth 1 \
	-printf 'ino=%i mode=%M nlink=%n uid=%U gid=%G rdev=0 size=%s blksize=512 blocks=%b atime=%A@ mtime=%T@ ctime=%C@ %f\0' |\
basedir=$2 cwd=$1 perl -e '
use Encode;
use Linux::UserXAttr ":all";
use constant {STAT_ATIME => 8, STAT_MTIME => 9, STAT_CTIME => 10,};

$xattr_file = "user.maildirfs.display_filename";
$/ = chr 0;

$folder_time = (stat $ENV{basedir}.$ENV{cwd})[STAT_CTIME];
$cache_basename = "maildirfs.cache";
$cache_file = $ENV{basedir}.$ENV{cwd}."/".$cache_basename;
$cache_time = (stat $cache_file)[STAT_MTIME];
$cache = "";

if($folder_time <= $cache_time)
{
	close STDIN;
	open my $f, "<", $cache_file or exit 5;
	$/ = chr 0;
	print while <$f>;
	exit 0;
}

open $cache_fh, ">", $cache_file;

while(<>)
{
	s/\x00$//;
	@attr = split / /;
	$fname = $attr[12];
	
	if($ENV{cwd} =~ m{/.getmail/})
	{
		goto return_dir_entry;
	}
	
	if($fname eq $cache_basename)
	{
		next;
	}
	
	$path = $ENV{basedir}.$ENV{cwd}."/".$fname;
	if(-f $path)
	{
		my $name = getxattr($path, $xattr_file);
		
		if(not $name)
		{
			if(open my $fh, "<", $path)
			{
				my %hdr;
				local $/ = "\n";
				while(<$fh>)
				{
					s/[\r\n]//g;
					last if /^$/;
					if(($hname) = /^(From|Subject):\s*/i)
					{
						$hdr{$hname} = $'\'';
						$pos = tell $fh;
						$hdr{$hname} .= $_ while $_=<$fh> and s/^\s+(.+)[\r\n]*$/$1/;
						seek $fh, $pos, 0;
					}
					last if scalar keys %hdr == 2;
				}
				close $fh;
				
				$name = join " ✉ ", 
					map {s/^"(.+?)"/$1/; $_} 
					map {s{/}{∕}g; $_}
					map {s{\x00}{}g; $_}
					map {encode "utf8", decode "MIME-Header", $_} 
					grep {defined} $hdr{From}, $hdr{Subject};
				
				setxattr $path, $xattr_file, $name, 0;
			}
		}
		
		if($name)
		{
			$attr[12] = "$name [$fname].eml";
		}
	}
	
	return_dir_entry:
	$entry = join(" ", @attr) . "\0";
	print $entry;
	print {$cache_fh} $entry;
}

close $cache_fh;
'
