#!/bin/bash

. "`dirname "$(readlink -f "$0")"`/common.sh"

if [ -e "$2$1" ]
then
find -L "$2$1" -mindepth 1 -maxdepth 1 \
	-printf 'ino=%i mode=%M nlink=%n uid=%U gid=%G rdev=0 size=%s blksize=512 blocks=%b atime=%A@ mtime=%T@ ctime=%C@ %f\0' |\
fields=13 basedir=$2 cwd=$1 perl -e '
use Encode;
use Linux::UserXAttr ":all";
use constant {STAT_INODE => 1, STAT_ATIME => 8, STAT_MTIME => 9, STAT_CTIME => 10,};
use constant {EIO => 5,};

$xattr_displayname = "user.maildirfs.display_filename";
$/ = chr 0;

while(<>)
{
	s/\x00$//;
	@attr = split / /, $_, $ENV{fields};
	$fname = $attr[12];
	
	if($ENV{cwd} =~ m{/.})
	{
		goto return_dir_entry_itself;
	}
	
	if($fname =~ /^\./)
	{
		goto return_dir_entry_itself;
	}
	
	$path = $ENV{basedir}.$ENV{cwd}."/".$fname;
	if(-f $path)
	{
		my $name = getxattr($path, $xattr_displayname);
		
		if(not $name)
		{
			if(open my $fh, "<", $path)
			{
				my %hdr;
				local $/ = "\n";
				while(<$fh>)
				{
					s/[\r\n]//g;
					last if /^$/;
					if(($hname) = /^(From|Subject):\s*/i)
					{
						$hdr{$hname} = [$'\''];
						$pos = tell $fh;
						push @{$hdr{$hname}}, $_ while $_=<$fh> and s/^\s+(.+)[\r\n]*$/$1/;
						seek $fh, $pos, 0;
					}
					last if scalar keys %hdr == 2;
				}
				close $fh;
				
				$hdr_from = encode "utf8", join " ", map { decode "MIME-Header", $_ } @{$hdr{From}};
				$hdr_subj = encode "utf8", join " ", map { decode "MIME-Header", $_ } @{$hdr{Subject}};
				
				$name = join " ✉ ", 
					map {s/^"(.+?)"/$1/; $_} 
					map {s{/}{∕}g; $_}
					map {s{\x00}{}g; $_}
					grep {$_ ne ""} $hdr_from, $hdr_subj;
				
				# setxattr $path, "user.xdg.origin.email.from", $hdr{From}, 0;
				# setxattr $path, "user.xdg.origin.email.subject", $hdr{Subject}, 0;
				setxattr $path, $xattr_displayname, $name, 0;
			}
		}
		
		if($name)
		{
			if($fname =~ /[][]/)
			{
				my $inode = (stat $path)[STAT_INODE];
				$attr[12] = "$name {inode=$inode}.eml";
			}
			else
			{
				$attr[12] = "$name [$fname].eml";
			}
		}
	}
	elsif(!-e $path)
	{
		warn "$path: does not exist. strange.\n";
	}
	
	return_dir_entry_itself:
	$entry = join(" ", @attr) . "\0";
	print $entry;
}
'
else
	exit $ENOENT
fi
