#!/bin/bash

base_url=https://api.entropay.com/api
curlopts=(-sS -H "Content-Type: application/json")
showCardNumber=''
showExpirationDate=''
showCvvCode=''
machineParseable=''


while getopts "hu:p:NXCm" OPT
do
	case "$OPT" in
	u)
		user=$OPTARG
		;;
	p)
		pass=$OPTARG
		;;
	N)
		showCardNumber=1
		;;
	X)
		showExpirationDate=1
		;;
	C)
		showCvvCode=1
		;;
	m)
		machineParseable=1
		;;
	h)
		echo "Usage: entropay -u USER -p PASS [-N] [-X] [-C] [-m]
Options:
  -N   show card number
  -X   show expiration date
  -C   show CVV code
  -m   machine parseable"
		exit 0
		;;
	esac
done

set -e
set -u
test -n "$user"
test -n "$pass"


# Login
page1=$(
 curl "${curlopts[@]}" $base_url/authentication/jwt \
    -d "{\"username\":\"$user\",\"password\":\"$pass\",\"referrerId\":null}"
)

token=$(
 echo "$page1" |\
 jq -r .token
)

test -n "$token"
curlopts+=(-H "Authorization: Bearer $token")


# Get cards' data
content=$(
 curl "${curlopts[@]}" "$base_url/cards/virtual/search?start=0&max=6&availableBalance=true" -d '{"deleted":false}'
)

JQ()
{
	jq -r "$1" <<<"$content"
}


# Display details

n_cards=`JQ '.entries | length'`
n=0
while [ $n -lt $n_cards ]
do
	cardName=`JQ ".entries[$n].displayName"`
	balanceActual=`JQ ".entries[$n].actualBalance"`
	balanceAvailable=`JQ ".entries[$n].availableBalance"`
	[ $showCardNumber ] && cardNumber=`JQ ".entries[$n].cardNumber"` || cardNumber=''
	holder=`JQ ".entries[$n].nameOnCard"`
	[ $showExpirationDate ] && expire=`JQ ".entries[$n].expiryMonth"`/`JQ ".entries[$n].expiryYear"` || expire=''
	if [ $showCvvCode ]
	then
		cvv=`curl "${curlopts[@]}" "$base_url/cards/virtual/$(JQ ".entries[$n].id")/cvv" | jq -r .cvv`
	else
		cvv=''
	fi
	
	if [ ! $machineParseable ]
	then
		balanceActual=${balanceActual/USD/$}
		balanceAvailable=${balanceAvailable/USD/$}
	fi
	
	if [ "$balanceActual" = "$balanceAvailable" ]
	then
		balance="$balanceActual"
	else
		balance="$balanceActual ($balanceAvailable)"
	fi
	
	if [ $machineParseable ]
	then
		echo "$cardNumber;$balanceActual;$balanceAvailable;$expire;$cvv;$holder;$cardName"
	else
		if [ $showCardNumber$showExpirationDate$showCvvCode ]
		then
			echo "$cardName
  $balance
  ${cardNumber:+${cardNumber:0:4}-${cardNumber:4:4}-${cardNumber:8:4}-${cardNumber:12}  }${expire:+[$expire]  }${cvv:+CVV:$cvv}
  $holder"
		else
			echo "$cardName $balance"
		fi
	fi
	
	n=$[n+1]
done

