#!/bin/bash

set -e
set -u

set -- `git remote -v | head -n1 | perl -ne 'm{github.com[/:](.+?)/([^/.]+)} and print "$1 $2"'`
user=$1
repo=$2

set +e
set -o pipefail

if curl -sS https://api.github.com/repos/$user/$repo/issues | tee .git/issues.json~
then
	mv .git/issues.json~ .git/issues.json
else
	cat .git/issues.json
fi|\
jq -r 'map([
	.number,
	"\n==========================",
	([(.number|tostring)+":",.title]|join(" ")),
	(["   "+.state,(.labels|.[].name)]|join(", ")),
	"--------------------------",
	.body
]) |
sort | .[] | .[1:] | join("\n")'
