#!/bin/bash
# script
# dependencies: curl html2text awk

# variables, constans, defaults
self="${0##*/}"
ver=0.1
ekezet=nemszamit
egyezes=resz

perror() {
	echo "$self: $@" >&2
}

# check arguments
while [ -n "$1" ]; do
	case "$1" in
	"-h"|"-?"|"--help"|"-help")
		echo "Usage: ${0##*/} [-e|-E] [-b|-s|-t] [szó]
-e     ékezet nem számít (default)
-E     ékezet számít
-b     bármilyen egyezés (default)
-s     szó eleji egyezés
-t     teljes egyezés
szó    amire keresel a szótárban"
		exit 0;;
	"-V"|"--version"|"-version")
		echo "${0##*/}: vesrion $ver" >&2
		exit 0;;
	-e)
		ekezet=nemszamit;;
	-E)
		ekezet=szamit;;
	-b)
		egyezes=resz;;
	-s)
		egyezes=szoeleji;;
	-t)
		egyezes=teljes;;
	--)
		shift
		break
		;;
	-*)
		false
		;;
	*)
		break
		;;
	esac
	shift
done

# main script


q=$(echo "$@" | od -t x1 -A n | tr " " % | tr -d "\n\r")

curl -s -d "q=$q&ekezet=$ekezet&egyezes=$egyezes" http://www.magyarhelyesiras.hu/ | awk '/<p>Keresett szó:/,/<!-- Keresett szavak:/' | \
html2text -utf8 #| \
# pipeline to pager if stdout is a terminal
#if [ -t 1 -a -x "`which sensible-pager`" ]; then sensible-pager; else cat; fi

