#!/bin/bash

EPERM=1
ENOENT=2
EIO=5
EBADF=9
EAGAIN=11
EACCESS=13
EBUSY=16
EEXIST=17
ENOTDIR=20
EISDIR=21
EINVAL=22
EFBIG=27
ENOSPC=28
ESPIPE=29
ENOSYS=38
ENOTEMPTY=39
EOPNOTSUPP=95

set -x; exec 2>>/tmp/d

GID=0
fmode=-rw-r--r--
dmode=drwxr-xr-x

print_entry_dir()
{
	mode=$dmode size=0 print_entry "$@"
}

print_entry_file()
{
	mode=$fmode print_entry "$@"
}

print_entry()
{
	echo -ne "ino=1 mode=$mode nlink=2 uid=$UID gid=$GID rdev=0 size=${size:-0} blksize=512 blocks=0 atime=0 mtime=0 ctime=0${1:+ $1\0}"
}


fuse_operation=${0##*/}

case "$fuse_operation" in
readdir)
	exit 0
;; # readdir

getattr)
	if [ "$1" = / ]
	then
		print_entry_dir
		exit 0
	fi
	content=${1:1}
	size=${#content}
	print_entry_file
	exit 0
;; # getattr

read_file)
	echo -n "${1:1}"
	exit 0
;; # read_file
esac

exit $ENOSYS
