#!/bin/bash

echo "|   |   |"
echo "|---|---|"

for filepath in admin-tools/* compiled-tools/*.pod crawler-bin/* root-tools/* user-tools/* xwin-tools/*
do
	if [ -f "$filepath" ]
	then
		echo $'=pod\n\n=head1 FILEPATH '"$filepath"$'\n\n=cut\n\n'
		cat "$filepath"
		echo $'=pod\n\n=head1 EOF '"$filepath"$'\n\n=cut\n\n'
	fi
done |\
pod2text -w 10000 --utf8 |\
while IFS=$'\n' read line
do
	if [[ $line =~ ^FILEPATH[\ \	]+(.+) ]]
	then
		filepath=${BASH_REMATCH[1]}
		dirpath=${filepath%/*}
	
	elif [ "$line" = NAME ]
	then
		while IFS=$'\n' read line2
		do
			if [[ $line2 =~ ^[\ ]+([^ ]+)[\ ]+-[\ ]+(.+) ]]
			then
				name=${BASH_REMATCH[1]}
				description=${BASH_REMATCH[2]}
				
				filelink=$dirpath/$name
				if [ "${filepath: -4}" = .pod ]
				then
					filelink=$dirpath/$name.c
				fi
				if [ ! -e "$filelink" ]
				then
					filelink=($dirpath/*/$name.*)
					filelink=${filelink[0]}
				fi
				if [ ! -e "$filelink" ]
				then
					filelink=$filepath
				fi
				
				echo "| [$name]($filelink) | $description"
			elif [[ $line2 =~ ^[^\ \	] ]]
			then
				break
			fi
		done
	fi
done |\
sort -u
