#!/bin/bash

echo "|   |   |"
echo "|---|---|"

for filepath in admin-tools/* compiled-tools/* crawler-bin/* root-tools/* user-tools/* xwin-tools/*
do
	if [ -f "$filepath" ]
	then
		path=${filepath%/*}
		echo $'=pod\n\n=head1 PATH '"$path"$'\n\n=cut\n\n'
		cat "$filepath"
	fi
done |\
pod2text -w 10000 --utf8 |\
while IFS=$'\n' read line
do
	if [[ $line =~ ^PATH\ (.+) ]]
	then
		path=${BASH_REMATCH[1]}
	
	elif [ "$line" = NAME ]
	then
		while IFS=$'\n' read line2
		do
			if [[ $line2 =~ ^[\ ]+([^ ]+)[\ ]+-[\ ]+(.+) ]]
			then
				name=${BASH_REMATCH[1]}
				description=${BASH_REMATCH[2]}
				echo "| [$name]($path/$name) | $description"
			elif [[ $line2 =~ ^[^\ ] ]]
			then
				break
			fi
		done
	fi
done |\
sort -u
