#!/bin/bash

. "`dirname "$(readlink -f "$0")"`/common.sh"

fname=`virt2phy_filepath "$1" "$2"`

if [ -e "$2$fname" ]
then
	if find -L "$2$fname" -maxdepth 0 \
		-printf 'ino=%i mode=%M nlink=%n uid=%U gid=%G rdev=0 size=%s blksize=512 blocks=%b atime=%A@ mtime=%T@ ctime=%C@' \
		-quit
	then
		exit 0
	else
		exit $EIO
	fi
else
	exit $ENOENT
fi
