#!/usr/bin/env perl

# unicode-aware expand(1) replacement

use Encode;
binmode STDIN, ":utf8";
binmode STDOUT, ":utf8";

$tabstop = 4;
$tabstopMinusOne = $tabstop - 1;

while(<STDIN>)
{
	s/((?<A>[^\t]{0,$tabstopMinusOne})\t|(?<A>[^\t]{$tabstop}))/sprintf "%s%s", $+{A}, " " x ($tabstop - length $+{A})/ge;
	print;
}
