#!/bin/bash

# this script makes symlinks to git project directories which are in ~/src,
# and place these symlinks in directories names after the git project's author,
# which is generally the github owner's username.

if [ $# = 0 ]
then
	dirs=(~/src/*/)
else
	dirs=()
	for dir in "$@"
	do
		dirs+=("$(readlink -f "$dir")")
	done
fi

mydir=`dirname "$0"`
cd "$mydir" || exit -1

for repo in "${dirs[@]}"
do
	(
	author=''
	if [ -d "$repo/.git" ]
	then
		for remote in github github.com origin
		do
			remote_url=`GIT_DIR=$repo/.git git remote get-url "$remote" 2>/dev/null`
			if [ -n "$remote_url" ]
			then
				if [[ $remote_url =~ [/:]([^/]+)/([^/]+)/?$ ]]
				then
					author=${BASH_REMATCH[1]}
					break
				fi
			fi
		done
		if [ -n "$author" ]
		then
			[ -d "$author" ] || mkdir "$author"
			ln -snfr "$repo" "$author/"
		else
			echo "unknown author of $repo" >&2
		fi
	fi
	) &
done

wait
