#!/bin/bash


PIDS=()
parents=0
declare -A show
show[exe]=1
show[cwd]=0
show[comm]=0
show[cmdline]=1
show[started]=0
show[name]=0
show[state]=0
show[tgid]=0
show[ngid]=0
show[ppid]=0
show[pgid]=0
show[psid]=0
show[tracerpid]=0
show[uid]=1
show[gid]=0
show[files]=0
show[groups]=0
show[env]=0
show_pid_only=0


is_integer()
{
	[ "$1" -ge 0 -o "$1" -lt 0 ] 2>/dev/null
}

in_list()
{
	local needle=$1
	shift
	for hay
	do
		if [ "$needle" = "$hay" ] ; then return 0 ; fi
	done
	return 1
}

indent()
{
	local tabs=''
	local i
	for ((i=1; i<=$1; i++)); do tabs=$tabs$'\t'; done
	sed -e "s/^/$tabs/"
}

add_proc_name()
{
	local pidlist=(`pidof "$1"`)
	if [ ${#pidlist[@]} = 0 ]
	then
		pidlist=(`pgrep "$1"`)
	fi
	if [ ${#pidlist[@]} = 0 ]
	then
		pidlist=(`pgrep -f "$1"`)
	fi
	if [ ${#pidlist[@]} = 0 ]
	then
		echo "No such process: $1" >&2
		return 1
	else
		PIDS+=("${pidlist[@]}")
	fi
	return 0
}

add_proc_any()
{
	if is_integer "$1"
	then
		PIDS+=($1)
	else
		add_proc_name "$1"
	fi
}

set_show_almost_all()
{
	show[exe]=1
	show[cwd]=1
	show[comm]=1
	show[cmdline]=1
	show[started]=1
	show[name]=1
	show[state]=1
	show[tgid]=1
	show[ngid]=1
	show[ppid]=1
	show[pgid]=1
	show[psid]=1
	show[tracerpid]=1
	show[uid]=1
	show[gid]=1
	show_pid_only=0
}


while [ -n "$1" ]
do
	case "$1" in
	-p)
		shift
		PIDS+=("$1")
		;;
	-n)
		shift
		add_proc_name "$1"
		;;
	--parent)
		parents=1
		;;
	-P|--parents)
		shift
		if [ "${1:0:1}" = - ]
		then
			parents=all
			continue
		elif is_integer "$1"
		then
			parents=$1
		else
			break
		fi
		;;
	--exe|--cwd|--cmdline|--started|--name|--state|--tgid|--ngid|--ppid|--pgid|--psid|--tracerpid|--uid|--gid|--files|--groups|--env)
		show[${1:2}]=1
		;;
	-a|--all)
		set_show_almost_all
		show[files]=1
		show[groups]=1
		;;
	-A|--almost-all)
		set_show_almost_all
		;;
	-o|--pid-only)
		show_pid_only=1
		;;
	-h|--help)
		echo -n "Usage: proc [options] [PID | PROCNAME [PID | PROCNAME [...]]]
Options:
 -p PID [-p PID [...]]
 -n PROCNAME [-n PROCNAME [...]]
 --parent
 --parents, -P [DEPTH]
 -a, --all, -A, --almost-all
 --exe, --cwd, --cmdline, --name
 --started, --state
 --tgid, --ngid, --ppid, --tracerpid, --pgid, --psid
 --uid, --gid
 --files, --groups, --env
 -o, --pid-only
"
		exit 0
		;;
	-*)
		echo "Unknown option: $1" >&2
		exit 1
		;;
	--)
		shift
		break
		;;
	*)
		add_proc_any "$1"
		;;
	esac
	shift
done

while [ -n "$1" ]
do
	add_proc_any "$1"
	shift
done


# filter out self pid
PIDS=(`echo "${PIDS[@]}" | tr " " "\n" | grep -vx $$`)


set -u


display_info()
{
	local pid=$1
	
	if [ -z "$pid" ] || [ "$pid" = 0 ]
	then
		return
	fi
	if in_list $pid "${pidstack[@]}"
	then
		return
	fi
	
	pidstack+=("$pid")
	
	
	if [ ! -r /proc/$pid ]
	then
		return 1
	fi
	
	for x in exe cwd
	do
		if [ ${show[$x]} = 1 ]
		then
			echo -n "$x: "
			readlink /proc/$pid/$x
		fi
	done
	
	if [ ${show[comm]} = 1 ]
	then
		echo -n "comm: "
		cat /proc/$pid/comm
	fi
	
	if [ ${show[cmdline]} = 1 ]
	then
		local cmdline
		cmdline=`cat /proc/$pid/cmdline | tr "\0" " "`
		if [ -z "$cmdline" ]
		then
			cmdline=`cat /proc/$pid/comm`
		fi
		echo "cmdline: $cmdline"
	fi
	
	if [ ${show[started]} = 1 ]
	then
		echo -n "started: "
		ps o lstart='' -p $pid
	fi
	
	if [ ${show[pgid]} = 1 -o ${show[psid]} = 1 ]
	then
		cat /proc/$pid/stat | tr ')' '\n' | tail -1 |\
		{
			read x x pgid psid x
			
			if [ ${show[pgid]} = 1 ]
			then
				echo "PGID: $pgid"
			fi
			
			if [ ${show[psid]} = 1 ]
			then
				echo "PSID: $psid"
			fi
		}
	fi
	
	cat /proc/$pid/status |\
	while read -r attrname attrval
	do
		attrname=${attrname%:}
		case "$attrname" in
		Name|State)
			if [ ${show[${attrname,,}]} = 1 ]
			then
				echo "$attrname: $attrval"
			fi
			;;
		Tgid|Ngid|PPid|TracerPid)
			if [ ${show[${attrname,,}]} = 1 ]
			then
				echo "$attrname: $attrval"
			fi
			
			if [ $attrname = PPid ]
			then
				if [ $parents = all ] || [ $parents -ge $[ ${#pidstack[@]} - 1 ] ]
				then
					if [ ${show[${attrname,,}]} != 1 ]
					then
						echo "$attrname: $attrval"
					fi
					display_info $attrval | indent 1
				fi
			fi
			;;
		Uid|Gid|Groups)
			if [ ${show[${attrname,,}]} = 1 ]
			then
				echo -n "$attrname: "
				for id in $attrval
				do
					entsvc=group
					if [ $attrname = Uid ]; then entsvc=passwd; fi
					name=`getent $entsvc "$id" | cut -f1 -d:`
					echo -n "$name($id) "
				done
				echo
			fi
		esac
	done
	
	if [ ${show[files]} = 1 ]
	then
		echo -n "files:"
		find /proc/$pid/fd -printf "%l\n" 2>/dev/null | sort -u | tr "\n" " "
		echo
	fi
	
	if [ ${show[env]} = 1 ]
	then
		echo -n "env: "
		cat /proc/$pid/environ 2>/dev/null | tr "\000" "\n" | sort | tr "\n" " "
		echo
	fi
	
	unset pidstack[$((${#pidstack[@]}-1))]
}


pidstack=('')
exitstatus=2

if [ ${#PIDS[@]} = 0 ]
then
	echo "No such process found." >&2
	exit 1
fi

for pid in "${PIDS[@]}"
do
	if [ -n "$pid" -a -d /proc/$pid ]
	then
		exitstatus=0
		if [ $show_pid_only = 1 ]
		then
			echo -n "$pid "
		else
			echo "PID: $pid"
			display_info $pid | indent 1
		fi
	fi
done

exit $exitstatus
