#!/bin/bash

_git_mirrors()
{
    local subcommands="ls ls-remotes add-remotes-to-mirrors ls-new-mirrors"
    local subcommand="$(__git_find_on_cmdline "$subcommands")"
    if [ -z "$subcommand" ]; then
        case "$cur" in 
            *)
                __gitcomp "$subcommands"
            ;;
        esac
        return
    fi
}
