#!/bin/bash

set -e
set -o pipefail

cd /var/run/pam_vouch

_resolveip()
{
	local host=$1
	if [ "${host:0:1}" = '[' ]
	then
		host=${host:1}
		host=${host%%]*}
	else
		host=${host%%:*}
	fi
	resolveip "$host"
}

bolden()
{
	echo -ne "[1m"
	echo -n "$*"
	echo -ne "[m"
}

for file in req-*
do
	uuid=${file:4}
	
	# note, $file is trusted
	. $file
	age=`perl -MTime::Duration -e "print ago(time - $PAM_VOUCH_TIMESTAMP)"`
	exp=`perl -MTime::Duration -e "print ago(time - $PAM_VOUCH_EXPIRE)"`
	
	echo "Access request:"
	echo "  when:            $(date -d "@$PAM_VOUCH_TIMESTAMP") ($(bolden "$age"))"
	echo "  request expires: $(date -d "@$PAM_VOUCH_EXPIRE") ($exp)"
	echo "  source host:     $PAM_RHOST"
	echo -n "  "; _resolveip "$PAM_RHOST"
	echo "  tty:             $PAM_TTY"
	echo "  local service:   $PAM_SERVICE"
	echo "  login as:        $(bolden "$PAM_USER")"
	echo
	
	read -e -p "Allow? [y/n] " reply
	
	if [ $PAM_VOUCH_EXPIRE -le `date +%s` ]
	then
		echo "Request expired in the meanwhile."
	else
		if [ ".$reply" = .y ]
		then
			touch "allow-$uuid"
			echo "You granted access."
		elif [ ".$reply" = .n ]
		then
			rm "req-$uuid"
			echo "You denied access."
		else
			echo "Undecided."
		fi
	fi
	echo
done
