#!/bin/bash

set -e

trap 'help; exit 255' ERR

help()
{
	echo "Használat: $0 [felhasználási_hely_azonosító] [mérőóra_gyári_száma] [email] [óraállás]"
}

test $# = 4

fogyhely=$1
merogysz=$2
email=$3
meroallas=$4

url=https://www.alfoldviz.hu/ugyfelszolgalat/meroallas-bejelentes
curlargs=(-sS)

# get session (and other) cookie
cookies=`curl "${curlargs[@]}" "$url" -H "Cookie: acceptCookies=1" -c /dev/fd/3 3>&1 1>/dev/null | sed -e 's/^#HttpOnly_//'`
# add 'acceptCookies' cookie to the cookie jar
cookies="$cookies"$'\n'"$(tail -n1 <<<"$cookies" | awk '{print $1,$2,$3,$4,$5}') acceptCookies 1"
# get CSRF token
csrf_token=`curl "${curlargs[@]}" "$url" -b /dev/fd/3 3<<<"$cookies" | pup 'input[name=_token] attr{value}'`

# fill form input fields
curlargs+=( \
	-d "ugyfelazonosito=$fogyhely" \
	-d "email=$email" \
	-d "meters[0][gyariszam]=$merogysz" \
	-d "meters[0][meter]=$meroallas" \
	-d "_token=$csrf_token" \
)

# fire report
response=`curl -i -L "${curlargs[@]}" "$url" -b /dev/fd/3 3<<<"$cookies" 2>&1`

if echo "$response" | grep -o "Az adatok feldolgozását megkezdtük."
then
	exit 0
else
	echo "Az Alföldvíz nem nyugtázta a bejelentést." >&2
	tmp=`tempfile -s .txt`
	{
		echo == Cookies
		echo "$cookies"
		echo
		echo == Curl args
		echo "${curlargs[@]}" "$url"
		echo
		echo == Response
		echo "$response"
	}>"$tmp"
	echo "Diagnosztika mentve ebbe a fájlba: $tmp" >&2
	exit 1
fi
