#!/bin/bash

set -e

curlargs=(-sS)
HelpText="Használat: $0 [felhasználási_hely_azonosító] [mérőóra_gyári_száma] [email] [óraállás]
  $0 --history [email] [jelszó]"
response=''
declare -g Cookies="acceptCookies=1"


assert()
{
	local msg=$1
	shift
	if ! command "$@"
	then
		echo "$msg" >&2
		save_diag
		exit 1
	fi
}

save_diag()
{
	tmp=`tempfile -s .txt`
	{
		echo == Cookies
		echo "$Cookies"
		echo
		echo == Curl args
		echo "${curlargs[@]}" "$url"
		if [ -n "$response" ]
		then
			echo
			echo == Response
			echo "$response"
		fi
	}>"$tmp"
	echo "Diagnosztika mentve ebbe a fájlba: $tmp" >&2
}

http_headers()
{
	awk 'BEGIN{h=1} { if(/^\r?$/){h=0} if(h){print} }'
}

extract_cookies()
{
	http_headers | grep -i ^Set-Cookie: | cut -f2 -d: | cut -f1 -d';' | tr "\n" ";"
}

start_session()
{
	local url=$1
	# get session (and other) cookie
	local cookies=`curl "${curlargs[@]}" "$url" -b "$Cookies" -i | extract_cookies`
	Cookies="$Cookies;$cookies"
}

urlencode()
{
	local s=$1
	s=${s//+/%2B}
	echo "$s"
}
	

if [ ".$1" = .--history ]
then
	url=https://www.alfoldviz.hu/ugyfelszolgalat/e-ugyfelszolgalat
	start_session "$url"
	
	url=https://www.alfoldviz.hu/ugyfelszolgalat/e-ugyfelszolgalat/bejelentkezes
	email=`urlencode "$2"`
	password=`urlencode "$3"`
	response=`curl "${curlargs[@]}" -i "$url" -d "email=$email" -d "password=$password" -b "$Cookies"`
	echo "$response" |\
	{
		read httpver status message
		[ "$status" = 302 ]
		while IFS=: read -r header content
		do
			if [ "$header" = Location ] && expr "$content" : '.*bejelentkezes' >/dev/null
			then
				echo "Hibás bejelentkezés" >&2
				exit 2
			fi
			if [ -z "$header" ]
			then
				break
			fi
		done
	}
	ps=("${PIPESTATUS[@]}")
	assert "Rossz státusz bejelentkezéskor" [ ${ps[1]} = 0 ]
	Cookies="acceptCookies=1;"`echo "$response" | extract_cookies`
	
	url=https://www.alfoldviz.hu/ugyfelszolgalat/e-ugyfelszolgalat/korabbi-meroallasok-listaja/betoltes
	curl "${curlargs[@]}" "$url" -b "$Cookies" | html2text -utf8
	exit ${PIPESTATUS[0]}
fi

assert "$HelpText" [ $# = 4 ]

fogyhely=$1
merogysz=$2
email=$3
meroallas=$4

url=https://www.alfoldviz.hu/ugyfelszolgalat/meroallas-bejelentes
start_session "$url"
# get CSRF token
csrf_token=`curl "${curlargs[@]}" "$url" -b "$Cookies" | pup 'input[name=_token] attr{value}'`
assert "CSRF tokent nem találtam" [ -n "$csrf_token" ]

# fill form input fields
curlargs+=( \
	-d "ugyfelazonosito=$fogyhely" \
	-d "email=$email" \
	-d "meters[0][gyariszam]=$merogysz" \
	-d "meters[0][meter]=$meroallas" \
	-d "_token=$csrf_token" \
)

# fire report
response=`curl -i -L "${curlargs[@]}" "$url" -b "$Cookies" 2>&1`

if echo "$response" | grep -o "Az adatok feldolgozását megkezdtük."
then
	exit 0
else
	echo "Az Alföldvíz NEM nyugtázta a bejelentést." >&2
	save_diag
	exit 1
fi
