#!/bin/bash

# EXIT CODES
#   0 - outage is not expected
#  10 - outage IS expected
#   * - crawler error (see there)

set -u

telepules=$1
utca=$2

./aramszunetek "$telepules" |\
html2text -utf8 |\
grep "$utca"

ps=(${PIPESTATUS[@]})
if [ ${ps[0]} != 0 ]
then
	echo "crawler error" >&2
	exit ${ps[0]}
else
	if [ ${ps[2]} = 0 ]
	then
		echo "Áramszünet VÁRHATÓ" >&2
		exit 10
	else
		echo "Áramszünet nem várható" >&2
		exit 0
	fi
fi
