#!/bin/bash

true <<EOF
=pod

=head1 NAME

2opml - Convert list of URLs to OPML.

=head1 SYNOPSIS

2opml [--add-attributes <ATTRIBUTES>] < urls.txt

=head1 DESCRIPTION

Convert text file, containing "<TITLE> <URL>" looking lines, to OPML.

=cut
EOF


xmlquote()
{
	local s=$1
	s=${s//&/&amp;}
	s=${s//</&lt;}
	s=${s//>/&gt;}
	s=${s//\"/&quot;}
	echo "$s"
}

add_attributes=''

while [ $# != 0 ]
do
	case "$1" in
	--help)
		echo "Usage: 2opml [--add-attributes <ATTRIBUTES>] < urls.txt"
		echo "Convert text file, containing \"<TITLE> <URL>\" looking lines, to OPML."
		exit;;
	--add-attributes)
		shift
		add_attributes=$1;;
	--)
		shift
		break;;
	-*)
		break;;
	esac
	shift
done

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<opml version=\"1.0\"><body>"

while read -r title url
do
	title=`xmlquote "$title"`
	url=`xmlquote "$url"`
	
	echo "<outline type=\"rss\" title=\"$title\" text=\"$title\" xmlUrl=\"$url\" $add_attributes />"
done

echo "</body></opml>"
