#!/usr/bin/env perl

use warnings;
no if ($] >= 5.018), 'warnings' => 'experimental::smartmatch';
use MIME::Base64 qw/encode_base64url decode_base64url/;

if($ARGV[0] ~~ ['-d', '--decode'])
{
	undef $/;
	print decode_base64url(<STDIN>);
}
elsif(not @ARGV)
{
	undef $/;
	print encode_base64url(<STDIN>);
}
else
{
	die "Usage: $0 [-d | --decode]\n";
}

__END__

=pod

=head1 NAME

base64url - Encode to (decode from) Base64-URL encoding

=cut

