#!/usr/bin/env perl

=pod

=head1 NAME

confpatch - set options/values in config file of various formats

=head1 SYNOPSIS

confpatch I<CONFIG_FILE> < I<INPUT_FILE>

=head1 DESCRIPTION

Take config option keys and values on I<INPUT_FILE>
and edit I<CONFIG_FILE> line-based config file in-place
to set those config options to the input value (leaving old lines in C<#>-prefixed comment),
or add those options in I<CONFIG_FILE> if not yet found in it.

=head1 ENVIRONMENT

=over 4

=item B<CONFPATCH_TYPE>

One of B<environment>, B<simple-space>, B<custom>.

=item B<CONFPATCH_KV_PATTERN>

Regexp with 2 capture groups to find option keys and values in I<CONFIG_FILE> when B<CONFPATCH_TYPE> is B<custom>.

=item B<CONFPATCH_POST_CHANGE>

Shell command run after there was any modifications to I<CONFIG_FILE>.

=back

=head1 EXAMPLES

 CONFPATCH_TYPE="environment" confpatch /etc/environment < ...
 
 CONFPATCH_TYPE="simple-space" confpatch /etc/screenrc < ...

 CONFPATCH_TYPE="custom" CONFPATCH_KV_PATTERN='^set\s+(\S+)\s+(.+)$$' confpatch /etc/inputrc < ...

=head1 LIMITATIONS

=head1 SEE ALSO

=cut


use Fcntl qw/:flock :seek/;

$input_type = $ENV{'CONFPATCH_TYPE'};
if($input_type eq 'environment')
{
	$variable_definition_regex = qr/^(?:export )?([^=]+)=(.*)$/;
}
elsif($input_type eq 'simple-space')
{
	$variable_definition_regex = qr/^(\S+)\s*(.*)$/;
}
elsif($input_type eq 'custom')
{
	#$variable_definition_regex = qr/^$lead_regex($key_regex)$separator_regex($value_regex)$trail_regex$/;
	$variable_definition_regex = $ENV{'CONFPATCH_KV_PATTERN'} or die "$0: no CONFPATCH_KV_PATTERN given\n";
}
else
{
	die "$0: unknown input type given in CONFPATCH_TYPE: $input_type, valid types: environment, simple-space, custom\n";
}

$Changed = 0;
$target_file = $ARGV[0];

open $target_fh, '+<', $target_file or die "$0: open $target_file: $!\n";
flock $target_fh, LOCK_EX or die "$0: lock $target_file: $!\n";

while($variable_definition = <STDIN>)
{
	chomp $variable_definition;
	# TODO: keep comment block belonging to a setting
	next if $variable_definition =~ /^#/;
	next if $variable_definition =~ /^\s*$/;
	if(my ($varname, $qvalue) = $variable_definition =~ /$variable_definition_regex/)
	{
		my $value = $qvalue =~ s/^"(.*?)"$/$1/r;  # $value is not quoted, $qvalue is the original value which is maybe quoted
		$variable_set = 0;
		seek $target_fh, 0, SEEK_SET;
		while(do{ $pos = tell $target_fh; $target_line = <$target_fh>; })
		{
			chomp $target_line;
			next if $target_line =~ /^#/;
			if(my ($old_varname, $old_qvalue) = $target_line =~ /$variable_definition_regex/)
			{
				if($old_varname eq $varname)
				{
					my $old_value = $old_qvalue =~ s/^"(.*?)"$/$1/r;
					if($old_value ne $value)
					{
						local $/ = undef;
						my $buffer_rest_of_file = <$target_fh>;
						seek $target_fh, $pos, SEEK_SET;
						print {$target_fh} "#$target_line\n";
						print {$target_fh} "$variable_definition\n";
						print {$target_fh} $buffer_rest_of_file;
						warn "$0: patched $varname\n";
						$Changed = 1;
					}
					$variable_set = 1;
					last;
				}
			}
		}
		if(not $variable_set)
		{
			print {$target_fh} "$variable_definition\n";
			warn "$0: added $varname\n";
			$Changed = 1;
		}
	}
	else
	{
		warn "$0: invalid input line $.: $_\n";
	}
}

if($Changed)
{
	$run_on_change = $ENV{'CONFPATCH_POST_CHANGE'};
	if($run_on_change)
	{
		warn "$0: running: $run_on_change\n";
		my $shell = $ENV{'SHELL'} || '/bin/sh';
		exec $shell, '-c', $run_on_change;
		exit 127;
	}
}
