#!/bin/bash

true <<'EOF'
=pod

=head1 NAME

cpyfattr - Copy file attributes (xattr)

=head1 SYNOPSIS

cpyfattr I<SOURCE> I<DESTINATION> [I<OPTIONS>]

=head1 DESCRIPTION

Copy I<SOURCE> file'Z<'>s all xattributes to I<DESTINATION>
using getfattr(1) and setfattr(1).

=head1 OPTIONS

All options passed to setfattr(1).
Note that I<OPTIONS> are at the end of argument list.

=head1 SEE ALSO

getfattr(1), setfattr(1)

=cut

EOF



set -e
set -o pipefail
set -u

source=$1
shift
dest=$1
shift

{
echo "# file: $dest"
getfattr -d "$source" | sed -e 1d
} | setfattr --restore=- "$@"
