#!/bin/bash

true <<'EOF'
=pod

=head1 NAME

cred - Credentials and secrets management in command line

=head1 SYNOPSIS

cred I<SUBCOMMAND> I<SITE> [I<ARGUMENTS>]

cred site I<SITE> I<SUBCOMMAND> [I<ARGUMENTS>]

=head1 DESCRIPTION

I<SITE>, most often a website name, is a container of one or more properties.
But it can be anything you want to tie properties to,
typically passwords, keys, pin codes, API tokens as secrets and 
username, email address, etc. as ordinary properties.

I<SITE> is represented in a directory in the credentials base dir.
You may also enter a directory path on the filesystem for I<SITE>.
You don't need to create a I<SITE>: it's created automatically when you write in it.

For websites and other services you have more than one account or identity for,
recommended to organize them into sub-directories like: I<SITE>/I<IDENTITY>,
eg: C<mail.example.net/joe@example.net> and C<mail.example.net/jane@example.net>.

=head1 SUBCOMMANDS

=over 4

=item compscript

Output a bash script to setup tab-completion for the C<cred> command.
Use it by eg: C<eval "$(cred compscript)">

=item list-sites

=item dump [reveal-secrets | mask-secrets | hash-secrets | blank-secrets] [subdirs]

Display all properties (and their values) of a given site.
Optional parameter is how secrets are displayed:
B<mask-secrets> is the default and replaces a secret string with 5 asterisks (C<*****>) uniformly (so number of chars are not leaked).
B<hash-secrets> replaces secrets by a hash and the checksum algorithm' name
is appended to the hash with a tab, like: <TAB>B<hash-algo=>I<NAME>.
B<blank-secrets> displays the secret property name but leaves the value field empty.
Finally B<reveal-secrets> displays secret strings in clear text just like ordinary properties.

The option B<subdirs> dumps properties from the sub-directories too.

Those properies are considered to be secret at the moment which contain at least one of these words (case insensitive) :
B<pass>, B<key>, B<cvc>, B<secret>, B<pin>, B<code>, B<token>, B<totp> (but not B<totp-issuer>).

=item generate-password

Generate a new password and put in B<PASSWORD> property;
append its old value to the B<OLDPASSWORDS> property;
copy the new one to the clipboard.

=item list-props

=item prop I<PROPERTY> [set I<NEW-VALUE> | edit | read | del | show | reveal | clip]

Manage properties of a given site.
See individual instruction descriptions at the subcommands below which are aliases to these B<prop ...> commands.

=item set I<PROPERTY> I<NEW-VALUE>

=item edit I<PROPERTY>

Open up the B<$EDITOR> (falling back to B<$VISUAL>) to edit the given property's value.
=item read I<PROPERTY>

Read the new value from the STDIN (readline is supported if bash does support it, see C<help read> in bash(1)).
Secrets are read in no-echo mode.

=item del I<PROPERTY>

=item show I<PROPERTY>

=item reveal I<PROPERTY>

Subcommand B<show> shows only non-secrets.
Enter B<reveal> to show secrets as well.

=item clip I<PROPERTY>

By B<clip> you may copy the value to the clipboard.
If you use CopyQ(1), secrets are prevented to get to CopyQ's clipboard items history.

=item fill-form I<PROPERTY> [I<PROPERTY> [...]]

Takes one or more property names and types their values to the window accessible by pressing Alt+Tab on your desktop.
Also presses <TAB> after each string, but does not press <RETURN>.
A single dot (C<.>) is a pseudo I<PROPERTY> name: if it's given, nothing will be typed in its place,
but <TAB> is still pressed after it.
Use it if the form has fields which you don't want to fill in.
Obviously it's useful only with a B<$DISPLAY>.
Depends on xdotool(1).

=back

=head1 SPECIAL PROPERTIES

=over 4

=item B<TOTP>

TOTP property (Timed One-Time Passcode) can be B<set> (simply by C<cred ... set TOTP>, no value needed), B<del>elted, B<show>n, and B<reveal>ed.
When accessed, cotp(1) programm is called to search a TOTP code with its ISSUER (combined with LABEL, if taking the ISSUER only would be ambiguous)
matching to the selected I<SITE>.

How I<SITE> and ISSUER (LABEL) are matched:
If the site has B<OTP-ISSUER> propery, it is searched.
Otherwise the site's name itself is takes as ISSUER name.
If the site is at more than 1 directory levels deep under the credentials base dir, then only the first path component satisfies the search criteria as well.
For example, TOTP codes for a site like "example.com/my-2nd-account" are searched under both "example.com/my-2nd-account" and "example.com" issuers.

If the above filtering yields more than 1 cotp(1) records, it's further filtered by LABEL.
The following properties are tried as LABEL in order: EMAIL, USERNAME, LOGIN.
Once only 1 cotp(1) record is yielded, it is taken as the TOTP code.

=back

=head1 FILES

Credentials directory is hardcoded to F<~/cred>.

=head1 SEE ALSO

=over 4

=back

=cut

EOF



# need to set these shell options before they are relied upon when bash parses the big { ... } block later down.
shopt -s nocasematch
shopt -s expand_aliases
# aliases in non-interactive bash script are not evaluated in the same scope where they are defined,
# but they are in the big { ... } block below.
alias set_site='if [ -z "${site:-}" ]; then set_site_func "${1:-}"; shift; fi;'

{
set -eE
set -o pipefail
set -u

. /usr/lib/tool/bash-utils

colors_supported()
{
	if [ -n "${NO_COLOR:-}" ]; then return 1; fi
	if [ -n "${CLICOLOR_FORCE:-}" ]; then return 0; fi
	[ -t 1 ]
}
if colors_supported; then . /usr/lib/tool/ansi-codes; fi

TAB=$'\t'

print_traceback()
{
	local i stack_size=${#FUNCNAME[@]}
	for (( i=1; i<stack_size; i++ )); do
		local func="${FUNCNAME[$i]}"
		[[ $func = "" ]] && func=MAIN
		local linen="${BASH_LINENO[$(( i - 1 ))]}"
		local src="${BASH_SOURCE[$i]}"
		[[ "$src" = "" ]] && src=non_file_source
		
		echo -n "${ANSI_bold:-}${ANSI_fg_black:-}"
		echo "  function: $func"
		echo "  file: $src (line $linen)"
		echo -n "${ANSI_reset:-}"
		
		local line_number_text_sep='| '
		nl -ba -w ${#linen} -s " $line_number_text_sep" "$src" | grep -C 2 -E "^\s*$linen " |\
			prefixlines "    " |\
			sed -e "s/^\(\s*$linen\) \(.\{${#line_number_text_sep}\}\)\(.*\)/\1-\2${ANSI_italic:-}\3${ANSI_normal:-}/" |\
			sd '^' "${ANSI_bold:-}${ANSI_fg_black:-}" | sd '$' "${ANSI_reset:-}"
	done
}

trap 'print_traceback >&2' ERR


exit_with_msg()
{
	if [ ! $opt_quiet ]
	then
		warnx "$2"
	fi
	exit $1
}

set_site_func()
{
	local param=$1
	if [ -z "$1" ]
	then
		exit_with_msg 1 "Enter site name or directory!"
	elif [ -d "$param" ]
	then
		site=`basename "$param"`
	else
		site=$1
	fi
	basesite=${site%%/*}
}

is_secret()
{
	[[ $1 =~ pass|key|cvc|secret|pin|code|token|otp && ! $1 =~ otp-issuer ]]
}

do_clip()
{
	local prop=$1
	if type copyq 1>/dev/null 2>&1 && is_secret "$prop"
	then
		copyq_monitoring=`copyq monitoring`
		if [ "$copyq_monitoring" = true ]
		then
			copyq disable
		fi
		copyq copy -
		if [ "$copyq_monitoring" = true ]
		then
			copyq enable
		fi
	else
		xclip -i -selection clipboard
	fi
}

get_totp_all()
{
	COTP_PASSWORD='' cotp |\
	jq -r '.[] | [.index, .issuer, .label, .otp_code] | join("\t")' |\
	td-add-headers INDEX ISSUER LABEL CODE
}

has_prop()
{
	local prop=$1
	shift
	[ -f "$basedir/$site/$prop" ]
}

prop()
{
	local prop=${1:?'enter property name!'}
	shift
	local instruct=${1:?enter an instruction: set, edit, read, del, show, reveal, clip}
	shift
	
	if [ "$prop" = TOTP ]
	then
		case "$instruct" in
		(set)
			touch "$basedir/$site/$prop"
			return
			;;
		(reveal)
			local td td2 label_prop
			declare -a otp_codes
			
			if has_prop OTP-ISSUER
			then
				td=`get_totp_all | td-filter ISSUER = "$(prop OTP-ISSUER show)"`
			else
				td=`get_totp_all | td-filter ISSUER = "$site" or ISSUER = "${site%%/*}"`
			fi
			
			otp_codes=($(echo "$td" | td-select -H CODE))
			if [ ${#otp_codes[@]} -gt 1 ]
			then
				for label_prop in EMAIL USERNAME LOGIN
				do
					if has_prop "$label_prop"
					then
						td2=`echo "$td" | td-filter LABEL = "$(prop "$label_prop" show)"`
						otp_codes=($(echo "$td2" | td-select -H CODE))
						if [ ${#otp_codes[@]} = 1 ]
						then
							td=$td2
							break
						fi
					fi
				done
			fi
			
			otp_codes=($(echo "$td" | td-select -H CODE))
			if [ ${#otp_codes[@]} -ne 1 ]
			then
				exit_with_msg 3 "Found ${#otp_codes[@]} TOTP codes."
			fi
			echo "${otp_codes[0]}"
			return
			;;
		(del|clip|show)
			true;;  # handled below by generic propery operations
		(*)	false;;  # invalid instruction given
		esac
	fi
	
	case "$instruct" in
	(set)
		[ $# -gt 0 ]  # 'prop ... set' needs at least 1 argument
		val=$*
		mkdir -p "$basedir/$site"
		printf '%s' "$val" > "$basedir/$site/$prop"
		;;
	(edit)
		mkdir -p "$basedir/$site"
		"${EDITOR:-$VISUAL}" "$basedir/$site/$prop"
		;;
	(read)
		if is_secret "$prop"
		then
			read -s -p "$site/$prop: " -e val
		else
			read -p "$site/$prop: " -e val
		fi
		mkdir -p "$basedir/$site"
		printf '%s' "$val" > "$basedir/$site/$prop"
		;;
	(del)
		rm "$basedir/$site/$prop"
		;;
	(show)
		if is_secret "$prop"
		then
			false  # this property is deemed to be a secret
		else
			prop "$prop" reveal "$@"
		fi
		;;
	(reveal)
		cat "$basedir/$site/$prop"
		;;
	(clip)
		prop "$prop" reveal "$@" | do_clip "$prop"
		;;
	(*)
		false  # invalid instruction given
		;;
	esac
}

dump()
{
	local site=$1
	shift
	declare -a options=("$@")
	declare -a files subfiles
	local path file basename propname hash subpathglob
	
	(
		shopt -s nullglob
		GLOBIGNORE=${GLOBIGNORE:-}${GLOBIGNORE:+:}".:..:.[!/.]*:*/.*:..[!/]*:-*:*/-*"
		path="$basedir/$site/"
		files=("$path"*)
		if in_list subdirs "${options[@]}"
		then
			subpathglob='*'
			while true
			do
				subfiles=("$path"$subpathglob/*)
				if [ ${#subfiles[@]} = 0 ]; then break; fi
				files+=("${subfiles[@]}")
				subpathglob=$subpathglob/*
			done
		fi
		
		for file in "${files[@]}"
		do
			if [ ! -f "$file" ]
			then
				continue
			fi
			basename=${file##*/}
			if in_list subdirs "${options[@]}"
			then
				propname=${file:${#path}}
			else
				propname=$basename
			fi
			
			if is_secret "$basename"
			then
				if in_list reveal-secrets "${options[@]}"
				then
					true
				elif in_list hash-secrets "${options[@]}"
				then
					hash=`cat "$file" | md5sum | cut -c 1-32`
					echo "$propname$TAB$hash$TAB""hash-algo=md5"
					continue
				elif in_list blank-secrets "${options[@]}"
				then
					echo "$propname$TAB"
					continue
				else
					echo "$propname$TAB*****"
					continue
				fi
			fi
			
			grep . "$file" | prefixlines "$propname$TAB" || true
		done
		
		if ! in_list subdirs "${options[@]}"
		then
			site=${site%/}
			if [[ $site =~ / ]]
			then
				parent=${site%/*}
				dump "$parent" "${options[@]}"
			fi
		fi
	)
}


basedir=~/cred
site=''
basesite=''
opt_quiet=''

while [ $# -gt 0 ]
do
	case "$1" in
	(--quiet)	opt_quiet=1;;
	(--)		shift; break;;
	(-*)		errx 1 "unknown option: $1";;
	(*)			break;;
	esac
	shift
done


if [ "${1:-}" = site ]
then
	shift || true
	set_site
fi

subcmd=${1:-}
shift || true



case "$subcmd" in
(dump)
	set_site
	if [ ! -e "$basedir/$site" ]
	then
		exit_with_msg 2 "no such site"
	fi
	
	dump "$site" "$@"
	;;
(list-sites)
	find -L "$basedir" -path "$basedir/${1:-}*" -type d -printf "%P\n"
	;;
(prop)
	set_site
	prop "$@"
	;;
(set|edit|read|del|show|reveal|clip)
	set_site
	prop=$1
	shift
	prop "$prop" "$subcmd" "$@"
	;;
(fill-form)
	set_site
	if [ $# -gt 0 ]
	then
		strings=''
		for prop in "$@"
		do
			if [ "$prop" = . ]
			then
				val=''
			else
				val=`prop "$prop" reveal`
			fi
			strings="$strings$val"$'\t'
		done
		xdotool key Alt+Tab
		# TODO verify if the new window is something we are supposed to type secrets
		sleep 1
		xdotool type --delay 100ms "$strings"
	else
		exit_with_msg 1 "Enter property names in order to fill the form on the window brought to focus by Alt+Tab."
	fi
	;;
(list-props)
	set_site
	if [ ! -e "$basedir/$site" ]
	then
		exit_with_msg 2 "no such site"
	fi
	find -L "$basedir/$site" -type f -printf "%P\n"
	;;
(generate-password)
	set_site
	newpwd=$(pwgen -y 8 1)$(pwgen -y 8 1)
	[ -n "$newpwd" ]
	pwdfile=$basedir/$site/PASSWORD
	mkdir -p "$basedir/$site"
	if [ -s "$pwdfile" ]
	then
		cur_pwd=`cat "$pwdfile"`
		atime=`stat -c %x "$pwdfile"`
		now=`date +'%F %T.%N %z'`
		echo "$atime	$now	$cur_pwd" >> "$basedir/$site/OLDPASSWORDS"
	fi
	printf '%s' "$newpwd" > "$pwdfile"
	printf '%s' "$newpwd" | do_clip PASSWORD
	;;
(compscript)
	cat <<'EOF'
_autocomplete_cred() {
	local compreply
	local curr_word=${COMP_WORDS[$COMP_CWORD]}
	local prev_word=${COMP_WORDS[$[COMP_CWORD - 1]]}
	# NOTE if change $prop_subcmds, align it with the switch case below!
	local prop_subcmds="set edit read del show reveal clip"
	local site_subcmds="list-sites dump generate-password list-props prop $prop_subcmds fill-form"
	
	case $COMP_CWORD in
	(1)
		compreply="compscript site $site_subcmds"
		;;
	(2)
		local site=$curr_word; site=${site/#'~/'/$HOME/}
		compreply=`cred list-sites "$site"`
		;;
	(*)
		local subcmd=${COMP_WORDS[1]}
		local site=${COMP_WORDS[2]}; site=${site/#'~/'/$HOME/}
		local cword_idx=$COMP_CWORD
		if [ "$subcmd" = site ]
		then
			if [ $COMP_CWORD = 3 ]
			then
				compreply="$site_subcmds"
			else
				subcmd=${COMP_WORDS[3]}
				let cword_idx-=1
			fi
		fi
		case "$subcmd" in
		(prop)
			case $cword_idx in
			(3)
				compreply=`cred --quiet list-props "$site"`
				;;
			(4)
				compreply=$prop_subcmds
				;;
			esac
			;;
		# NOTE: align with $prop_subcmds!
		(fill-form|set|edit|read|del|show|reveal|clip)
			compreply=`cred --quiet list-props "$site"`
			if [ "$subcmd" = set ]
			then
				common_properties="EMAIL USERNAME LOGIN PASSWORD PIN KEY TOKEN TOTP"
				compreply="$compreply $common_properties"
			fi
			;;
		(dump)
			case $cword_idx in
			(3)
				compreply="reveal-secrets mask-secrets hash-secrets blank-secrets subdirs"
				;;
			esac
		esac
		;;
	esac
	COMPREPLY=($(compgen -W "$compreply" -- "${COMP_WORDS[$COMP_CWORD]}"))
	return 0
}
complete -F _autocomplete_cred cred
# use this in your bash session by eg: eval "$(cred compscript)"
EOF
	;;
(*)
	exit_with_msg 1 'Use tab-completion! Example: eval "$(cred compscript)"'
	;;
esac

exit
}
