#!/bin/bash

true <<'EOF'
=pod

=head1 NAME

delfattr - Removes given attributes (xattr) from files

=head1 SYNOPSIS

delfattr -n I<NAME> [-n I<NAME> [..]] I<FILE> [I<FILE> [...]]

=head1 DESCRIPTION

Remove I<NAME> xattribute(s) from the given files.

=head1 SEE ALSO

setfattr(1)

=cut

EOF


set -e
set -o pipefail
set -u

attr_names=()
files=()

while [ $# -gt 0 ]
do
	case "$1" in
	(-n)
		shift
		attr_names+=("$1")
		;;
	(--)
		shift
		break
		;;
	(-*)
		echo "$0: unknown option: $1" >&2
		exit 1
		;;
	(*)
		files+=("$1")
		;;
	esac
	shift
done

files+=("$@")

for name in "${attr_names[@]}"
do
	setfattr -x "$name" "${files[@]}"
done
