#!/usr/bin/perl

use strict;
use warnings;
use Encode qw(decode encode);
use Data::Dumper;

binmode(STDIN,  ':raw');
binmode(STDOUT, ':raw');

my $MARKER = "\x{F8FF}";

while (my $line = <STDIN>) {
    my $text = decode('UTF-8', $line);  # always valid, by construction
    my $out  = '';

    while ($text =~ /^(.*?)$MARKER(L|[0-9a-fA-F]{2})/s)
    {
        $text = $';
        print encode('UTF-8', $1);
        my $tag = $2;
        if ($tag eq 'L')
        {
        	# restore literal marker
        	print encode('UTF-8', $MARKER);
        }
        else
        {
        	# restore original raw byte
            print chr(hex($tag));
        }
    }
    print encode('UTF-8', $text);
}
