#!/bin/bash

true <<'EOF'
=pod

=head1 NAME

dict-repl - Shell-like interface for dict(1).

=cut

EOF


if [ "$INSIDE_DICT_REPL" ]
then
	while read -p "dict> " -a words
	do
		dict "${words[@]}"
	done
else
	export INSIDE_DICT_REPL=1
	exec rlwrap -r dict-repl 
fi
