#!/bin/bash

true <<EOF
=pod

=head1 NAME

diu - Display Inode usage, similar to du(1) for space usage

=cut

EOF


shopt -s dotglob
shopt -s nullglob
CROSSDEV=allow

show_num_of_entries()
{
	local prefix name entries recursive_num pwd mynum parent_dev dev
	prefix=${1:+$1/}
	shift
	parent_dev=$1
	shift
	mynum=0
	
	for name in "$@"
	do
		if [ ! -L "$name" ]
		then
			if [ -d "$name" ]
			then
				if [ $CROSSDEV = deny ]
				then
					dev=`stat -c %D "$name"`
				fi
				if [ $CROSSDEV = allow -o -z "$parent_dev" -o "$dev" = "$parent_dev" ]
				then
					pwd=$PWD
					if cd -- "$name"
					then
						entries=(*)
						show_num_of_entries "$prefix$name" "$dev" "${entries[@]}"
						recursive_num=$[${#entries[@]} + $NUM]
						echo "$recursive_num	$prefix$name"
						mynum=$[$mynum + $recursive_num]
						cd "$pwd"
					fi
				fi
			elif [ ! -e "$name" ]
			then
				echo "$0: $name: not found" >&2
			fi
		fi
	done
	NUM=$mynum
}

while [ $# -gt 0 ]
do
	case "$1" in
	-h|--help)
		echo "$0: [options] [<directory> [...]]
options:
 -x, --one-file-system"
		exit 0
		;;
	-x|--one-file-system)
		CROSSDEV=deny
		;;
	--)
		shift
		break
		;;
	-*)
		echo "$0: unknown option: $1" >&2
		exit -1
		;;
	*)
		break
		;;
	esac
	shift
done

if [ $# = 0 ]
then
	set .
fi

show_num_of_entries '' '' "$@"
