#!/bin/bash

set -e
set -o pipefail

act=$1

if [ "$act" = get ]
then
	server_url=`cat`
	echo $server_url >&2
	if [[ $server_url =~ ://([^:/]+) ]] || [[ $server_url =~ ^([^:/]+)$ ]]
	then
		domain=${BASH_REMATCH[1]}
		username=`cred site "$domain" reveal USERNAME`
		if [ -z "$username" ]
		then
			echo "username not found for $domain" >&2
		fi
		password=`cred site "$domain" reveal PASSWORD`
		if [ -z "$password" ]
		then
			echo "password not found for $domain" >&2
		fi
		echo "{\"Username\":\"$username\",\"Secret\":\"$password\"}"
	else
		echo "bad server url: $server_url" >&2
	fi
fi
