#!/usr/bin/env perl

=pod

=head1 NAME

ffilt - Filter a file via a command's STDIO and write back to the file

=head1 SYNOPSIS

ffilt I<FILE> I<COMMAND> [I<ARGS>]

=head1 DESCRIPTION

Feed I<FILE> into I<COMMAND>'s stdin, then save its stdout back to I<FILE>
if I<COMMAND> ran successfully.

ffilt(1) is quasi a shorthand for this shell idiom:

 output=`cat FILE | COMMAND`
 [ $? = 0 ] && echo "$output" > FILE

=head1 LIMITATIONS

=head1 SEE ALSO

sponge(1), insitu(1) L<https://github.com/athas/insitu>

=cut


use open IN => ':raw :bytes', OUT => ':raw :bytes';
use Getopt::Long qw/:config no_ignore_case no_bundling no_getopt_compat no_auto_abbrev pass_through permute/;
use IPC::Run qw/run/;
use Pod::Usage;
use Data::Dumper;
use POSIX;
use Fcntl qw/:seek/;


GetOptions(
    'help' => sub { pod2usage(-exitval=>0, -verbose=>99); },
) or pod2usage(-exitval=>2, -verbose=>99);

# Getopt's pass_through mode leaves "--" there
shift @ARGV if $ARGV[0] eq '--';


sub cease
{
	my ($code, $msg) = @_;
	warn "$0: $msg\n";
	exit $code;
}


$File = shift @ARGV or pod2usage(-exitval=>2, -verbose=>99);
open $filehandle, '+<', $File or cease(int $!, "$File: open: $!");

$exit_status = 0;
run [@ARGV], '<', $filehandle, '>', \$stdout;
$run_status = $?;

if($run_status == 0)
{
	seek $filehandle, 0, SEEK_SET	or cease(int $!, "$File: seek: $!");
	print {$filehandle} $stdout		or cease(int $!, "$File: write: $!");
	seek $filehandle, 0, SEEK_CUR	or cease(int $!, "$File: seek: $!");
	truncate $filehandle, length $stdout	or cease(int $!, "$File: truncate: $!");
	close $filehandle				or cease(int $!, "$File: close: $!");
	$exit_status = 0;
}
else
{
	if(WIFSIGNALED($run_status))
	{
		my $sig = WTERMSIG($run_status);
		warn "$0: $ARGV[0]: command terminated by signal $sig\n";
		$exit_status = 128 + $sig;
	}
	else
	{
		my $code = WEXITSTATUS($run_status);
		warn "$0: $ARGV[0]: command exited with status $code\n";
		$exit_status = $code;
	}
	
}
exit $exit_status;

