#!/bin/bash

inode=$1

if [ "$inode" = 1 ]
then
	# it's a mountpoint.
	filename=$2
	path="$FZF_PREVIEW_DIRECTORY/$filename"
else
	# note, possibly this `find` does not yield the same file which given to us,
	# due to hardlinks, but generally it does not alter previewing much.
	path=`find "$FZF_PREVIEW_DIRECTORY" -maxdepth 1 -inum "$inode" -print -quit`
	
	# filename contains the "-> target" part if it's a symlink to "target"
	#filename=${filename%% -> *}
fi

mime=`file -bL --mime-type "$path"`


ornate_per_line()
{
	local ansi_codes=$1
	local ansi_reset=`tput sgr0`
	local line
	while read -r line
	do
		echo -n "$ansi_codes$line$ansi_reset"
		echo
	done
}

strip_ctrl_chars()
{
	sed -e 's/\[\x00-\x1F\x7F\]//g'
}

concat_major_minor()
{
	# concat char- and block-special file's major and minor device numbers
	# to unite their respective columns.
	# note, we keep all the spaces before the major and minor numbers,
	# although this is one space more than needed to pad off the previous column,
	# but other files (not char- or block-special ones) in the directory are
	# also padded to account the one extra space after the comma between the major
	# and the minor numbers.
	sed -e 's/^\([cb]\S\+\s\+\S\+\s\+\)\([0-9]\+\),\(\s\+\)\([0-9]\+\)/\1\3\2:\4/'
}

reorder_ls_columns()
{
	# remove permissions and n_links columns and
	# put date and time before size.
	sed -e "s/\(\S\+\s\+\S\+\)\(\s\+\S\+\)\s\+\(\S\+\s\+\S\+\)/\3\2/"
}


xattrs=`getfattr --physical --dump --encoding=text "$path" 2>/dev/null`
if [ -n "$xattrs" ]
then
	ansi_codes=`tput bold; tput setaf 5`
	echo "$xattrs" | ornate_per_line "$ansi_codes"
fi

acls=`getfacl --physical --omit-header --skip-base --absolute-names "$path" 2>/dev/null`
if [ -n "$acls" ]
then
	ansi_codes=`tput bold; tput setaf 3`
	echo "$acls" | ornate_per_line "$ansi_codes"
fi


case "$mime" in
application/pdf)
	pdftotext -layout "$path" -
	;;
application/*)
	echo $mime
	file -bL "$path"
	;;
image/*)
	;;
video/*)
	;;
audio/*)
	;;
message/rfc822)
	emlv "$path"
	;;
*)
	if [ -d "$path" ]
	then
		ls -lAhgo ${LS_SORT_FLAGS[$LS_SORT_ORDER]} --time-style=long-iso --indicator-style=slash --color=always "$path/" |\
		lines 2-EOF |\
		concat_major_minor |\
		reorder_ls_columns
	elif [ -c "$path" -o -p "$path" ]
	then
		file "$path"
	else
		head -n ${FZF_PREVIEW_LINES:--0} "$path" | strip_ctrl_chars
	fi
	;;
esac
