#!/bin/bash

true <<EOF
=pod

=head1 NAME

gitdiff - View two files' diff by git-diff(1), even not under git version control

=cut

EOF


declare -a args
for arg in "$@"
do
        if [ "${arg:0:1}" != - ]
        then
                arg=`readlink -nf "$arg"`
        fi
        args+=("$arg")
done
git diff --no-index "${args[@]}"
