#!/usr/bin/env python

"""
This gno2gron takes .GNO file (GenoPro) as argument and
outputs a gron(1) format text forto be able to parse and diff it better.
Replaces the lists to dicts by taking each element ID attribute as key.
"""

from __future__ import print_function
import os
import sys
import xmltodict
import json
import subprocess
import traceback


def force_list_decider(path, key, value):
	if len(path) == 2 and path[1][0].endswith('s'):
		return True

def getkey_default(item):
	return item['@ID']

def getkey_GenoMap(item):
	return item['@Name']

def getkey_PedigreeLink(item):
	return '.'.join([item['@Individual'], item['@Family'], item['@PedigreeLink']])

def getkey_SocialRelationship(item):
	return '.'.join([item['@Entity1'], item['@Entity2'], item['@Connection']])

class DuplicateKeyError(Exception):
	pass

def transform_list_to_dict(typ, lst):
	state = {}
	getkey_funcname = 'getkey_' + typ
	if getkey_funcname in globals():
		getkey = globals()[getkey_funcname]
	else:
		getkey = getkey_default
	state['getkey_method'] = getkey
	res = {}
	for idx, item in enumerate(lst):
		state['index'] = idx
		try:
			key = getkey(item)
			if key in res.keys():
				try:
					raise DuplicateKeyError(key)
				except DuplicateKeyError as ex:
					print("The following", ex.__class__.__name__, "is ignored. State:", state, file=sys.stderr)
					traceback.print_exc()
					print("Previous item:", res[key], file=sys.stderr)
					print("This item:", item, file=sys.stderr)
			res[key] = item
		except Exception as ex:
			ex.transform_list_to_dict_state = state
			raise
	return res

def transform_lists_to_dict_recursively(obj, path=()):
	for key, value in obj.items():
		if isinstance(value, list):
			try:
				obj[key] = transform_list_to_dict(key, value)
			except Exception as ex:
				print("Exception at path:", path, "key:", key, file=sys.stderr)
				if hasattr(ex, 'transform_list_to_dict_state'):
					print("transform_list_to_dict state:", ex.transform_list_to_dict_state, file=sys.stderr)
				raise
		elif isinstance(value, dict):
			transform_lists_to_dict_recursively(value, path+(key,))


xmldata = subprocess.check_output(['unzip', '-p', sys.argv[1], 'Data.xml'])
data = xmltodict.parse(xmldata, force_list=force_list_decider)

transform_lists_to_dict_recursively(data)

json2gron = subprocess.Popen(['json2gron'], stdin=subprocess.PIPE)
json.dump(data, json2gron.stdin, sort_keys=True)
json2gron.stdin.close()
json2gron.wait()
sys.exit(json2gron.returncode)

