#!/usr/bin/env perl

=pod

=head1 NAME

header - Echo the input stream up to the first empty line (usual end-of-header marker)

=head1 SYNOPSIS

header I<FILE> [I<FILE> [I<FILE> [...]]]

header < I<FILE>

=cut

if(not @ARGV)
{
	push @ARGV, '/dev/stdin';
}

for my $idx (0..$#ARGV)
{
	my $path = $ARGV[$idx];
	open my $fh, '<', $path;
	while(<$fh>)
	{
		last if /^\r?\n?$/;
		print;
	}
	if($idx < $#ARGV)
	{
		print "\n";
	}
}
