#!/usr/bin/env perl

=pod

=head1 NAME

hlcal [OPTIONS] [CAL-OPTIONS]

hlncal [OPTIONS] [NCAL-OPTIONS]

=cut


use Data::Dumper;
use Getopt::Long qw/:config no_ignore_case bundling no_getopt_compat pass_through/;
use feature qw/switch/;
use Pod::Usage;
use Carp qw/croak/;
use List::MoreUtils qw/all any none/;

use POSIX qw/strftime setlocale LC_TIME/;
use DateTime;
use DateTime::Duration;
use DateTime::Format::Strptime;
use DateTime::Locale;
use locale;


# take the basename of the command as procname.
$0 =~ s/.*\/([^\/]+)$/$1/;

use constant {
	VERTICAL => 'v',
	HORIZONTAL => 'h',
};

use constant {
	MON => 0,
	TUE => 1,
	WED => 2,
	THU => 3,
	FRI => 4,
	SAT => 5,
	SUN => 6,
};

my %Months = (
	jan=>1,
	feb=>2,
	mar=>3,
	apr=>4,
	may=>5,
	jun=>6,
	jul=>7,
	aug=>8,
	sep=>9,
	'oct'=>10,
	nov=>11,
	dec=>12,
);
my $re_months = join '|', keys %Months;


my %ANSIcolor = (
	black=>30, red=>31, green=>32, yellow=>33, blue=>34, magenta=>35, cyan=>36, white=>37,
);
my %ANSIcode = (
	'reset'=>0, bold=>1, faint=>2, italic=>3, underline=>4,
	blink_slow=>5, blink_rapid=>6, inverse=>7, conceal=>8, crossed=>9,
	normal=>22,
	noitalic=>23, nounderline=>24, noblink=>25, noinverse=>27, noconceal=>28, nocrossed=>29,
	%ANSIcolor,
	default=>39,
);
sub get_ansi_codes
{
	my $str = shift;
	my @codes = ();
	$str =~ s/[- ]bg/_bg/g;
	$str =~ s/bright[- ]/bright_/g;
	for my $word (split /[\s-]+/, $str)
	{
		my $code = 0;
		if($word =~ /^(?'BRIGHT'bright_|)(?'COLOR'.+?)(?'BG'_bg|)$/ and any {$_ eq $+{'COLOR'}} (keys %ANSIcolor))
		{
			$code += 10 if $+{'BG'};
			$code += 60 if $+{'BRIGHT'};
			$word = $+{'COLOR'};
		}
		if(exists $ANSIcode{$word}) { $code += $ANSIcode{$word}; }
		else { $code = ''; }
		push @codes, $code;
	}
	return @codes;
}
sub ansicode
{
	my @codes = grep {length} get_ansi_codes join " ", @_;
	return '' if not @codes;
	return sprintf "\x1B[%sm", join(';', @codes);
	#return join '', map { sprintf "\x1B[%sm", $_ } @codes;
}



$OptNoHighlightToday = 0;
# weeks starts on Sunday by default in cal
$week_start_on = SUN;
$calcmd = 'cal';
$calcmd = 'ncal' if $0 =~ /ncal/;


while(@ARGV)
{
	my $arg = shift @ARGV;
	
	# TODO: get highlight parameters from config files
	
	if(my ($date, $color) = $arg =~ /^(today|yesterday|tomorrow)=(.+)$/i)
	{
		$date = DateTime->now(time_zone=>'local')->strftime('%F') if $date eq 'today';
		$date = (DateTime->now(time_zone=>'local') - DateTime::Duration->new(days=>1))->strftime('%F') if $date eq 'yesterday';
		$date = (DateTime->now(time_zone=>'local') + DateTime::Duration->new(days=>1))->strftime('%F') if $date eq 'tomorrow';
		$arg = "$date=$color";
	}
	
	if(my ($day, $color) = $arg =~ /^(MON|TUE|WED|THU|FRI|SAT|SUN)=(.+)$/i)
	{
		$Highlight->{'days-of-week'}->{eval $day} = $color;
		warn "$0: no ANSI code: $color\n" unless all {length} get_ansi_codes $color;
	}
	elsif($arg =~ /^((?'YEAR'\d\d\d\d)-|)((?'MON'\d\d?|$re_months)-|)(?'DOM'\d{1,2})=(?'COLOR'.+)$/i)
	{
		my $year = $+{'YEAR'} || 'ALL';
		my $mon = $+{'MON'} || 'ALL';
		my $dom = $+{'DOM'};
		my $color = $+{'COLOR'};
		$mon = $Months{$mon} if exists $Months{$mon};
		$Highlight->{'date'}->{$year}->{$mon}->{$dom} = $color;
	}
	else
	{
		# unknown parameter.
		# give it back to cal/ncal.
		unshift @ARGV, $arg;
		last;
	}
}

#warn Dumper $Highlight;


@cal_args = @ARGV;

GetOptions(
	'M' => sub { $week_start_on = MON; },
	'S' => sub { $week_start_on = SUN; },
	'C' => sub { $calcmd = 'cal'; },
	'N' => sub { $calcmd = 'ncal'; },
	'b' => sub { $layout = HORIZONTAL; },
	'h' => \$OptNoHighlightToday,  # TODO
	'help|?' => sub {
		pod2usage(-exitval=>'NOEXIT', -verbose=>99);
		system("sh", "-c", "cal --help 2>&1");
		exit 0;
	},
) or pod2usage(-exitval=>2, -verbose=>99);


if(not defined $layout)
{
	$layout = HORIZONTAL;
	$layout = VERTICAL if $calcmd eq 'ncal';
}


my $month_parser = new DateTime::Format::Strptime(pattern=>'%Y %b', on_error=>'croak', locale=>setlocale(LC_TIME));



# prevent cal to highlight today. we will do it.
unshift @cal_args, "-h";


open my $pipe, '-|:utf8', $calcmd, @cal_args or croak "$0: popen: $calcmd: $!";
binmode STDOUT, ':utf8';

$title_passed = 0;

while(<$pipe>)
{
	my $is_week_row = 0;
	
	if(/(\d\d\d\d)/)
	{
		$year = $1;
	}
	
	my @words = /([^\d\s]+)/g;
	if(scalar @words >= 1 and scalar @words <= 3 and (not /\d/ or /\d\d\d\d/))
	{
		# seems to be 1, 2, or 3 month names
		@month_column = ();
		for my $word (@words)
		{
			push @month_column, int $month_parser->parse_datetime("$year $word")->strftime('%m');
		}
	}
	
	my @years = /(\d\d\d\d)/g;
	if(@years)
	{
		@year_column = @years;
	}
	
	if(/([^\d\s]+\s+){7}/)
	{
		# at least 7 groups of letters (not space or digit),
		# it's probably day of week names;
		# assuming horizontal layout.
		
		# TODO: any locale setting in which month names have space?
		
		$layout = HORIZONTAL;
		$title_passed = 1;
		$week_of_month = 0;
		$is_week_row = 1;
		
		%dow_bgn = ();
		%dow_end = ();
		my $day_spacing = 1;
		for my $dow ($week_start_on, MON..SUN)
		{
			my $repeats = ($dow - $week_start_on) % 7 + 1;
			/^(\s*[^\d\s]+){$repeats}/;
			$dow_end{$dow} = length $&;
			$dow_bgn{$dow} = $dow eq $week_start_on ? 0 : $dow_end{($dow-1)%7} + $day_spacing;
		}
	}
	
	if($layout eq HORIZONTAL)
	{
		if(/\d/ and $title_passed)
		{
			# at least 1 number -> a row of a week
			$week_of_month++;
			$is_week_row = 1;
		}
		
		if($is_week_row)
		{
			my $month_spacing = 2;
			my $where_last_dow_column_ends = $dow_end{($week_start_on-1)%7};
			my $how_many_month_columns = int(length($_) / $where_last_dow_column_ends);
			my $accum_shift = 0;
			
			for my $month_column (0..$how_many_month_columns-1)
			{
				my $week_start_offset = $month_column * ($where_last_dow_column_ends + $month_spacing);
				
				my %hldow = map {$_=>$Highlight->{'days-of-week'}->{$_}} keys $Highlight->{'days-of-week'};
				my $cur_year = $year_column[$month_column] || $year;
				my $cur_month = $month_column[$month_column];
				my %dates = ();
				$dates{$d} = $c while ($d, $c) = each %{$Highlight->{'date'}->{'ALL'}->{'ALL'}};
				$dates{$d} = $c while ($d, $c) = each %{$Highlight->{'date'}->{'ALL'}->{$cur_month}};
				$dates{$d} = $c while ($d, $c) = each %{$Highlight->{'date'}->{$cur_year}->{$cur_month}};
				for my $date (keys %dates)
				{
					my $dow = int strftime('%u', 0, 0, 0, $date, $cur_month-1, $cur_year-1900) - 1;
					my $date_at_dow_location = substr($_, $dow_bgn{$dow} + $week_start_offset + $accum_shift, $dow_end{$dow}-$dow_bgn{$dow});
					$hldow{$dow} .= " " . $dates{$date} if $date == $date_at_dow_location;
				}
				
				for my $dow ( $week_start_on .. SUN, MON .. ($week_start_on-1) )
				{
					if(exists $hldow{$dow})
					{
						my $color = $hldow{$dow};
						my $insert1 = ansicode($color);
						my $insert2 = ansicode('reset');
						my $bgn = $dow_bgn{$dow} + $week_start_offset + $accum_shift;
						my $end = $dow_end{$dow} + $week_start_offset + $accum_shift;
						
						$_ = substr($_, 0, $bgn) . $insert1 . substr($_, $bgn, $end-$bgn) . $insert2 . substr($_, $end);
						$accum_shift += length($insert1) + length($insert2);
					}
				}
				
			}
		}
	}
	else  # $layout eq VERTICAL
	{
		if(not /\b\d\d?\b/)
		{
			# no 1 or 2 digit numbers, assuming month name(s) header.
			# TODO: any locale setting in which month names have numbers?
			
			$day_of_week = $week_start_on - 1;
			$is_date_row = 0;
		}
		
		if(/(\d+\s+){4}/)
		{
			# at least 4 numbers -> it's a new row of days
			$day_of_week = ($day_of_week + 1) % 7;
			$is_date_row = 1;
		}
		
		if($is_date_row)
		{
			# TODO: hilight dates
			
			while (my ($hldow, $color) = each $Highlight->{'days-of-week'})
			{
				if($day_of_week == $hldow)
				{
					s/^/ansicode($color)/e;
					s/$/ansicode('reset')/e;
				}
			}
		}
	}
	
	print;
}

close $pipe;
