#!/usr/bin/env python

"""
=pod

=head1 NAME

json2bencode - Convert JSON to Bencode (BitTorrent's loosely structured data)

=cut

"""

import sys
import json
import bencode

json.stdout.write(bencode.bencode(json.load(sys.stdin)))
