#!/bin/bash

true <<EOF
=pod

=head1 NAME

loggerexec - Run a command and send STDOUT and STDERR to syslog

=head1 SYNOPSIS

loggerexec [-s] I<FACILITY> I<IDENT> I<COMMAND> [I<ARGS>]

Send I<COMMAND>'s stdout and stderr to syslog.
I<FACILITY> is one of standard syslog facility names (user, mail, daemon, auth, local0, ...).
I<IDENT> is a freely choosen identity name, also known as tag or programname.
I<COMMAND>'s stdout goes as B<info> log level, stderr goes as B<error> log level.
Option C<-s> puts the output on stdout/stderr too.

=head1 SEE ALSO

logger(1), stdsyslog(1)

=cut

EOF


if [ ".$1" = ".--help" ]
then
	pod2text "$0"
	exit
fi

passthrough=''

if [ "$1" = -s ]
then
	passthrough=1
	shift
fi

set -e
set -o pipefail
set -u

facility=$1
shift
ident=$1
shift

exec "$@" > >(exec {fd}>&1; exec tee ${passthrough:+/dev/fd/$fd} | exec logger -p "$facility.info" -t "$ident" 2>&1) 2> >(exec tee ${passthrough:+/dev/stderr} | logger -p "$facility.error" -t "$ident")
