#!/usr/bin/env perl

#use Data::Dumper;

while(<STDIN>)
{
	chomp;
	
	while(
	 /\s*,?\s*[^,]*?<([^\s\@""''<>,]+@[^\s\@""''<>,]+)>/m or
	 /\s*,?\s*[^,]*?([^\s\@""''<>,]+@[^\s\@""''<>,]+)/m or
	 /\s*,?\s*[""].*?[""]\s*<([^\s\@""''<>,]+@[^\s\@""''<>,]+)>/m or
	 /\s*,?\s*[''].*?['']\s*<([^\s\@""''<>,]+@[^\s\@""''<>,]+)>/m
	)
	{
		#print STDERR Dumper {"before"=>$`,"match"=>$&,"address"=>$1,"after"=>$'};
		print "$1\n";
		$_ = $';
	}
}
