TOOLS ?= \
  2opml \
  a8e \
  adr2html \
  args2env \
  args2stdin \
  asterisk-log-separator \
  autosshfs-mount \
  awk-cut \
  base58 \
  base64url \
  bencode2json \
  body \
  cdexec \
  chattr-cow \
  chattr-nocow \
  chromium_cookie_decrypt.py \
  chshebang \
  cled \
  cred \
  confpatch \
  convert_chromium_cookies_to_netscape.sh \
  corner_time \
  cpyfattr \
  cronrun \
  cut.awk \
  daemonctl \
  dataurl2bin \
  dbus-call \
  debdiff \
  delfattr \
  descpids \
  dfbar \
  digasn \
  diu \
  dlnew \
  dnsmasq-dbus-nameservers \
  docker-credential-cred \
  dump_php_session.php \
  eat \
  errorlevel \
  error_reporting.php \
  evhand \
  fcomplete \
  fc-search-codepoint \
  fdupes-hardlink \
  ff \
  ffilt \
  fgat \
  filesets \
  filterexec \
  find-by-date \
  findnewestfile \
  findoldestfile \
  fixlogfiledatetime \
  fixRFC822filemtime \
  fmtkv \
  foreach \
  fzf-preview \
  g_filename_to_uri \
  getcvt \
  git-checkout-sparse \
  git-mirrors \
  gitconfigexec \
  git_diff \
  git-submodule-auto-add \
  git-push-remotes \
  glob \
  grepdatetime \
  Head \
  header \
  hlcal \
  hlncal \
  htmlentities \
  indent2tree \
  indent2graph \
  inisort \
  is_gzip \
  jaro-metric \
  jaro-winkler-metric \
  jobsel \
  json-merge-objects \
  json-sort \
  json2bencode \
  json2msgpack \
  killcmd \
  killexe \
  killp \
  killpgrp \
  kt \
  LevelDB \
  levenshtein-distance \
  lines \
  lnto \
  locale-validator \
  loggerexec \
  logrotate-counters \
  logto \
  lpjobs \
  lpset \
  ls2html \
  lsata \
  lsenv \
  lynx-render \
  mail-extract-addresses \
  mail-extract-raw-headers \
  maskfiles \
  mdstat \
  metalink-sync-list \
  mime_extract \
  mime-header-decode \
  mkdeb \
  mkmagnetlink \
  movesymlinks \
  moz_bookmarks \
  msg \
  msgpack2json \
  multicmd \
  multithrottler \
  mysql-fix-orphan-privileges.php \
  netrc \
  nncp-send-dir \
  noacute \
  nocomment \
  notashell \
  nthash.py \
  ocspverify \
  oded \
  organizebydate \
  palemoon-current-url \
  pararun \
  parsel \
  partial \
  pathmod \
  paths2indent \
  pcut \
  perlprintf \
  perl-repl \
  pfx2pem \
  pipecmd \
  pipekill \
  PMbwmon \
  PMdirindex \
  PMhexdiff \
  PMnslist \
  PMpwgen \
  PMrecdiff \
  PMwrite \
  pngmetatext \
  prefixlines \
  pvalve \
  pyzor-files \
  qrwifi \
  query-alternatives \
  randstr \
  rcmod \
  rdfindreport \
  recent-files-gtk \
  redirexec \
  regargwrap \
  renamemanual \
  rename.td \
  repeat \
  replcmd \
  reportcmdstatus \
  rn \
  rr \
  rsacrypt \
  rsync-semichroot \
  rsysrq \
  screenconsole \
  screendetach \
  screen-notify \
  screenreattach \
  screens \
  seekstdin \
  set-sys-path \
  set-xcursor-lock-and-run \
  singleinstance \
  sockio \
  spoolprocess \
  ssh-agent-finder \
  stdfilt \
  stdmux \
  straceall \
  strip-ansi-seq \
  substenv \
  subst_sudo_user \
  swap \
  symlinks2dot \
  symlinks-analyze \
  tabularize \
  Tail \
  takeown \
  taslis \
  terminaltitle \
  tests \
  text2img-dataurl \
  timestamper \
  touchx \
  trackrun \
  triggerexec \
  ttinput \
  uchmod \
  unicodestyle \
  uniproc \
  untabularize \
  upsidedown \
  url_decode \
  url_encode \
  url_encode_bf \
  url-parts \
  verscmp \
  vidir-sanitize \
  vifiles \
  visymlinks \
  w3m-render \
  waitpid \
  wget-mirror \
  whisper-retention-info \
  wikibot \
  withpidfile \
  xdg-autostart \
  xml2json \

