#!/usr/bin/env python

"""
=pod

=head1 NAME

noacute - Strip diacritics (acute, umlaut, ...) from letters on the input stream

=cut

"""


import sys
import unicodedata

while True:
	line = sys.stdin.readline()
	if line == '':
		break
	line = line.decode('utf-8')
	print unicodedata.normalize('NFKD', line).encode('ASCII', 'ignore'),
