#!/bin/bash

true <<EOF

=pod

=head1 NAME

nocomment - remove comment lines from input stream

=head1 SYNOPSIS

nocomment [B<grep-arguments>]

=head1 DESCRIPTION

This command does not overwrite nor write files, just prints them without comments. 
I.e. removing lines starting hashmark or semicolon.

=head1 SEE ALSO

grep(1)

=cut

EOF

grep -Ev '^[[:space:]]*(#|;|//|$)' "$@"
