#!/usr/bin/env perl

$CustomShellPath = "/etc/notashell/customshell";

if(not $ENV{'NOTASHELL_INTERCEPT'})
{
	my $basename = $0 =~ s/.*\/([^\/]+)$/$1/r;
	$progname = $basename;
	exec {"/var/lib/notashell/real-" . $basename} $0, @ARGV;
}
else
{
	if(scalar @ARGV != 2 or $ARGV[0] != '-c')
	{
		die "notashell: Supposed to be called as 'notashell -c CommandString'\n";
	}
	
	$CommandString = $ARGV[1];
	$ENV{'NOTASHELL_INTERCEPT'} = 0;
	$ENV{'NOTASHELL_ORIGINAL_COMMAND'} = $CommandString;
	
	if(-x $CustomShellPath)
	{
		exec {$CustomShellPath} @cmd_args;
	}
	else
	{
		@cmd_args = split / /, $CommandString;
		$progname = $cmd_args[0];
		exec {$cmd_args[0]} @cmd_args;
	}
}

($errno, $errstr) = (int $!, $!);
warn "$progname: $errstr\n";
exit 125+$errno;
