#!/usr/bin/env perl

=pod

=head1 NAME

organizebydate-conflict-resolve-filename-version - Filename conflict resolver script for organizebydate(1)

=head1 SYNOPSIS

organizebydate-conflict-resolve-filename-version [I<OPTIONS>] I<SOURCE> I<TARGET>

=head1 DESCRIPTION

This is a helper programm used by organizebydate(1) as a filename conflict resolver command.
It signals that the I<SOURCE> is already equivalent to the I<TARGET> if their SHA-256 checksums match.
If not, then sets a new target file name for organizebydate(1).

The new target includes a version number in between the file's basename and extension,
taking into account any already existing versioned file names, so no files gonna be overwritten
(unless there is a race condition with other processes writing to the target directory).

Compare I<SOURCE> to all existing versions of the I<TARGET> file, not just the base version.
Versions are detected by increasing the version number integer
and stop at the first non-existing file.
So "gaps" in version numbers are not supported.


=head1 OPTIONS

=over 4

=item -s I<STR>

Set I<STR> as the string separating the filename (basename) from the version number.
Default is dot: C<.>.

=item -t I<STR>

Set I<STR> as the string separating the version number from the filename suffix (extension).
Default is empty, so the version number is followed by the dot directly which is the part of the suffix,
if there is an extension.

=item --checksum-db I<FILE>

Read and record file checksums from and to.
So no need to recompute for the same file path.

=back

=head1 EXAMPLES

 organizebydate-conflict-resolve-filename-version -s '(v' -t ')' ...

=head1 SEE ALSO

organizebydate(1)

=cut

use Data::Dumper;
use Digest::CRC;
use Getopt::Long qw/:config no_ignore_case bundling no_getopt_compat no_auto_abbrev require_order/;
use Pod::Usage;
use File::stat;
use DBI;

$msg_prefix = "filename conflict resolver: ";
$version_sep1 = '.';
$version_sep2 = '';
$checksum_db = undef;
$db_conn = undef;

GetOptions(
	's=s' => \$version_sep1,
	't=s' => \$version_sep2,
	'checksum-db=s' => \$checksum_db,
	'help' => sub { pod2usage(-exitval=>0, -verbose=>99); },
) or pod2usage(-exitval=>2, -verbose=>99);

pod2usage(-exitval=>2, -verbose=>99) unless scalar @ARGV == 2;


$Source = $ARGV[0];
$Target = $ARGV[1];


sub connect_db
{
	if(not defined $db_conn)
	{
		$db_conn = DBI->connect("dbi:SQLite:dbname=$checksum_db", undef, undef, {AutoCommit=>1, PrintError=>1, PrintWarn=>1, RaiseError=>1});
	}
	$db_conn->do("CREATE TABLE IF NOT EXISTS checksum (path TEXT PRIMARY KEY, crc TEXT NOT NULL) WITHOUT ROWID");
}

sub checksum_file
{
	my ($path, %opt) = @_;

	if($opt{'lookup_db'} and defined $checksum_db)
	{
		connect_db();
		my ($hexdigst) = $db_conn->fetchrow_arrayref("SELECT crc FROM checksum WHERE path = ?", undef, $path);
		return $hexdigst;
	}

	my $digest = Digest::CRC->new('crc64');
	open my $fh, '<', $path;
	$digest->addfile($fh);
	close $fh;
	my $hexdigst = $digest->hexdigest;

	if($opt{'write_db'} and defined $checksum_db)
	{
		connect_db();
		$db_conn->do("INSERT OR REPLACE INTO checksum (crc, path) VALUES (?, ?)", undef, $hexdigst, $path);
	}
	return $hexdigst;
}

sub same_as_source_file
{
	my ($file2) = @_;

	my $size1 = $ENV{'SOURCE_FILE_SIZE'};
	my $size2 = (stat $file2)->size;
	
	if($size1 eq $size2)
	{
		warn "${msg_prefix}sizes match, comparing checksums...\n";
		if(not defined $cksum_source)
		{
			$cksum_source = checksum_file($Source);
		}
		if($cksum_source eq checksum_file($file2, lookup_db=>1, write_db=>1))
		{
			warn "${msg_prefix}checksums match exactly.\n";
			return 1;
		}
		else
		{
			warn "${msg_prefix}checksums differ.\n";
		}
	}
	else
	{
		warn "${msg_prefix}sizes differ.\n";
	}
	return 0;
}

sub increase_version_number
{
	# insert the version number in the file name right before the extension.

	my ($filename) = @_;
	my ($prefix, $suffix, $version);

	my ($target_dir, $target_file) = $filename =~ /^(.*?)([^\/]+)$/;
	# keep the last dot-delimited substring as filename extension:
	if($target_file =~ /^(.+?)(\.[^\.]+)$/)
	{
		$prefix = $1;
		$suffix = $2;
	}
	else
	{
		$prefix = $target_file;
		$suffix = '';
	}
	$version = 2;

	# notice if the filename already has a version number:
	if($prefix =~ /\Q$version_sep1\E(\d+)\Q$version_sep2\E$/)
	{
		$version = $1 + 1;
		$prefix = $`;
	}

	return $target_dir . $prefix . $version_sep1 . $version . $version_sep2 . $suffix;
}

warn "${msg_prefix}source: $Source\n";
$proposed_target = $Target;

if($ENV{'SOURCE_FILE_SIZE'} !~ /^\d+$/)
{
	$ENV{'SOURCE_FILE_SIZE'} = (stat $Source)->size;
}

while(-e $proposed_target or -l $proposed_target)
{
	warn "${msg_prefix}target: $proposed_target\n";

	if(same_as_source_file($proposed_target))
	{
		print "done\n";
		exit 0;
	}

	$proposed_target = increase_version_number($proposed_target);
}


warn "${msg_prefix}new target: $proposed_target\n";
print "proceed $new_target\n";
exit 0;
