#!/bin/bash

true <<EOF
=pod

=head1 NAME

palemoon-current-url - Display the webpage's URL which is currently open in Palemoon web browser

=cut

EOF


set -e -o pipefail -u

sessionstore=`cat "$HOME/.moonchild productions/pale moon"/*.default/sessionstore.js`
selectedWindow=`echo "$sessionstore" | jq -r ".selectedWindow"`
selectedTab=`echo "$sessionstore" | jq -r ".windows[$((selectedWindow - 1))].selected"`
url=`echo "$sessionstore" | jq -r ".windows[$((selectedWindow - 1))].tabs[$((selectedTab - 1))].entries[0].url"`

echo "$url"
