#!/usr/bin/env perl

use Data::Dumper;
use IPC::Run qw(run harness);
use Getopt::Long qw/:config no_ignore_case no_bundling no_getopt_compat no_auto_abbrev require_order/;
use Pod::Usage;
use POSIX qw/:sys_wait_h/;

my $OptSeparator = '--';
my $OptPipefail = 0;

GetOptions(
	'p|pipe|pipechar=s' => \$OptSeparator,
	'f|pipefail!' => \$OptPipefail,
	'help' => sub { pod2usage(-exitval=>0, -verbose=>99); },
) or pod2usage(-exitval=>2, -verbose=>99);

@cmd1 = ();
@cmd2 = ();

while (@ARGV)
{
	my $arg = shift @ARGV;
	if ($arg eq $OptSeparator) {
		last;
	}
	push @cmd1, $arg;
}
@cmd2 = @ARGV;

unless (@cmd1 and @cmd2)
{
	pod2usage(
		-message => "Two commands are required.",
		-exitval => 2,
	);
}

sub derive_exit_code
{
	my $status = shift;
	return 128 + WTERMSIG($status) if WIFSIGNALED($status);
	return WEXITSTATUS($status);
}

$ipc = harness \@cmd1, '|', \@cmd2;
$ipc->run;
@results = $ipc->full_results;
$exit_code = derive_exit_code($results[1]);

if ($OptPipefail)
{
	for my $exit_status (@results) {
		my $this_exit_code = derive_exit_code($exit_status);
		$exit_code = $this_exit_code if $this_exit_code > $exit_code;
	}
}

exit $exit_code;


=pod

=head1 NAME

pipecmd - Run a command and pipe its output to an other one

=head1 SYNOPSIS

pipecmd [I<OPTIONS>] I<CMD_1> [I<ARGS>] -- I<CMD_2> [I<ARGS>]

=head1 DESCRIPTION

Equivalent to this shell command:

 CMD_1 | CMD_2

The first command's (I<CMD_1>) arguments can not contain a double-dash (C<-->),
because it's the command separator for pipecmd(1), unless redefined by B<--pipechar> option.
However, since only a total of 2 commands are supported,
arguments for I<CMD_2> may contain double-dash(es).

You can chain pipecmd(1) commands together to get a pipeline equivalent to
C<CMD_1 | CMD_2 | CMD_3>, like:

 pipecmd CMD_1 -- pipecmd CMD_2 -- CMD_3

=head1 OPTIONS

=over 4

=item -p, --pipechar, --pipe I<STRING>

Use I<STRING> as the command separator.
Default is double dash (C<-->).

=item -f, --pipefail

Exit with the highest exit code of the commands in the pipeline (or zero if all commands exit successfully).
The default is to exit with the latest command's exit code.

=back

=head1 EXIT STATUS

The latest command's exit code, unless B<--pipefail> is specified.

=head1 RATIONALE

It's sometimes more convenient to don't involve shell command-line parser.

=head1 SEE ALSO

pipexec(1)

=cut
