#!/bin/bash

true <<EOF
=pod

=head1 NAME

PMdirindex - Poor man's directory index generator, output HTML

=cut

EOF

switch=''
total=0
self=`basename "$0"`
output=./index.html


human_number() {
	n=$1
	m=''
	i=${#n}
	while [ $i -gt 0 ]
	do
		let i--
		[ $[(${#n}-$i)%3] == 1 ] && s=" " || s=''
		m="${n:$i:1}$s$m"
	done
	m=${m:0:$[${#m}-1]}
	echo -n "$m"
}


while [ -n "$1" ]
do
	if [ .${1:0:1} = .- ] && expr "${1:1}" : "[AasrctuvU]\+\$" >/dev/null
	then
		switch="$switch $1"
	else
		echo "$self: ignored: $1" >&2
	fi
	shift
done

if [ -t 1 ]
then
    if [ ! -f "$output" ]
    then
	echo "$self: output: $output" >&2
	exec > "$output"
    else
    	echo "$self: $output: already exists." >&2
    	exit 1
    fi
fi


echo "<pre class='poorMansDirecoryIndex'>"
echo "date time                 size           name"
echo "------------------------- -------------- --------------"

ls -1 --group-directories-first ${switch:--At} | {
	while read file
	do
		time=$(date +'%Y-%m-%d %H:%M:%S %z' -d@$(stat -c %Y "$file"))
		size=$(stat -c %s "$file")
		sz=`human_number $size`
		type=''
		if   [ -d "$file" ]; then type=/; size=''
		elif [ -L "$file" ]; then type=@
		elif [ -x "$file" ]; then type=*
		fi
		total=$(( total+size ))

		printf "%s %14s <a href='%s'>%s</a>%s\n" "$time" "$sz" "$file" "$file" "$type"
	done

	echo "------------------------- -------------- --------------"
	printf "%40s\n" "`human_number $total`"
}

echo "</pre>"
