#!/bin/bash

true <<EOF
=pod

=head1 NAME

pyzor-files - Run a pyzor(1) command on the given files

=cut

EOF


if [ $# = 0 ]
then
	echo "Usage: pyzor-files [<action>] -- <file-1> [<file-2> [<file-n> ...]]"
	echo "Note that 'check' action returns the last checked file's status only."
	exit -1
fi

args=()

while [ $# -gt 0 ]
do
	if [ ".$1" = .-- ]
	then
		shift
		break
	else
		args+=("$1")
	fi
	shift
done

for file in "$@"
do
	pyzor "${args[@]}" < "$file"
done
