#!/bin/bash

true <<EOF
=pod

=head1 NAME

qrwifi - Generate a string, used in WiFi-setup QR codes, containing a hotspot name and password

=cut

EOF


set -e
set -u

if [ $# -lt 2 ]
then
	echo "Usage: $0 [<SSID>] [<PSK>]" >&2
	false
fi

is_hidden=false

echo -n "WIFI:T:WPA;S:${1?enter SSID argument};P:${2?enter PSK argument};H:$is_hidden;"
