#!/bin/bash

true <<EOF
=pod

=head1 NAME

renamemanual - Interactive file rename tool

=head1 SYNOPSIS

renamemanual I<FILE> [I<FILE> [...]]

=head1 DESCRIPTION

Prompt for the user for new names for the files given in arguments.
Won't overwrite existing files,
rather keep asking the new name until it can be renamed to (without overwriting an existing file).
Skip a file by entering empty name.

=head1 SEE ALSO

mv(1), rename(1), file-rename(1p) (prename(1)), rename.ul (rename(1)), rename.td(1)

=cut

EOF

if [ $# = 0 ]
then
	pod2text "$0" >&2
	exit -1
fi
if [ "$1" = --help ]
then
	pod2text "$0"
	exit 0
fi

for file in "$@"
do
	while true
	do
		read -e -i "$file" -p "old: $file"$'\n'"new: " newname
		if [ "$newname" != "$file" -a -n "$newname" ]
		then
			if mv -i -v "$file" "$newname"
			then
				break
			fi
		else
			break
		fi
		echo
	done
done
