#!/bin/bash

true <<EOF
=pod

=head1 NAME

renamemanual - Interactive file rename tool

=cut

EOF

usage()
{
	echo "Usage: $0 <FILE> [<FILE> [...]]"
}

if [ $# = 0 ]
then
	usage >&2
	exit -1
fi
if [ "$1" = --help ]
then
	usage
	exit 0
fi

for file in "$@"
do
	while true
	do
		read -e -i "$file" -p "old: $file"$'\n'"new: " newname
		if [ "$newname" != "$file" -a -n "$newname" ]
		then
			if mv -i -v "$file" "$newname"
			then
				break
			fi
		else
			break
		fi
		echo
	done
done
