#!/bin/bash

true <<EOF
=pod

=head1 NAME

renamemanual - Interactive file rename tool

=cut

EOF


if [ -z "$1" ] || [ ."$1" = .--help ]
then
	echo "Usage: $0 [files...]" >&2
	exit 1
fi

for file in "$@"
do
	while true
	do
		read -e -i "$file" -p "old: $file"$'\n'"new: "
		if [ "$REPLY" != "$file" -a -n "$REPLY" ]
		then
			if mv -i -v "$file" "$REPLY"
			then
				break
			fi
		else
			break
		fi
		echo
	done
done
