#!/bin/bash

true <<EOF
=pod

=head1 NAME

repeat - Run a give command repeatedly

=head1 SYNOPSIS

repeat <COMMAND> [<ARGS>]

=head1 ENVIRONMENT

=over 4

=item REPEAT_TIMES

How many times to repeat the given command.
Default is infinite.

=item REPEAT_COUNT

How many time the command has been ran.
The command itself can access this variable to read.

=item REPEAT_DELAY

Sleep interval between invocations.
In seconds, by default.
See sleep(1) for valid parameters.

=back

=cut

EOF


. /usr/lib/tool/bash-utils

if [ "$1" = --help -o $# = 0 ]
then
	echo "Usage: [REPEAT_TIMES=num] [REPEAT_DELAY=interval] repeat <COMMAND> [<ARGS>]"
	exit 0
fi

REPEAT_TIMES=${REPEAT_TIMES:--1}
export REPEAT_COUNT
REPEAT_COUNT=0

while [ $REPEAT_TIMES = -1 -o $REPEAT_COUNT -lt $REPEAT_TIMES ]
do
	"$@"
	REPEAT_COUNT=$[REPEAT_COUNT + 1]
	sleep ${REPEAT_DELAY:-0}
done
