#!/bin/bash

true <<EOF
=pod

=head1 NAME

repeat - Run a give command repeatedly

=head1 SYNOPSIS

repeat I<COMMAND> [I<ARGS>]

=head1 ENVIRONMENT

=over 4

=item REPEAT_TIMES

How many times to repeat the given command.
Default is -1 which means infinite.

=item REPEAT_COUNT

How many times the command has been ran.
It is not a variable repeat(1) itself takes as input,
but passes to I<COMMAND> for its information.

=item REPEAT_UNTIL

Stop repeat(1) if I<COMMAND> exists with this return code.
By default the return code is not checked.

=item REPEAT_DELAY

Sleep interval between invocations.
In seconds, by default.
See sleep(1) for valid parameters, eg. "10m" for 10 minutes.
Default is no delay.

=back

=cut

EOF


. /usr/lib/tool/bash-utils

if [ "$1" = --help -o $# = 0 ]
then
	echo "Usage: [REPEAT_TIMES=num] [REPEAT_DELAY=interval] [REPEAT_UNTIL=code] repeat <COMMAND> [<ARGS>]"
	exit 0
fi

REPEAT_TIMES=${REPEAT_TIMES:--1}
export REPEAT_COUNT
REPEAT_COUNT=0

while [ $REPEAT_TIMES = -1 -o $REPEAT_COUNT -lt $REPEAT_TIMES ]
do
	"$@"
	if [ $? = "$REPEAT_UNTIL" ]
	then
		break
	fi
	REPEAT_COUNT=$[REPEAT_COUNT + 1]
	sleep ${REPEAT_DELAY:-0}
done
