#!/bin/bash

true <<'EOF'
=pod

=head1 NAME

replcmd - Wrap any command in a REPL interface

=head1 SYNOPSIS

replcmd I<COMMAND> [I<ARGS>]

=head1 DESCRIPTION

Run I<COMMAND> repeatedly with words read from STDIN appended to its argument list after I<ARGS>.
You may add prompt, history, and other CLI-goodies on top of replcmd(1) by eg. rlwrap(1).

=head1 EXAMPLE

rlwrap --remember --command-name dict --substitute-prompt "dict> " replcmd dict

=cut

EOF


if [ $# -le 0 ]
then
	pod2text "$0" >&2
	exit 2
fi

while read -a words
do
	"$@" "${words[@]}"
done
