#!/usr/bin/env perl

use POSIX;

system @ARGV;
$status = ${^CHILD_ERROR_NATIVE};

if(WIFSIGNALED($status))
{
	printf STDERR "command terminated by signal %d.\n", WTERMSIG($status);
}
else
{
	printf STDERR "command exited with status %d.\n", WEXITSTATUS($status);
}

__END__

=pod

=head1 NAME

reportcmdstatus - Textually shows how a given command finished

=cut

