#!/bin/bash

if [ "$1" = --help ]
then
	echo "Rename one file, no overwrite:
  rn [<OLDNAME>] [<NEWNAME>]
Rename 1 or more than 2 files interactively:
  rn [<FILENAME-1> [<FILENAME-2> [...]]]"
	exit
fi

if [ $# = 2 ]
then
	if [ "$1" = "$2" ]
	then
		exit 0
	fi
	
	if [ ! -e "$2" -o -d "$2" ]
	then
		mv -n "$@"
		# set error status if the first file still exists (rename was not successful)
		test ! -e "$1" || exit 17
	else
		renamemanual "$@"
	fi
else
	renamemanual "$@"
fi
