#!/bin/bash

true <<EOF
=pod

=head1 NAME

screens - List all GNU/Screen sessions accessible by the user and all of their inner windows as well

=cut

EOF


screen -ls |\
grep -Evi '^(No Sockets found|[0-9]+ Sockets? in)|^\s*$' |\
while IFS=$'\n' read -r line
do
	echo "$line"
	if [[ $line =~ ^[\ $'\t']+([^ $'\t']+) ]]
	then
		sty=${BASH_REMATCH[1]}
		for win in `screen -S "$sty" -Q @echo -p %v`
		do
			win=${win//[!0-9]/}
			tty=`screen -S "$sty" -p "$win" -Q @echo -p %T`
			title=`screen -S "$sty" -p "$win" -Q @echo -p %t`
			echo $'\t'$'\t'"$win"$'\t'"$tty"$'\t'"$title"
			unset tty
			unset title
		done
		unset win
		unset sty
	fi
done
