#!/bin/sh

if [ $# -lt 2 ]
then
	echo "Usage: singleinstance <LOCKFILE> <COMMAND> [<ARGS>]" >&2
	exit 1
fi

set -e

lockpidfile=$1
shift

exec flock --exclusive --nonblock --no-fork "$lockpidfile" withpidfile "$lockpidfile" "$@"
