#!/bin/bash

true <<EOF
=pod

=head1 NAME

slay - Try to kill a process until it exists

slayall - Try to kill a process by name until it exists

=cut

EOF


usage()
{
	echo "Usage:
 slay [-SIGNAL] <PID>
 slayall [-SIGNAL] <PROCESS-NAME>"
}

myname=${0##*/}
declare -a argv

while [ -n "$1" ]
do
	case "$1" in
	--help)	usage; exit;;
	-*)
		argv+=("$1")
		;;
	*)
		prm=$1
		argv+=("$1")
		;;
	esac
	shift
done

set -u

if [ "$myname" = slay ]
then
	while [ -d "/proc/$prm" ]
	do
		kill "${argv[@]}"
		sleep 0.1
	done
elif [ "$myname" = slayall ]
then
	while killall -0 "$prm"
	do
		killall "${argv[@]}"
		sleep 0.1
	done
else
	usage >&2
	exit -1
fi
