#!/bin/bash

true <<EOF
=pod

=head1 NAME

swap - swaps two files' names

=cut

EOF


set -e

if [ $# -ne 2 ]
then
	echo "Usage: swap [<FILE-1>] [<FILE-2>]" >&2
	exit 1
fi


if [ ! -e "$1" -a -e "$2" ]
then
	f1=$2
	f2=$1
else
	f1=$1
	f2=$2
fi


if [ ! -e "$f2" ]
then
	mv -v --no-target-directory "$f1" "$f2"
else
	TMP=`TMPDIR=. mktemp $([ -d "$f1" ] && echo --directory) --dry-run -t .swap.XXXXXX`
	
	if mv -v --no-target-directory "$f1" "$TMP"
	then
		if mv -v --no-target-directory "$f2" "$f1"
		then
			if mv -v --no-target-directory "$TMP" "$f2"
			then
				exit 0
			fi
			exit 4
		fi
		exit 3
	fi
fi

exit 2
