#!/usr/bin/env perl

use POSIX qw/strftime/;

$fmt = $ENV{'TIMESTAMP_FMT'} || '%F %T %z';


while(<STDIN>)
{
	print strftime($fmt, localtime);
	print "\t";
	print $_;
}


__END__

=pod

=head1 NAME

timestamper - Prepend a timestamp to each input line

=head1 SYNOPSIS

timestamper

=head1 DESCRIPTION

Read STDIN and put everything on STDOUT, only prepending each line by a timestamp and a B<TAB> char.

=head1 ENVIRONMENT

=over 4

=item TIMESTAMP_FMT

Timestamp format, see strftime(3).
Default is "%F %T %z".

=back

=head1 SEE ALSO

ts(1) from moreutils

=cut
