#!/bin/bash

set -e
set -o pipefail
set -u


true <<'EOF'

=pod

=head1 NAME

trackrun - Record when the given command was started and ended and expose to it in environment variables

=head1 SYNOPSIS

trackrun [<OPTIONS>] [--] <COMMAND> [<ARGS>]

=head1 OPTIONS

=over 4

=item -f, --full-command

=item -b, --command-basename (default)

=item -n, --name NAME

=item -e, --env-var ENV

=back

=head1 DESCRIPTION

It records when it starts COMMAND and when it ends, identifying COMMAND either by one of 4 options:
(1) Full command line including ARGS.
(2) Only the command name, COMMAND.
(3) By the name given by the user in NAME.
(4) By the environment variable given by name ENV.

Set B<TRACKRUN_LAST_STARTED> and B<TRACKRUN_LAST_ENDED> environments for COMMAND to the ISO 8601 representation
of the date and time when COMMAND was last started and ended respectively.
Set B<TRACKRUN_LAST_STATUS> to the status COMMAND last exited with.
Those are left empty if no data yet.

=head1 FILES

Store tracking data in C<~/.trackrun> directory.

=head1 ENVIRONMENT

=over 4

=item TRACKRUN_LAST_STARTED

=item TRACKRUN_LAST_ENDED

=item TRACKRUN_LAST_STATUS

=back

=head1 LIMITATIONS

Trackrun does not do locking. You may take care of it if you need using flock(1), cronrun(1), or similar.

=cut

EOF


cmd_id=''
cmd_id_by=basename


while [ $# -gt 0 ]
do
	case "$1" in
	--help)
		pod2text "$0"
		exit 0;;
	-f|--full-command)
		cmd_id_by=full
		;;
	-b|--command-basename)
		cmd_id_by=basename
		;;
	-n|--name)
		cmd_id_by=name
		shift
		cmd_id=$1
		;;
	-e|--env-var)
		cmd_id_by=env
		shift
		cmd_id=${!1}
		;;
	--)
		shift
		break;;
	-*)
		echo "$0: unknown option: $1" >&1
		exit -1;;
	*)
		break;;
	esac
	shift
done


if [ $# = 0 ]
then
	pod2text "$0" >&2
	exit -1
fi


declare -a cmd_args=("$@")


if [ -z "$cmd_id" ]
then
	case "$cmd_id_by" in
	full)
		cmd_id=${cmd_args[*]}
		;;
	basename)
		cmd_id=`basename "${cmd_args[0]}"`
		;;
	esac
fi


track_dir=~/.trackrun
cmd_id_hash=`printf %s "$cmd_id" | md5sum | cut -c 1-32`
track_file=$track_dir/$cmd_id_hash

lookup()
{
	# lookup A B C
	# return the C-th field of the first line in stdin of which A-th field is B
	awk -F $'\t' -v field_num="$1" -v field_val="$2" -v field_ret="$3" \
		'{if($field_num == field_val){ print $field_ret; exit; }}'
}

mkdir -p "$track_dir"
export TRACKRUN_LAST_STARTED=`tac "$track_file" 2>/dev/null | lookup 1 start 2`
export TRACKRUN_LAST_ENDED=`tac "$track_file" 2>/dev/null | lookup 1 end 2`
export TRACKRUN_LAST_STATUS=`tac "$track_file" 2>/dev/null | lookup 1 end 3`

record()
{
	printf "%s\t%(%FT%T%z)T\t%s\t%s\n" "$1" -1 "${2:-}" "${cmd_args[*]}" >> "$track_file"
}

record start

{
	exec -- setsid ${cmd_args[@]}
	exit 127
} &

child_pid=$!
signal_handler() { interrupted=yes; }
trap signal_handler INT
while true
do
	interrupted=''
	set +e
	wait $child_pid
	exit_code=$?
	set -e
	if [ $interrupted ]
	then
		exit_code=''
		kill -s INT $child_pid || true
	else
		break
	fi
done

record end $exit_code

exit $exit_code
