#!/bin/bash

declare -a chmod_opt
chmod_opt=()
maxdepth="-maxdepth 0"
do_dirs=''
do_files=''

help()
{
	echo "Usage: $0 [--verbose | --changes | --recursive | --dirs | --files] <files and folders>" >&2
	exit ${1:-1}
}

while [ -n "$1" ]
do
	case "$1" in
	-v|--verbose|-c|--changes)
		chmod_opt+=("$1")
		;;
	-R|--recursive)
		maxdepth=''
		;;
	-d|--dirs)
		do_dirs=1
		;;
	-f|--files)
		do_files=1
		;;
	-h|--help)
		help 0
		;;
	--)	shift
		break
		;;
	-*)	echo "Unknown option: $1" >&2
		exit 1
		;;
	*)	break
		;;
	esac
shift
done

if [ -z "$1" ]
then
	help 1
fi

if [ -z "$do_dirs" -a -z "$do_files" ]
then
	do_dirs=1
	do_files=1
fi

umask=`umask -S`
dmod=$umask
fmod=${umask//x/}

if [ $do_dirs ]
then
	find "$@" $maxdepth -type d -print0 | xargs --null chmod "${chmod_opt[@]}" "$dmod" --
fi
if [ $do_files ]
then
	find "$@" $maxdepth -type f -print0 | xargs --null chmod "${chmod_opt[@]}" "$fmod" --
fi


true <<EOF

=pod

=head1 NAME

uchmod - chmod files according to umask

=head1 SYNOPSIS

uchmod [-v] [-R] [B<path>-1] [B<path>-2] ... [B<path>-n]

=head1 DESCRIPTION

Change mode bits of files and directories according to umask(1) settings using chmod(1).
Use it when file modes were messed up, B<uchmod> change them like mode of newly created files.

=cut

EOF
