#!/bin/sh

true <<EOF
=pod

=head1 NAME

url_encode_bf - Make all chars given either in parameters or in stdin to percent-encoded sequence

=cut

EOF


test -n "$*" && echo -n "$*" | od -t x1 -A n | tr " " % | tr -d "\n\r" || od -t x1 -A n | tr " " % | tr -d "\n\r"
