#!/bin/bash

set -e -o pipefail
set -u

server_side_workdir_prefix=/tmp/vncssh
lsock=$HOME/vncssh.sock
server_ready_str=VNC_SERVER_SOCKET_IS_AVAILABLE


socket_live()
{
	cat /proc/net/unix | cut -d' ' -f8- | grep -qFx "$1"
}


if [ "$1" = --remote-side ]
then
	shift
	ssh_hostname=$1
	shift
	
	workdir=$server_side_workdir_prefix.$USER
	listening_sock=$workdir/vnc.sock
	
	mkdir -p "$workdir"
	tigervncserver -rfbunixpath "$listening_sock" -rfbport -1 -SecurityTypes None -xstartup /etc/X11/Xsession -autokill yes -desktop "$ssh_hostname" -useold
	
	while ! socket_live "$listening_sock"
	do
		sleep 0.2
	done
	
	echo "$server_ready_str"
	
	# keep up the connection:
	while socket_live "$listening_sock"
	do
		echo "keeping connection open while $listening_sock is listening." >&2
		nc -U "$listening_sock" </dev/null >/dev/null || true
	done

elif [ "$1" = --tunnel ]
then
	shift
	
	declare -a ssh_opts=()
	for ((i=0; i < $SSH_OPT_COUNT; i++))
	do
		varname=SSH_OPT_$i
		ssh_opts+=("${!varname}")
	done
	
	ruser=`ssh "${ssh_opts[@]}" "$VNCSSH_HOST" -N -G | awk '$1 == "user" { print $2 }'`
	rsock=$server_side_workdir_prefix.$ruser/vnc.sock
	
	set -x
	ssh "${ssh_opts[@]}" "$VNCSSH_HOST" \
		-o ControlPath=none -o ExitOnForwardFailure=yes \
		-L "$lsock:$rsock" \
		-T "bash /dev/stdin --remote-side $VNCSSH_HOST" < "$0"

else
	declare -a ssh_opts=()
	target=$1
	shift
	
	if [[ $target =~ ^([^@]+)@(.+)$ ]]
	then
		ssh_opts+=(-l "${BASH_REMATCH[1]}")
		VNCSSH_HOST=${BASH_REMATCH[2]}
	else
		VNCSSH_HOST=$target
	fi
	export VNCSSH_HOST
	
	for ((i=0; i < ${#ssh_opts[@]}; i++))
	do
		eval "SSH_OPT_$i=\${ssh_opts[$i]}"
		eval "export SSH_OPT_$i"
	done
	export SSH_OPT_COUNT=$i
	
	if ! socket_live "$lsock"
	then
		if [ -S "$lsock" ]
		then
			rm "$lsock"
		else
			echo "$lsock: Can not listen on socket. File exists and not a socket." >&2
			exit 2
		fi
		
		fifo_dir=`mktemp -d -t vncssh-XXXXXX`
		fifo=$fifo_dir/ssh-tunnel.stdout
		mkfifo "$fifo"
		
		"$0" --tunnel </dev/null >"$fifo" &
		while read -r line
		do
			printf '%s\n' "$line"
			if [[ $line =~ $server_ready_str ]]
			then
				break
			fi
		done < "$fifo"
		cat "$fifo" & disown
	fi
	
	exec xvncviewer "$lsock" "$@"
fi
