#!/bin/bash

set -eo pipefail
set -u

server_side_workdir_prefix=/tmp/vncssh


if [ "$1" = --remote-side ]
then
	shift
	ssh_hostname=$1
	shift
	workdir=$server_side_workdir_prefix.$USER
	listening_sock=$workdir/vnc.sock
	
	mkdir -p "$workdir"
	if grep -Fq "$listening_sock" /proc/net/unix
	then
		echo "$listening_sock: already listening. not starting new VNC Server." >&2
		echo "going to sleep to keep up the connection." >&2
		sleep inf
	else
		echo "$listening_sock: starting new VNC Server." >&2
		tigervncserver -rfbunixpath "$listening_sock" -rfbport -1 -SecurityTypes None -xstartup /etc/X11/Xsession -autokill yes -fg -desktop "$ssh_hostname"
	fi

elif [ "$1" = --via-cmd ]
then
	shift
	
	# 1-letter env vars passed by xvncviewer:
	rhost=$G
	lport=$L
	rport=$R  # unused
	lhost=$H  # unused
	
	declare -a ssh_opts=()
	for ((i=0; i < $SSH_OPT_COUNT; i++))
	do
		varname=SSH_OPT_$i
		ssh_opts+=("${!varname}")
	done
	
	ruser=`ssh "${ssh_opts[@]}" "$rhost" -G | awk '$1 == "user" { print $2 }'`
	rsock=$server_side_workdir_prefix.$ruser/vnc.sock
	
	set -x
	# TODO FIXME dont listen on local tcp port: make vnc viewer connect to UDS instead!
	ssh "${ssh_opts[@]}" "$rhost" -o ControlPath=none -o ExitOnForwardFailure=yes -o ForkAfterAuthentication=yes -L "$lport:$rsock" -T "bash /dev/stdin --remote-side $rhost" < "$0"
	set +x
	
	# verify if the server respons on the port.
	# let xvncviewer proceed only if we can read at least 1 byte from the VNC server.
	# TODO FIXME this triggers "CConn:       Authentication failure: Too many security failures" in the server
	LPORT=$lport \
		perl -e 'use IO::Socket::INET; use IO::Select;
			RETRY: $sock = IO::Socket::INET->new(PeerAddr=>"127.0.0.1", PeerPort=>$ENV{LPORT}, Proto=>"tcp", Timeout=>1);
			goto RETRY unless $sock;
			$sel = IO::Select->new($sock);
			@ready = $sel->can_read(0.2);
			goto RETRY unless @ready;
			$n = sysread($sock, $buf, 12);  # RFB banner line is 12 bytes.
			goto RETRY unless $n;
			warn "tcp $ENV{LPORT} port is ready to read.\n";
			exit 0;
		'

else
	declare -a ssh_opts=()
	target=$1
	
	if [[ $target =~ ^([^@]+)@(.+)$ ]]
	then
		ssh_opts+=(-l "${BASH_REMATCH[1]}")
		rhost=${BASH_REMATCH[2]}
	else
		rhost=$target
	fi
	
	for ((i=0; i < ${#ssh_opts[@]}; i++))
	do
		eval "SSH_OPT_$i=\${ssh_opts[$i]}"
		eval "export SSH_OPT_$i"
	done
	export SSH_OPT_COUNT=$i
	
	desktop_size=`xwininfo -root | grep geometry | awk '{print $2}'`
	
	VNC_VIA_CMD="$0 --via-cmd" \
		xvncviewer -DesktopSize="$desktop_size" -via "$rhost" localhost
fi
