#!/bin/bash

true <<EOF
=pod

=head1 NAME

waitpid - Wait for a process to end (even if not child of current shell)

=cut

EOF


if [ "$1" -gt 0 ] 2>/dev/null
then
	pid=$1
	while [ -d /proc/$pid ]
	do
		sleep 0.5
	done
	exit 0
else
	echo "Usage: $0 [PID]" >&2
	exit 1
fi
