#!/usr/bin/env python2

import os
import sys
import re
import gtk

def esc(s):
	return s.replace('\\', '\\\\').replace('"', '\\"')

def iconpath_for_mime(mime):
	BASE = "/usr/share/rox/ROX/MIME"
	(main, sub) = mime.split('/')
	path = os.path.join(BASE, main+'-'+sub+'.png')
	if not os.path.exists(path):
		path = os.path.join(BASE, main+'-x-generic.png')
	return path


items = os.popen('recent-files-gtk', 'r').readlines()
dirs = {}

for item in items:
	item = item.rstrip('\n')
	mime_type, filepath = item.split('\t', 1)
	filepath = filepath.rstrip(os.path.sep)
	
	if os.path.exists(filepath):
			label = os.path.basename(filepath)
			iconpath = iconpath_for_mime(mime_type)
			
			# this method seems sparsely supported by applications
			# they register their commands wrong.
			#
			#app = item.last_application()
			#(cmd, _, _) = item.get_application_info(app)
			#command_str = "%s %s" % (cmd, filepath)
			
			command_str = "%s \"%s\"" % ('rox' if os.path.isdir(filepath) else 'mimeopen-gui', esc(filepath))
			
			print "prog \"%s\" \"%s\" %s" % (esc(label), esc(iconpath), command_str)
			
			if not os.path.isdir(filepath):
				dirpath = os.path.dirname(filepath)
				if dirpath not in dirs:
					dirs[dirpath] = True
					print "prog \"%s\" folder rox \"%s\"" % (esc(dirpath), esc(dirpath))
