#!/usr/bin/env perl

use IPC::Run qw/run/;
use List::MoreUtils qw/all any none uniq/;
use Data::Dumper;
use X11::Protocol;
#use X11::Protocol::Xlib;
no if ($] >= 5.018), 'warnings' => 'experimental::smartmatch';


$Xorg = X11::Protocol->new();
$RootWindow = $Xorg->root;


sub esc
{
	$_[0] =~ s/\\/\\\\/gr =~ s/[""]/\\$&/gr =~ s/_/__/r;
}

sub current_xorg_window
{
	my ($current_window_id) = $Xorg->GetInputFocus;
	my ($classes) = $Xorg->GetProperty($current_window_id, $Xorg->atom('WM_CLASS'), 0, 0, 1024);
	my ($class, $instance) = split chr(0), $classes;
	my ($title) = $Xorg->GetProperty($current_window_id, $Xorg->atom('_NET_WM_NAME'), $Xorg->atom('UTF8_STRING'), 0, 1024);
	($title) = $Xorg->GetProperty($current_window_id, $Xorg->atom('WM_NAME'), 0, 0, 1024) unless $title;
	return {id=>$current_window_id, class=>"$class.$instance", title=>$title};
}

sub add_menu_item
{
	my $label = shift;
	my $icon = shift;
	my $command = shift;
	printf "prog \"%s\" %s %s\n", $label, $icon, $command;
}


$win = current_xorg_window;

if($win->{class} =~ /^navigator\.firefox/i)
{
}
elsif($win->{class} =~ /^navigator\.pale/i)
{
}
else
{
	add_menu_item "unknown foreground application: $win->{class}", "dialog-warning", "false";
}

#$cred_site = 


add_menu_item "unknown foreground application: $win->{class}", "user-identity", "false";
add_menu_item "unknown foreground application: $win->{class}", "dialog-password", "false";
