#!/usr/bin/env perl

$\ = "\n";

$HOME = $ENV{"HOME"};

for my $path ("$HOME/.gtk-bookmarks", glob "$HOME/.config/gtk-*/bookmarks")
{
	if(open my $f, '<', $path)
	{
		push @gtk_bookmark_files, $path;
		
		while(<$f>)
		{
			if(s{^file://(\S+).*\n}{$1})
			{
				s/%(..)/chr hex $1/ge;  # decode url-encoded chars
				s/[""\\]/\\$&/g;  # escape for icewm menu parser
				my $label = s{^\Q$HOME\E/}{~/}r =~ s/_/__/r;
				print "prog \"$label\" folder mimeopen \"$_\"";
			}
		}
		close $f;
	}
}

print "separator";
print "prog Szerkesztés text-editor mimeopen-gui ".join(' ', map { "'$_'" } @gtk_bookmark_files);
