
REPO_ROOT = ..

TOOLS = \
  icewm-menu-bookmarks \
  icewm-menu-cwds \
  icewm-menu-recently-used \
  icewm-menuhelper-parent-dirs \
  icewm-menu-startup-progs \
  icewm-menu-ssh-sessions \
  icewm-trayapp \
  


include ../user-tools/Makefile
