#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import argparse
import gtk
import glib
import pango
import gobject
import re
import sys
import os
import subprocess
import time
from datetime import datetime
from dateutil.relativedelta import relativedelta
import traceback
from hband_tools.gui import *
import threading
gtk.gdk.threads_init()
import json
from jinja2 import Template
import difflib



unicode = unicode  # just to keep python language server happy


def add_key_binding(widget, keyname, callback):
	accelgroup = gtk.AccelGroup()
	key, modifier = gtk.accelerator_parse(keyname)
	accelgroup.connect_group(key, modifier, gtk.ACCEL_VISIBLE, callback)
	widget.add_accel_group(accelgroup)

def successor_iter(model, predecessor):
	"""return the next "heir" in line of succession metaphorically speaking.
	i.e. the first child of the node if there is any, otherwise its next sibling node,
	otherwise its parent node's next sibling."""
	if model.iter_has_child(predecessor):
		return model.iter_nth_child(predecessor, 0)
	else:
		successor = model.iter_next(predecessor)
		if successor is None:
			while True:
				parent = model.iter_parent(predecessor)
				if parent is None: return None
				uncle = model.iter_next(parent)
				if uncle is not None: return uncle
				predecessor = parent
			return None
		return successor


class TreeModelRow(object):
	"""proxy class for inextensible gtk.TreeModelRow"""
	def __init__(self, treemodelrow, upstream_treemodel):
		self.real_treemodelrow = treemodelrow
		self.upstream_treemodel = upstream_treemodel
	@property
	def path(self):
		return self.real_treemodelrow.path
	@property
	def iter(self):
		return self.real_treemodelrow.iter
	@property
	def model(self):
		return self.real_treemodelrow.model
	def __getitem__(self, item):
		item = self.upstream_treemodel.get_column_num(item)
		answer = gtk.TreeModel.get(self.model, self.iter, item)[0]
		return self.upstream_treemodel.convert_cell(item, answer)
	def __setitem__(self, item, value):
		item = self.upstream_treemodel.get_column_num(item)
		self.real_treemodelrow[item] = value
	def __len__(self):
		return self.real_treemodelrow.__len__()
	def as_dict(self):
		return dict([(col_name, self[col_name]) for col_name in self.upstream_treemodel.column_name])

class TreeModelProxy(object):
	@staticmethod
	def _proxy_foreach(model, treepath, treeiter, _proxy_userdata):
		func = _proxy_userdata['func']
		userdata = _proxy_userdata['userdata']
		derived_model = _proxy_userdata['derived_model']
		return func(derived_model, treepath, treeiter, userdata)

class TreeModelFilter(gtk.TreeModelFilter):
	_proxy_implemented = ['__getitem__', 'foreach', 'get', 'get_value']
	def __init__(self, upstream_treemodel, treemodel_filter):
		self._proxy_real_treemodel = treemodel_filter
		self._proxy_upstream_treemodel = upstream_treemodel
	def __getitem__(self, item):
		answer = self._proxy_real_treemodel.__getitem__(item)
		return TreeModelRow(answer, self._proxy_upstream_treemodel)
	def foreach(self, func, userdata):
		_proxy_userdata = {'func': func, 'userdata': userdata, 'derived_model': self}
		self._proxy_real_treemodel.foreach(TreeModelProxy._proxy_foreach, _proxy_userdata)
	def get(self, row, *columns):
		raise(Exception('unimplemented'))
	def get_value(self, treeiter, column):
		raise(Exception('unimplemented'))
	def __len__(self):
		return len(self._proxy_real_treemodel)
	def __getattribute__(self, attr):
		if attr.startswith('_proxy_') or attr in self._proxy_implemented:
			return object.__getattribute__(self, attr)
		else:
			return object.__getattribute__(self._proxy_real_treemodel, attr)

class TreeModelSort(gtk.TreeModelSort):
	def __init__(self, basemodel):
		if hasattr(basemodel, '_proxy_upstream_treemodel'):
			self._proxy_upstream_treemodel = basemodel._proxy_upstream_treemodel
		else:
			self._proxy_upstream_treemodel = basemodel
		if hasattr(basemodel, '_proxy_real_treemodel'):
			basemodel = basemodel._proxy_real_treemodel
		super(self.__class__, self).__init__(basemodel)
	def __getitem__(self, item):
		answer = super(self.__class__, self).__getitem__(item)
		return TreeModelRow(answer, self._proxy_upstream_treemodel)
	def foreach(self, func, userdata):
		_proxy_userdata = {'func': func, 'userdata': userdata, 'derived_model': self}
		super(self.__class__, self).foreach(TreeModelProxy._proxy_foreach, _proxy_userdata)
	def get(self, row, *columns):
		raise(Exception('unimplemented'))
	def get_value(self, treeiter, column):
		raise(Exception('unimplemented'))

class TreeStore(gtk.TreeStore):
	__gsignals__ = {
		'changed': (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, ()),
		'set-changed': (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, ()),
	}
	def __init__(self, *columns):
		self.column_name = []
		self.reader = {}
		self.empty = []
		types = []
		self.input_types = []
		n = 0
		for col_name, col_type in columns:
			self.input_types.append(col_type)
			empty_value = None
			if col_type == unicode:
				col_type = str
				self.reader[n] = self.to_unicode
			if col_type == str:
				empty_value = ''
			elif col_type in [int, float]:
				empty_value = 0
			self.empty.append(empty_value)
			types.append(col_type)
			self.column_name.append(col_name)
			n += 1
		super(self.__class__, self).__init__(*types)
		for event in 'row-changed', 'row-deleted', 'row-inserted':
			self.connect_after(event, self.emit_signal, 'changed')
			self.connect_after(event, self.emit_signal, 'set-changed')
		self.connect_after('rows-reordered', self.emit_signal, 'changed')
	def emit_signal(self, *args):
		signal_name = args[-1]
		self.emit(signal_name)
	@staticmethod
	def to_unicode(s):
		if s is None: return None
		return unicode(s)
	@staticmethod
	class ColumnNotFoundException(Exception):
		pass
	def get_columns(self):
		return zip(self.column_name, self.input_types)
	def get_column_num(self, col_ref):
		if isinstance(col_ref, int):
			if col_ref < 0 or col_ref >= len(self.column_name):
				raise self.__class__.ColumnNotFoundException(col_ref)
			return col_ref
		try:
			return self.column_name.index(col_ref)
		except ValueError:
			raise self.__class__.ColumnNotFoundException(col_ref)
	def get_column_name(self, col_num):
		try:
			return self.column_name[col_num]
		except IndexError:
			raise self.__class__.ColumnNotFoundException(col_num)
	def get(self, row, *columns):
		if type(row) == tuple:
			row = self.get_iter(row)  # tree iterator path was given
		if len(columns) == 0:
			return tuple()
		columns = list(columns)
		for i, col in enumerate(columns):
			columns[i] = self.get_column_num(col)
		answer = super(self.__class__, self).get(row, *columns)
		answer = list(answer)
		for i, col_num in enumerate(columns):
			answer[i] = self.convert_cell(col_num, answer[i])
		answer = tuple(answer)
		return answer
	def get_value(self, treeiter, column):
		raise Exception('unimplemented')
	def convert_cell(self, col_num, cell_value):
		if self.reader.has_key(col_num):
			return self.reader[col_num](cell_value)
		return cell_value
	def __getitem__(self, item):
		answer = super(self.__class__, self).__getitem__(item)
		return TreeModelRow(answer, self)
	def _row_dict_to_list(self, row):
		if type(row) == dict:
			cols = row
			row = self.empty[:]
			for col_name, value in cols.iteritems():
				row[self.get_column_num(col_name)] = value
		return row
	def append(self, parent, row):
		return super(self.__class__, self).append(parent, self._row_dict_to_list(row))
	def insert_after(self, parent, sibling, row):
		return super(self.__class__, self).insert_after(parent, sibling, self._row_dict_to_list(row))
	def insert_before(self, parent, sibling, row):
		return super(self.__class__, self).insert_before(parent, sibling, self._row_dict_to_list(row))
	def set(self, treeiter, *itempairs):
		if len(itempairs) == 0: return
		if type(itempairs[0]) == dict:
			cols = itempairs[0]
			itempairs = []
			for col_name, value in cols.iteritems():
				itempairs.extend([self.get_column_num(col_name), value])
		super(self.__class__, self).set(treeiter, *itempairs)
	def get_cells_by_column(self, col_name):
		treeiter = self.get_iter_root()
		while treeiter is not None:
			yield self[treeiter][col_name]
			treeiter = successor_iter(self, treeiter)
	def walk_columns(self, *columns):
		"""yields a sequence of [TreeModelRow, depth, value-1, value-2, ..., value-n] lists
		for depth being the row's level on the tree and value-1 to value-n being the 
		content of cells in the requested columns in each row"""
		treeiter = self.get_iter_root()
		while treeiter is not None:
			row = self[treeiter]
			answer = [row]
			answer.extend(self.get(treeiter, *columns))
			yield answer
			treeiter = successor_iter(self, row.iter)
	def filter_new(self, root=None):
		treemodelfilter = super(self.__class__, self).filter_new(root=root)
		return TreeModelFilter(self, treemodelfilter)

class TreeView(gtk.TreeView):
	__gsignals__ = {
		'menu-popup': (gobject.SIGNAL_RUN_LAST, gobject.TYPE_BOOLEAN, (gobject.TYPE_PYOBJECT, gobject.TYPE_PYOBJECT, gobject.TYPE_PYOBJECT, gobject.TYPE_PYOBJECT, gobject.TYPE_PYOBJECT)),
		'header-menu-popup': (gobject.SIGNAL_RUN_LAST, gobject.TYPE_BOOLEAN, (gobject.TYPE_PYOBJECT, gobject.TYPE_PYOBJECT)),
		'column-added': (gobject.SIGNAL_RUN_LAST, gobject.TYPE_BOOLEAN, (gobject.TYPE_PYOBJECT,)),
		'column-width-changed': (gobject.SIGNAL_RUN_LAST, gobject.TYPE_BOOLEAN, (gobject.TYPE_PYOBJECT, int)),
		'sort-by-column-changed': (gobject.SIGNAL_RUN_LAST, gobject.TYPE_BOOLEAN, (gobject.TYPE_PYOBJECT,)),
		'column-sort-order-changed': (gobject.SIGNAL_RUN_LAST, gobject.TYPE_BOOLEAN, (gobject.TYPE_PYOBJECT,)),
		'column-visibility-changed': (gobject.SIGNAL_RUN_LAST, gobject.TYPE_BOOLEAN, (gobject.TYPE_PYOBJECT,)),
		'selection-change': (gobject.SIGNAL_RUN_LAST, gobject.TYPE_BOOLEAN, (gobject.TYPE_PYOBJECT,)),
	}
	def __init__(self, model):
		super(self.__class__, self).__init__(model)
		self._stored_column_width = {}
		self._sortby_column_name = None
		self._resorting = False
		self.set_reorderable(True)
		self.set_headers_clickable(True)
		self.set_rubber_banding(True)
		self.get_selection().set_mode(gtk.SELECTION_MULTIPLE)
		self.get_selection().connect('changed', self._on_selection_changed)
		self.connect('button-press-event', self._on_button_click)
		self.connect('realize', self._on_realize)
		self.connect('columns-changed', self._on_columns_changed)
		self.connect('key-release-event', self._on_key_release)
		self.connect('header-menu-popup', self._on_header_menu_popup)

	def _on_key_release(self, widget, event):
		if event.keyval == gtk.gdk.keyval_from_name('space'):
			iterpath, tv_col = self.get_cursor()
			cr = tv_col.get_cell_renderers()[0]
			cr.on_start_editing(event, widget, ','.join(map(str, iterpath)), self.get_background_area(iterpath, tv_col), self.get_cell_area(iterpath, tv_col), 0)

	def _on_button_click(self, widget, event):
		if event.button == MOUSE_BUTTON_RIGHT:
			x, y = int(event.x), int(event.y)
			event_target_info = self.get_path_at_pos(x, y)
			if event_target_info is not None:
				treepath, tv_col, cell_x, cell_y = event_target_info
			else:
				treepath, tv_col, cell_x, cell_y = None, None, None, None
			self.get_selection().select_path(treepath)
			popup_menu = gtk.Menu()
			if not self.emit('menu-popup', popup_menu, treepath, tv_col, cell_x, cell_y):
				# event is not handled by any handlers, so do it ourself
				if popup_menu.get_children():
					popup_menu.show_all()
					popup_menu.popup(None, None, None, event.button, event.time)
			return True

	def _on_realize(self, widget):
		for tvc in self.get_columns():
			self._column_setup_events(tvc)

	def _on_columns_changed(self, widget):
		# clear 'layoutstash', it is needed for CellRendererTextOverflow
		self.set_data('layoutstash', {})

	def set_columns(self, columns):
		for col in self.get_columns(): self.remove_column(col)
		return self.add_columns(columns)
	
	def add_columns(self, columns):
		for col_name, col_title, col_attr, col_num in columns:
			tvc = TreeViewColumn()
			tvc.set_name(col_name)
			tvc.title = col_title
			tvc.set_sort_indicator(True)
			tvc.set_sort_column_id(col_num)
			tvc.set_resizable(True)
			tvc.set_sizing(gtk.TREE_VIEW_COLUMN_FIXED)
			tvc.set_reorderable(True)
			
			cr_txt = CellRendererTextOverflow()
			cr_txt.set_data('treeviewcolumn', tvc)
			tvc.pack_start(cr_txt, True)
			tvc.add_attribute(cr_txt, col_attr, col_num)
			
			self.append_column(tvc)

	def _on_column_width_change(self, col, gparam):
		w = col.get_width()
		if w != self._stored_column_width.get(col.name):
			self.emit('column-width-changed', col, w)
		self._stored_column_width[col.name] = w

	def append_column(self, tvc):
		super(self.__class__, self).append_column(tvc)
		self._column_setup_events(tvc)
		self.emit('column-added', tvc)

	def _column_setup_events(self, tvc):
		if hasattr(tvc, 'setup_events'):
			tvc.setup_events()
			if not tvc.get_data('treeview-connect-done'):
				tvc.connect('button-press-event', self._on_column_click)
				tvc.set_data('treeview-connect-done', True)
		tvc.connect('notify::width', self._on_column_width_change)
		tvc.connect('notify::visible', self._on_column_visibility_changed)
		tvc.connect('notify::sort-order', self._on_column_sort_order_changed)

	def _on_column_click(self, col_widget, event):
		if event.button == MOUSE_BUTTON_RIGHT:
			popup_menu = gtk.Menu()
			if not self.emit('header-menu-popup', popup_menu, col_widget):
				popup_menu.show_all()
				popup_menu.popup(None, None, None, event.button, event.time)
			return True
		elif event.button == MOUSE_BUTTON_LEFT:
			self._set_sortby_column(col_widget)
			self.set_search_column_by_name(col_widget.name)

	def set_search_column_by_name(self, colname):
		model_col_num = self.get_model().get_column_num(colname)
		self.set_search_column(model_col_num)

	def set_sortby_column_by_name(self, colname):
		sort_column = self.get_column_by_name(colname)
		sort_order = sort_column.get_sort_order()
		sort_column.clicked()
		self._set_sortby_column(sort_column)
		sort_column.set_sort_order(sort_order)
		self.set_search_column_by_name(colname)

	def _set_sortby_column(self, col):
		self._sortby_column_name = col.name
		if not self._resorting:
			self.emit('sort-by-column-changed', col)
			self.emit('column-sort-order-changed', col)
	
	def get_sortby_column(self):
		return self.get_column_by_name(self._sortby_column_name)

	def _on_column_sort_order_changed(self, tvc, gparam):
		if not self._resorting:
			self.emit('column-sort-order-changed', tvc)

	def _on_column_visibility_changed(self, tvc, gparam):
		self.emit('column-visibility-changed', tvc)
	
	def resort(self):
		"apply the current sort column to the model"
		self._resorting = True
		try:
			self.set_sortby_column_by_name(self._sortby_column_name)
		except:
			pass
		finally:
			self._resorting = False

	@staticmethod
	class ColumnNotFoundException(Exception):
		pass

	def get_column_by_name(self, colname):
		for col in self.get_columns():
			if col.name == colname:
				return col
		raise self.__class__.ColumnNotFoundException(colname)
	
	def get_column_number_by_name(self, colname):
		for num, col in enumerate(self.get_columns()):
			if col.name == colname:
				return num
		raise self.__class__.ColumnNotFoundException(colname)
	
	def columns_autosize(self, cols=None):
		self.previous_widths = {}
		for tvc in self.get_columns() if cols is None else cols:
			self.previous_widths[tvc.name] = tvc.get_fixed_width()
			tvc.set_sizing(gtk.TREE_VIEW_COLUMN_AUTOSIZE)
		gtk.TreeView.columns_autosize(self)
		glib.idle_add(self._columns_autosize_restore_resizable, priority=glib.PRIORITY_DEFAULT_IDLE)
	def _columns_autosize_restore_resizable(self):
		for tvc in self.get_columns():
			width = tvc.get_width()
			tvc.set_sizing(gtk.TREE_VIEW_COLUMN_FIXED)
			if width > 1:
				tvc.set_fixed_width(width)
			tvc.set_resizable(True)
	def restore_previous_widths(self, cols=None):
		for tvc in self.get_columns() if cols is None else cols:
			tvc.set_fixed_width(self.previous_widths[tvc.name])

	def _on_header_menu_popup(self, tv, popup_menu, tv_col):
		for col in self.get_columns():
			markup = glib.markup_escape_text(col.title)
			if tv_col.name == col.name:
				markup = '<b>' + markup + '</b>'
			mi = CheckMenuItem(markup=markup)
			mi.set_active(col.get_visible())
			mi.connect('activate', lambda mi, col: col.set_visible(not col.get_visible()), col)
			popup_menu.append(mi)
			if tv_col.name == col.name:
				mi = ImageMenuItem(markup=markup+": set optimal width", icon=gtk.STOCK_FULLSCREEN)
				mi.connect('activate', lambda mi, tv_col: self.columns_autosize([tv_col]), tv_col)
				popup_menu.append(mi)
				mi = ImageMenuItem(markup=markup+": undo width", icon=gtk.STOCK_UNDO)
				mi.connect('activate', lambda mi, tv_col: self.restore_previous_widths([tv_col]), tv_col)
				popup_menu.append(mi)
		popup_menu.append(gtk.SeparatorMenuItem())
		mi = ImageMenuItem(label="set optimal widths", icon=gtk.STOCK_FULLSCREEN)
		mi.connect('activate', lambda mi: self.columns_autosize())
		popup_menu.append(mi)
		mi = ImageMenuItem(label="undo widths", icon=gtk.STOCK_UNDO)
		mi.connect('activate', lambda mi: self.restore_previous_widths())
		popup_menu.append(mi)
		mi = ImageMenuItem(label="reset columns order", icon=gtk.STOCK_REVERT_TO_SAVED)
		#mi.connect('activate', TODO
		popup_menu.append(mi)

	def _on_selection_changed(self, selection):
		model, paths = selection.get_selected_rows()[:]
		self.emit('selection-change', [model[treepath] for treepath in paths])

class TreeViewColumn(gtk.TreeViewColumn):
	__gsignals__ = {
		'button-press-event': (gobject.SIGNAL_RUN_LAST, gobject.TYPE_BOOLEAN, (gobject.TYPE_PYOBJECT,)),
	}
	@property
	def name(self):
		return self.get_name()
	@property
	def title(self):
		return self.get_widget().get_text()
	@title.setter
	def title(self, title):
		tvc_label = gtk.Label(title)
		tvc_label.show()
		self.set_widget(tvc_label)
	def __repr__(self):
		return '<%s name="%s">' % (self.__class__.__name__, self.name)
	def setup_events(self, *X):
		# this method should be called when the TreeView is realized.
		if not self.get_data('setup-events-done'):
			# find the button representing the treeview column header
			# and propagate up events.
			w = self.get_widget()
			while not isinstance(w, gtk.Button):
				w = w.get_parent()
			if w is not None:
				w.connect('button-press-event', lambda widget, event: self.emit('button-press-event', event))
			self.set_data('setup-events-done', True)

class CellRendererTextOverflow(gtk.GenericCellRenderer):
	"""
	This class implements a CellRenderer which renders (markup) text just like
	CellRendererText, but allows the text content to flow over to adjacent empty cells.
	"""
	__gproperties__ = {
		'text': (gobject.TYPE_STRING, 'Text', 'Text', None, gobject.PARAM_READWRITE),
		'markup': (gobject.TYPE_STRING, 'Markup', 'Markup', None, gobject.PARAM_READWRITE),
		'editable': (gobject.TYPE_BOOLEAN, 'Editable', 'Editable', False, gobject.PARAM_READWRITE),
	}
	def __init__(self):
		super(self.__class__, self).__init__()
		self.__gobject_init__()
		self.cr_txt = gtk.CellRendererText()
		self.the_props = {'markup': None}
	def connect(self, *args):
		self.cr_txt.connect(*args)
	def do_set_property(self, pspec, val):
		if pspec.name == 'markup':
			self.the_props[pspec.name] = val
		self.cr_txt.set_property(pspec.name, val)
	def do_get_property(self, pspec):
		if pspec.name == 'markup':
			# CellRendererText can not read 'markup' property back, so we do
			return self.the_props[pspec.name]
		return self.cr_txt.get_property(pspec.name)
	def set_property(self, prop, val):
		return self.cr_txt.set_property(prop, val)
	def on_get_size(self, widget, cell_area):
		x, y, w, h = self.cr_txt.get_size(widget, cell_area)
		return x, y, w, h
	def get_next_column(self, current_column=None):
		"""Return the column at the right side of 'current_column'
		or, if 'current_column' is None, of the column which this CellRenderer is in."""
		tvc = self.get_data('treeviewcolumn')
		tv = tvc.get_tree_view()
		columns = tv.get_columns()
		if current_column is None:
			current_column = tvc
		for num, col in enumerate(columns):
			if col is current_column:
				if num+1 < len(columns):
					return columns[num+1]
				return None
		return None
	def draw_layout(self, window, widget, cell_area, layout, flags):
		base_grctx = widget.style.black_gc
		if (flags & gtk.CELL_RENDERER_SELECTED) != 0: base_grctx = widget.style.white_gc
		window.draw_layout(base_grctx, cell_area.x, cell_area.y, layout)
		return False
	def on_render(self, window, widget, background_area, cell_area, expose_area, flags):
		"""Find out how much empty area we have horizontally
		by sum the width of empty cells on right of the current cell.
		Then render the (markup) text on a pango Layout.
		Save the data neccessary to draw the Layout into 'layoutstash' for each cells 
		which are found empty. Cells are identified by TreeModel path and TreeViewColumn name.
		When an actual empty cell is encountered, then recall the saved Layout (if any) and
		redraw it. It assumes that the controller routine requests us to
		render the cells from left to right in sequence and row-by-row."""
		markup = self.get_property('markup')
		text = self.get_property('text')
		
		tvc = self.get_data('treeviewcolumn')
		tv = tvc.get_tree_view()
		model = tv.get_model()
		cellinfo = tv.get_path_at_pos(cell_area.x, cell_area.y)
		if cellinfo is None:
			cellinfo = tv.get_path_at_pos(cell_area.x + cell_area.width, cell_area.y + cell_area.height)
		treepath = cellinfo[0]
		
		if tv.get_data('last-drawn-row-treepath') != treepath or tv.get_data('layoutstash') is None:
			tv.set_data('layoutstash', {})
		tv.set_data('last-drawn-row-treepath', treepath)
		layoutstash = tv.get_data('layoutstash')
		
		overflow_width = cell_area.width
		next_col = self.get_next_column()
		next_col_names = []
		while next_col is not None:
			next_col_content = model[treepath][next_col.name]
			if next_col_content is None or next_col_content == '':
				overflow_width += next_col.get_width()
				next_col_names.append(next_col.name)
				next_col = self.get_next_column(next_col)
			else:
				break
		if overflow_width != cell_area.width:
			context = widget.get_pango_context()
			layout = pango.Layout(context)
			if markup:
				layout.set_markup(markup)
			elif text:
				layout.set_text(text)
			if markup or text:
				layout.set_width(overflow_width * pango.SCALE)
				layout.set_wrap(pango.WRAP_CHAR)
				layout.set_ellipsize(pango.ELLIPSIZE_END)
				xpad, ypad = self.cr_txt.get_padding()
				draw_area = cell_area.copy()
				draw_area.x += xpad
				draw_area.y += ypad
				if not layoutstash.has_key(treepath):
					layoutstash[treepath] = {}
				for colname in layoutstash[treepath].keys():
					if layoutstash[treepath][colname].has_key(tvc.name):
						del layoutstash[treepath][colname][tvc.name]
				for colname in next_col_names:
					if not layoutstash[treepath].has_key(colname):
						layoutstash[treepath][colname] = {}
					layoutstash[treepath][colname][tvc.name] = (window, widget, draw_area, layout, flags)
		else:
			# this cell's text does not flow over, so delete earlier layouts, if any
			for colname in layoutstash.get(treepath, {}).keys():
				if layoutstash[treepath][colname].has_key(tvc.name):
					del layoutstash[treepath][colname][tvc.name]
		layout_overflowcells = layoutstash.get(treepath, {}).get(tvc.name, {})
		if not markup and not text:
			# current cell is empty, but redraw those cells which flow over to this one
			for layout_args in layout_overflowcells.values():
				self.draw_layout(*layout_args)
		else:
			if layout_overflowcells:
				# current cell is not empty so delete those layouts which would be drawn on it, if any
				del layoutstash[treepath][tvc.name]
			self.cr_txt.render(window, widget, background_area, cell_area, expose_area, flags)
	def on_activate(self, event, widget, path, background_area, cell_area, flags):
		return self.cr_txt.activate(event, widget, path, background_area, cell_area, flags)
	def on_start_editing(self, event, widget, path, background_area, cell_area, flags):
		ce = self.cr_txt.start_editing(event, widget, path, background_area, cell_area, flags)
		w = gtk.Window(gtk.WINDOW_TOPLEVEL)
		w.set_keep_above(True)
		w.set_modal(True)
		w.set_skip_taskbar_hint(True)
		w.set_transient_for(widget.get_ancestor(gtk.Window))
		w.set_decorated(False)
		frame = gtk.Frame(label = "Enter new value")
		frame.set_border_width(24)
		frame.set_shadow_type(gtk.SHADOW_IN)
		frame_inner = gtk.Frame()
		frame_inner.set_border_width(16)
		w.add(frame)
		frame.add(frame_inner)
		frame_inner.add(ce)
		w.show_all()
		add_key_binding(w, 'Escape', lambda *X: w.destroy())
		w.connect('destroy', lambda *X: w.destroy())
		ce.connect('remove-widget', lambda *X: w.destroy())
		ce.start_editing(event)

gobject.type_register(CellRendererTextOverflow)



def gtk_walk_descendant_widgets(w, cb, cb_data):
	stop = cb(w, cb_data)
	if stop:
		return
	if hasattr(w, 'get_children'):
		for child in w.get_children():
			gtk_walk_descendant_widgets(child, cb, cb_data)

class MenuItem(gtk.MenuItem):
	def get_label_widget(self):
		cb_data = {'label-widget': None}
		def cb(widget, cb_data):
			if isinstance(widget, gtk.Label):
				cb_data['label-widget'] = widget
				return True
		gtk_walk_descendant_widgets(self, cb, cb_data)
		return cb_data['label-widget']
		
	def set_markup(self, markup):
		self.set_label('.')
		self.get_label_widget().set_markup(markup)

class CheckMenuItem(gtk.CheckMenuItem, MenuItem):
	def __init__(self, label=None, markup=None, use_underline=False):
		super(self.__class__, self).__init__(label=label, use_underline=use_underline)
		if markup is not None:
			self.set_markup(markup)

class ImageMenuItem(gtk.ImageMenuItem, MenuItem):
	def __init__(self, stock_id=None, accel_group=None, label=None, markup=None, icon=None):
		assert not(label is not None and markup is not None), "label and markup arguments are mutually exclusive"
		super(self.__class__, self).__init__(stock_id=stock_id, accel_group=accel_group)
		if label is not None:
			self.set_label(label)
		if markup is not None:
			self.set_markup(markup)
		if icon is not None:
			self.set_icon(icon)
	def set_icon(self, icon):
		if not icon: return
		img = gtk.Image()
		if os.path.isfile(icon):
			width_px, height_px = gtk.icon_size_lookup(gtk.ICON_SIZE_MENU)[:]
			pixbuf = get_pixbuf_from_file_at_size(icon, width_px, height_px)
			img.from_pixbuf(pixbuf)
		elif icon.startswith('STOCK_'):
			img.set_from_stock(getattr(gtk, icon), gtk.ICON_SIZE_MENU)
		elif icon in gtk.stock_list_ids():
			img.set_from_stock(icon, gtk.ICON_SIZE_MENU)
		elif gtk.icon_theme_get_default().lookup_icon(icon, gtk.ICON_SIZE_MENU, 0) is not None:
			img.set_from_icon_name(icon, gtk.ICON_SIZE_MENU)
		else:
			width_px, height_px = gtk.icon_size_lookup(gtk.ICON_SIZE_MENU)[:]
			iconfile = find_icon_file(icon, width_px)
			if iconfile is None: return
			pixbuf = get_pixbuf_from_file_at_size(iconfile, width_px, height_px)
			img.set_from_pixbuf(pixbuf)
		self.set_image(img)


class TemporaryProperty(object):
	"""Context manager to temporarily set an object property and restore it on exit."""
	def __init__(self, getter, setter, tempval):
		assert callable(getter) or len(getter)==2
		assert callable(setter) or setter is () or len(setter)==2
		self.getter = getter
		self.setter = setter
		self.tempval = tempval
		self.original = None
	
	def _set(self, x):
		if callable(self.setter):
			self.setter(x)
		elif self.setter is ():
			setattr(self.getter[0], self.getter[1], x)
		else:
			setattr(self.setter[0] if self.setter[0] is not None else self.getter[0], self.setter[1], x)

	def __enter__(self):
		if callable(self.getter):
			self.original = self.getter()
		else:
			self.original = getattr(self.getter[0], self.getter[1])
		self._set(self.tempval)
		return self
	
	def __exit__(self, exc_type, exc_val, exc_tb):
		self._set(self.original)


class GtkThreadProtectedContext(object):
	def __init__(self, parent_context):
		self.parent_context = parent_context
	def __enter__(self):
		self.parent_context.enter()
		return self
	def __exit__(self, exc_type, exc_val, exc_tb):
		self.parent_context.leave_maybe()
		return False

class GtkThreadContext(object):
	def __init__(self, max_freeze_sec=None):
		self._entered = False
		self.max_freeze_sec = max_freeze_sec
		if self.max_freeze_sec is not None:
			self._last_enter = 0
			self.protected = GtkThreadProtectedContext(parent_context=self)
	def __enter__(self):
		if self.max_freeze_sec is None:
			self.do_enter()
		return self
	def do_enter(self):
		if not self._entered:
			gtk.threads_enter()
			self._entered = True
			self._last_enter = time.time()
	def __exit__(self, exc_type, exc_val, exc_tb):
		self.do_leave()
		return False  # don't ignore exceptions
	def do_leave(self):
		if self._entered:
			gtk.threads_leave()
			self._entered = False
	def leave_maybe(self):
		if self._last_enter + self.max_freeze_sec < time.time():
			self.do_leave()
	def enter(self):
		self.do_enter()

class NoGtkThreadContext(object):
	def __enter__(self):
		gtk.threads_leave()
		return self
	def __exit__(self, exc_type, exc_val, exc_tb):
		gtk.threads_enter()

class Thread(threading.Thread):
	def __init__(self, *params, **opts):
		is_daemon = None
		if 'daemon' in opts:
			is_daemon = opts['daemon']
			del opts['daemon']
		super(Thread, self).__init__(*params, **opts)
		if is_daemon:
			self.setDaemon(is_daemon)

class SubprocessError(Exception):
	def __init__(self, typ=None, code=None, details=''):
		super(SubprocessError, self).__init__()
		self.type = typ
		self.code = code
		self.details = details

def spawn_subprocess(command_with_args, *popen_args, **popen_options):
	err = SubprocessError()
	command_str = command_with_args if isinstance(command_with_args, basestring) else subprocess.list2cmdline(command_with_args)
	try:
		proc = subprocess.Popen(command_with_args, *popen_args, **popen_options)
	except Exception as exc:
		err.type = "exception"
		err.code = exc.__class__.__name__
		err.details = 'command: '+command_str
		err.details += "\n" + traceback.format_exc()
		if isinstance(exc, OSError):
			err.type = "status code"
			err.code = exc.errno
			err.details = exc.strerror + "\n" + err.details
			if exc.filename is not None: 
				err.details = "file: " + exc.filename + "\n" + err.details
		raise err
	else:
		proc.command_str = command_str
	return proc

def wait_subprocess(proc):
	err = SubprocessError()
	stderr = proc.stderr.read()
	if stderr:
		print(stderr, file=sys.stderr)
	proc.stderr.close()
	proc.wait()
	err.details = 'command: ' + proc.command_str + '\n'
	err.details += 'subprocess.Popen().returncode: ' + str(proc.returncode) + '\n'
	if stderr:
		err.details += 'stderr:\n' + stderr
	else:
		err.details += '(no stderr)'
	if proc.returncode != 0:
		err.type = "status code" if proc.returncode > 0 else "signal"
		err.code = abs(proc.returncode)
		raise err
	return proc

def ErrorMessage(message_markup, title=None, details=None):
	dlg = gtk.MessageDialog(parent=main_app.main_win, flags=(gtk.DIALOG_MODAL | gtk.DIALOG_DESTROY_WITH_PARENT), type=gtk.MESSAGE_ERROR, buttons=gtk.BUTTONS_OK)
	dlg.set_title("Error" if title is None else title)
	dlg.set_markup(message_markup)
	if details is not None:
		dlg.set_resizable(True)
		carea = dlg.get_content_area()
		carea.pack_start(Scrollable(Label(markup='<tt>'+glib.markup_escape_text(details)+'</tt>')), True, True)
	dlg.get_widget_for_response(gtk.RESPONSE_OK).connect('clicked', lambda btn, dlg: dlg.destroy(), dlg)

	dlg.connect('map-event', lambda *X: PropertyPersistor(dlg, 'error-dialog', [
		( 'geometry', 'configure-event', lambda wdg, evt: [evt.width, evt.height], lambda wdg, value: wdg.resize(*value) ),
		( 'position', 'configure-event', lambda wdg, evt: wdg.get_position()[:],   lambda wdg, value: wdg.move(*value) ),
	]).apply_saved_properties())

	dlg.show_all()
	dlg.run()
	return dlg



def split_command_args(cmd_str):
	return re.split(r'\s+', cmd_str)

def populate_row_context_menu(menu, items, macros):
	# TODO support submenus
	for definition in items:
		icon, label_template, command_template = [field.replace('\\:', ':') for field in re.split(r'(?<!\\):', definition, maxsplit=2)]
		menuitem_label = Template(label_template).render(**macros)
		if menuitem_label != '':
			enabled = True
			if menuitem_label.startswith(' '):
				menuitem_label = menuitem_label[1:]
				enabled = False
			mi = ImageMenuItem(label=menuitem_label, icon=icon)
			mi.set_sensitive(enabled)
			command = Template(command_template).render(**macros)
			mi.set_data('command_args', split_command_args(command))
			mi.connect('activate', on_context_menu_item_activate, menu)
			menu.append(mi)
	menu.show_all()

def gen_row_data(treeview, c_treepath, tv_col):
	return {
		'col': None if tv_col is None else tv_col.name,
		'row': {} if c_treepath is None else treeview.get_model()[c_treepath].as_dict(),
		'selected_rows': [treeview.get_model()[treepath].as_dict() for treepath in treeview.get_selection().get_selected_rows()[1]],
	}

def on_table_row_context_menu_open(treeview, popup_menu, c_treepath, tv_col, cell_x, cell_y):
	row_data = gen_row_data(treeview, c_treepath, tv_col)
	n_selected = len(row_data['selected_rows'])
	popup_menu.set_data('row-data', row_data)
	macros = {
		'n_selected': n_selected,
		'column': row_data['col'],
		'cell': row_data['row'][row_data['col']],
		'row': row_data['row'],
	}
	# add user-defined menu items
	populate_row_context_menu(popup_menu, cliargs.context_menu, macros)
	
	# add gtabdata-specific menu items:
	if popup_menu.get_children():
		popup_menu.append(gtk.SeparatorMenuItem())
	mi = ImageMenuItem(label="Copy cell", icon=gtk.STOCK_COPY)
	mi.connect('activate', on_context_menu_copy, popup_menu, 'cell')
	popup_menu.append(mi)
	mi = ImageMenuItem(label="Copy row as JSON", icon=gtk.STOCK_COPY)
	mi.connect('activate', on_context_menu_copy, popup_menu, 'row-as-json')
	popup_menu.append(mi)
	if n_selected > 1:
		mi = ImageMenuItem(label="Copy selection as JSON", icon=gtk.STOCK_COPY)
		mi.connect('activate', on_context_menu_copy, popup_menu, 'selection-as-json')
		popup_menu.append(mi)
	mi = ImageMenuItem(label="Refresh table data", icon=gtk.STOCK_REFRESH)
	mi.connect('activate', lambda mi: main_app.load_table_async())
	popup_menu.append(mi)
	return False

def on_context_menu_item_activate(mi, menu):
	row_data = menu.get_data('row-data')
	command_args = mi.get_data('command_args')
	run_system_command_async(command_args, row_data)

def on_context_menu_copy(mi, menu, what):
	row_data = menu.get_data('row-data')
	if what == 'cell':
		text = row_data['row'][row_data['col']]
	elif what == 'row-as-json':
		text = json.dumps(row_data['row'])
	elif what == 'selection-as-json':
		text = json.dumps(row_data['selected_rows'])
	else:
		raise ValueError()
	gtk.Clipboard().set_text(text)

def on_table_row_activated(treeview, c_treepath, tv_col):
	if cliargs.activate_command is not None:
		command_template = cliargs.activate_command
		macros = {
			'row': treeview.get_model()[c_treepath].as_dict(),
		}
		command = Template(command_template).render(**macros)
		run_system_command_async(split_command_args(command), gen_row_data(treeview, c_treepath, tv_col))

def run_system_command_async(command_with_args, input_object):
	Thread(target=run_system_command, args=(command_with_args, json.dumps(input_object)), daemon=True).start()

def run_system_command(command_with_args, input_text):
	try:
		proc = spawn_subprocess(command_with_args, shell=False, stdin=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True)
		proc.stdin.write(input_text)
		proc.stdin.close()
		wait_subprocess(proc)
	except SubprocessError as err:
		with GtkThreadContext():
			ErrorMessage("Command failed with %s: <tt>%s</tt>\nDetails:" % (err.type, err.code), title="gTabData: execution error", details=err.details)


def tabdata(rawline, n_fields=0):
	def unescape_td_sequence(s):
		"""only meant for backslash-t, backslash-n, backslash-r, backslash-e and double-blackslash inputs."""
		if s == '\\e': return '\x1B'
		else: return eval('"'+s+'"')
	cells = [re.sub(r'\\[tnre\\]', lambda match: unescape_td_sequence(match.group(0)), cell) for cell in rawline.rstrip('\n').split('\t', n_fields-1)]
	if n_fields > 0:
		cells = cells + [''] * (n_fields-len(cells))
	return cells


def merge_ordering(old_items, new_items):
	result = []
	for patchline in difflib.ndiff(old_items, new_items):
		op, item = patchline[0], patchline[2:]
		if op in ('+', ' ') or (op == '-' and item not in new_items):
			result.append(item)
	return result

def treemodel_find_row(model, treepath, treeiter, cb_data):
	if model[treepath][cb_data['column-name']] == cb_data['value']:
		cb_data['treepath'] = treepath
		return True

def get_path_by_cell(model, search_column, search_content):
	search_data = {'column-name': search_column, 'value': search_content, 'treepath': None}
	model.foreach(treemodel_find_row, search_data)
	return search_data['treepath']



def parse_cli_args():
	parser = argparse.ArgumentParser(description='gTabData - GTK Tabular Data viewer', formatter_class=argparse.RawDescriptionHelpFormatter)
	parser.add_argument('--title', type=str, default='gTabData', help='Window title text')
	parser.add_argument('--appname', type=str, default='gtabdata', help='Custom application name to operate as')
	parser.add_argument('--icon', type=str, default='text-spreadsheet', help='Window icon file or symbolic name')
	data_group = parser.add_mutually_exclusive_group()
	data_group.add_argument('--data-command', type=str, metavar='COMMAND', help='The command which produces the tabular data to be shown')
	data_group.add_argument('--data-script', type=str, metavar='SCRIPT', help='Shell command(s) to produce tabular data')
	data_group.add_argument('--db-query', type=str, help='Database query to load data from')
	parser.add_argument('--db-connection', type=str, help='Database connection string, for supported DSN see "sqlalchemy" python module.')
	key_group = parser.add_mutually_exclusive_group()
	key_group.add_argument('--key-field', type=str, default=None, metavar='COLUMN')
	key_group.add_argument('--auto-key-field', action='store_true', default=False, help='Default key field is the first column in the input data.')
	parser.add_argument('--activate-command', type=str, metavar='COMMAND', help='System command to run when double clicked on a row.')
	parser.add_argument('--context-menu', action='append', default=[], type=str, metavar='ICON:LABEL:COMMAND', help='Menu item definitions for rows context menu.')
	parser.add_argument('--auto-refresh-interval', type=float, metavar='SEC')
	parser.add_argument('--inotify-refresh', type=str, metavar='FILE', help='')  # TODO
	parser.epilog = '''
COMMAND
	The COMMAND option parameter is a jinja2 template, after rendered, split by whitespaces into command and arguments, no quoting or escaping is supported.
	Then the command is run as a system command, not in shell.
	For available jinja2 variables, see LABEL paragraph below.
	A JSON object is passed to the command's STDIN with these keys:
	- row: an object itself containing all fields (as object keys) and cells (as values) of the activated row
	- col: column's name which the context menu is opened in
	- selected_rows: list of all the selected rows' fields
ICON is one of these:
	- image file path
	- Gtk stock icon constant, starting with "STOCK_"
	- icon name as defined in the current Gtk icon theme
	- basename of an image file in the common system icon directories
LABEL is a jinja2 template rendered to the menu item label, supporting these variables:
	- n_selected: number of selected rows
	- cell: the cell's text content on which the context menu is opened
	- column: the column name in which the context menu is opened
	- row: a dict holding the focused/activated row's fields
	Literal ":" should be escaped by backslash.
	If the rendered LABEL is empty string, the menu item won't be shown.
	If the rendered LABEL starts with a space, the menu item is shown disabled.
'''
	return parser.parse_args()


cliargs = parse_cli_args()
APPNAME = cliargs.appname


class GTabData(object):
	def configure(self):
		self.tabdata_key_field = None

		self.main_win = Window({'name': 'window.main', 'gtk-args': [], 'default-size': ()})
		self.window_signalmanager = GSignalHandlerManager(self.main_win)
		self.window_signalmanager.connect('delete-event', lambda *X: self.on_exit())
		self.window_signalmanager.connect_once('map-event', lambda w, e: self._on_startup())
		add_key_binding(self.main_win, 'F5', lambda *X: self.load_table_async())

		self.main_table = TreeView(None)
		self.main_win.add(Scrollable(self.main_table))
		self.main_table.connect('row-activated', on_table_row_activated)
		self.main_table.connect('menu-popup', on_table_row_context_menu_open)
		self.main_table.connect('column-added', self.on_column_added)

		self.proppersist_table = PropertyPersistor(self.main_table, 'main_table', [
			('columns-order',  'columns-changed',           lambda tv: merge_ordering(self.proppersist_table.props.get('columns-order') or [], [col.name for col in tv.get_columns()]), self.restore_columns_order),
			('hidden-columns', 'column-visibility-changed', lambda tv, tvc: [col.name for col in tv.get_columns() if not col.get_visible()], self.restore_hidden_columns),
			('column-width',   'column-width-changed',      lambda tv, tvc, tvc_width: dict([(col.name, col.get_width()) for col in tv.get_columns()]), self.restore_columns_width),
			('sort-column',    'sort-by-column-changed',    lambda tv, tvc: tvc.name, self.restore_sortby_column),
			('sort-order',     'column-sort-order-changed', lambda tv, tvc: tvc.get_sort_order().value_nick, None),
		])
		if cliargs.key_field is not None or cliargs.auto_key_field:
			self.proppersist_table.add_properties([('selected-rows', 'selection-change', lambda tv, sel_rows: [row[self.tabdata_key_field] for row in sel_rows], self.restore_selection)])
		
	def run(self):
		self.main_win.show_all()

	def _on_startup(self):
		self.load_table_async()
	
	def load_table_async(self):
		Thread(target=self.load_table, daemon=True).start()
	
	def load_table(self):
		if cliargs.db_query:
			import sqlalchemy

			db_engine = sqlalchemy.create_engine(cliargs.db_connection, execution_options={'stream_results':True})
			db_conn = db_engine.connect()
			db_result = db_conn.execute(cliargs.db_query)

			columns = [(col, unicode) for col in db_result.keys()]
			self.load_columns(columns)
			data_generator = ((None, row) for row in db_result)
			self.load_data(data_generator)
		
		elif cliargs.data_command or cliargs.data_script:
			if cliargs.data_command:
				command = split_command_args(cliargs.data_command)
				in_shell = False
			elif cliargs.data_script:
				command = cliargs.data_script
				in_shell = True
			else:
				raise ValueError()

			try:
				proc = spawn_subprocess(command, shell=in_shell, stdin=open(os.devnull, 'r'), stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True)
				td_header = tabdata(proc.stdout.readline())
				columns = [(col, unicode) for col in td_header]
				self.load_columns(columns)
				data_generator = ((None, tabdata(line, n_fields=len(columns))) for line in iter(proc.stdout.readline, ''))
				self.load_data(data_generator)
				proc.stdout.close()
				wait_subprocess(proc)
			except SubprocessError as err:
				with GtkThreadContext():
					ErrorMessage("Command failed with %s: <tt>%s</tt>\nDetails:" % (err.type, err.code), title="gTabData: execution error", details=err.details)
		
		with GtkThreadContext():
			self.after_load_table()
	
	def after_load_table(self):
		with TemporaryProperty((self.proppersist_table, 'active'), (), False):
			self.proppersist_table.apply_saved_properties()
			# apply saved sorting
			self.main_table.resort()
			# auto size newly learned columns
			self._auto_size_new_columns()
			# resize the app window if not yet resized by the user
			gobject.idle_add(self._window_initial_resize)
	
	def _window_initial_resize(self):
		if not self.main_win.property_persistor.props.get('geometry'):
			tv_width, tv_height = self.main_table.size_request()
			scr = self.main_win.get_screen()
			self.main_win.resize(min(tv_width, scr.get_width()), min(tv_height, scr.get_height()))
	
	def _auto_size_new_columns(self):
		self.main_table.columns_autosize([col for col in self.main_table.get_columns() if not col.get_width() or col.get_width() == 1])

	def load_columns(self, columns):
		if cliargs.auto_key_field:
			self.tabdata_key_field = columns[0][0]
			print("info: Taking '%s' as key field." % self.tabdata_key_field, file=sys.stderr)
		
		if self.main_table.get_model() is None or columns != self.main_table.get_model().get_columns():
			with GtkThreadContext():
				with TemporaryProperty((self.proppersist_table, 'active'), (), False):
					self.main_table.set_model(TreeStore(*columns))
					self.main_table.set_columns([(col[0], col[0], 'text', idx) for idx, col in enumerate(columns)])
		
		if not cliargs.auto_key_field and cliargs.key_field is not None:
			if cliargs.key_field not in [col[0] for col in columns]:
				print("warning: Field '%s' is not in the input." % cliargs.key_field, file=sys.stderr)
			else:
				self.tabdata_key_field = cliargs.key_field

	def load_data(self, iterator):
		with GtkThreadContext():
			gdkwin = self.main_win.window
			gdkwin.set_cursor(gtk.gdk.Cursor(gdkwin.get_display(), gtk.gdk.WATCH))

			model = self.main_table.get_model()
			if self.tabdata_key_field is None:
				model.clear()
		
		existing_records_keys = []
		with GtkThreadContext(max_freeze_sec=0.2) as gtkcontext:
			for treepath, row in iterator:
				with gtkcontext.protected:
					record_key = None
					existing_record_path = None
					if self.tabdata_key_field is not None:
						record_key = row[model.get_column_num(self.tabdata_key_field)]
						existing_record_path = get_path_by_cell(model, self.tabdata_key_field, record_key)
					if existing_record_path is None:
						model.append(treepath, row)
					else:
						for col_num, col_data in enumerate(row):
							model[existing_record_path][col_num] = col_data
					if self.tabdata_key_field is not None:
						existing_records_keys.append(record_key)

		if self.tabdata_key_field is not None:
			with GtkThreadContext():
				def remove_invalid_rows(model, treepath, treeiter, cb_data):
					if model[treepath][cb_data['tabdata_key_field']] not in cb_data['existing_records_keys']:
						del model[treepath]
				model.foreach(remove_invalid_rows, {'existing_records_keys': existing_records_keys, 'tabdata_key_field': self.tabdata_key_field})

		with GtkThreadContext():
			gdkwin.set_cursor(None)

	def on_column_added(self, tv, tvc):
		width = self.proppersist_table.props.get('column-width', {}).get(tvc.name, None)
		if width > 1:
			tvc.set_fixed_width(width)
		if tvc.name in self.proppersist_table.props.get('hidden-columns', []):
			tvc.set_visible(False)

	def restore_columns_width(self, tv, cols_width):
		for colname, width in cols_width.iteritems():
			if width > 1:
				try:
					tv.get_column_by_name(colname).set_fixed_width(width)
				except TreeView.ColumnNotFoundException:
					pass
	
	def restore_sortby_column(self, tv, colname):
		try:
			tv.set_sortby_column_by_name(colname)
		except TreeView.ColumnNotFoundException:
			pass
		else:
			sort_order = self.proppersist_table.props.get('sort-order')
			if sort_order: tv.get_sortby_column().set_sort_order(getattr(gtk, 'SORT_'+sort_order.upper()))
		
	def restore_hidden_columns(self, tv, columns):
		for colname in columns:
			try:
				tv.get_column_by_name(colname).set_visible(False)
			except TreeView.ColumnNotFoundException:
				pass

	def restore_columns_order(self, tv, columns):
		preceding_col = None
		for colname in columns:
			try:
				col = tv.get_column_by_name(colname)
			except TreeView.ColumnNotFoundException:
				pass
			else:
				tv.move_column_after(col, preceding_col)
				preceding_col = col
	
	def restore_selection(self, tv, selected_records_keys):
		last_treepath = None
		if self.tabdata_key_field is not None:
			for key in selected_records_keys:
				treepath = get_path_by_cell(tv.get_model(), self.tabdata_key_field, key)
				if treepath is not None:
					tv.get_selection().select_path(treepath)
					last_treepath = treepath
		if last_treepath is not None:
			tv.scroll_to_cell(last_treepath)

	def on_exit(self):
		self.proppersist_table.active = False
		gtk.main_quit()


main_app = GTabData()
main_app.configure()
main_app.main_win.title = Template(cliargs.title).render({'env': os.environ})
main_app.main_win.set_icon_from_any(cliargs.icon)
main_app.run()
gtk.main()
