#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import re
from datetime import datetime
from icalendar import Calendar


def astz(dt, tz):
	if hasattr(dt, 'astimezone'):
		return dt.astimezone(tz)
	return dt


def esctd(raw):
	return re.sub(r'[\t\n\r\\]', lambda m: '\\'+repr(m.group(0))[2], raw).replace(r'', '\\e')


def main():
	cal = Calendar.from_ical(sys.stdin.read())
	
	user_tz = datetime.now().astimezone().tzinfo
	dt_fmt = '%Y-%m-%d %H:%M (%b %-d, %a) %Z'
	
	print('\t'.join(['START', 'END', 'ALL-DAY', 'STATUS', 'BUSYSTATUS', 'TRANSP', 'SUMMARY', 'LOCATION', 'COMMENT', 'DESCRIPTION']))
	
	for event in cal.walk('vevent'):
		dt_from = astz(event.get('dtstart').dt, user_tz)
		dt_to = astz(event.get('dtend').dt, user_tz)
		time_from = datetime.strftime(dt_from, dt_fmt)
		time_to = datetime.strftime(dt_to, dt_fmt)
		
		allday = 'ALL-DAY' if event.get('X-MICROSOFT-CDO-ALLDAYEVENT', '').upper() == 'TRUE' else ''
		
		print('\t'.join([esctd(cell) for cell in 
			[time_from, time_to, allday] + 
			[event.get(field, '') for field in 
				['status', 'X-MICROSOFT-CDO-BUSYSTATUS', 'transp', 'summary', 'location', 'comment', 'description']
			]
		]))

main()
