#!/usr/bin/env perl

do '/usr/lib/tool/perl5/tabdata/common.pl' or die "$@";

@Filter = ();

while($arg = shift @ARGV)
{
	if($arg =~ /^([^-].*)(==|!=|<=|>=|<|>|=~|!~| (?:eq|ne|gt|lt) )(.*)$/)
	{
		my ($field, $operator, $value) = ($1, $2, $3);
		$operator =~ s/ //g;
		push @Filter, {'field'=>$field, 'operator'=>$operator, 'value'=>$value,};
	}
	else
	{
		die "$0: unknown option: $arg\n";
	}
}

process_header(scalar <STDIN>);

unless($OptNoHeader)
{
	print $HeaderLine.$/;
}

while($line = <STDIN>)
{
	chomp $line;
	
	@Field = split $FS, $line;
	
	$pass = 1;
	
	for my $filter (@Filter)
	{
		my $left_data = $Field[$Header{$filter->{'field'}}];
		my $right_data = $filter->{'value'};
		my $operator = $filter->{'operator'};
		my $left_code = "\$left_data";
		my $right_code = "\$right_data";
		$right_code = "/$right_code/" if $operator ~~ ['=~', '!~'];
		unless(eval "$left_code $operator $right_code")
		{
			$pass = 0;
			last;
		}
	}
	
	if($pass)
	{
		print $line.$/;
	}
}
