#!/usr/bin/env perl

=pod

=head1 NAME

td-keepheader - Plug a non header-aware program in the tabular-data processing pipeline

=head1 USAGE

td-keepheader [--] <COMMAND> [<ARGS>]

=head1 EXAMPLE

ls -l | td-trans-ls | td-select NAME +REST | td-keepheader sort | tabularize

=cut

no if ($] >= 5.018), 'warnings' => 'experimental::smartmatch';
do '/usr/lib/tool/perl5/tabdata/common.pl' or die "$@";

die "$0: no COMMAND given\n" unless @ARGV;

$header = sys_read_line();

exec @ARGV;
die "$!: @ARGV\n";
