#!/usr/bin/env perl

=pod

=head1 NAME

td-nup - Transform lines of text into tabluar data by unroll N lines into a row

=head1 OPTIONS

=over 4

=item -n I<NUM>

=item -E, --no-escape

Don't escape text.
By default, td-nup(1) assumes input lines are raw text data,
thus need to escape tabular data special chars in them.

=back

=cut

$OptNup = undef;
$OptEscape = 1;
%OptionDefs = (
	'n=i' => \$OptNup,
	'E|no-escape' => sub { $OptEscape = 0; },
);

no if ($] >= 5.018), 'warnings' => 'experimental::smartmatch';
do '/usr/lib/tool/perl5/tabdata/common.pl' or die "$@";


$n = 0;
@record = ();
while(not eof STDIN)
{
	$_ = <STDIN>;
	chomp;
	push @record, $OptEscape ? escape_tabdata($_) : $_;
	$n++;
	if($n == $OptNup)
	{
		output_record(@record);
		$n = 0;
		@record = ();
	}
}

if(@record)
{
	output_record(@record);
}
