#!/usr/bin/env perl

=pod

=head1 NAME

td-pivot - Switch columns for rows in tabular data

=head1 SYNOPSIS

td-pivot

=head1 CAVEAT

Must read and buffer the whole STDIN before output any data,
so inpractical on large data.

=cut

no if ($] >= 5.018), 'warnings' => 'experimental::smartmatch';
do '/usr/lib/tool/perl5/tabdata/common.pl' or die "$@";


@data = ();
$max_col = 0;

while(my @row = read_record(\*STDIN))
{
	my $cols = scalar @row - 1;
	$max_col = $cols if $cols > $max_col;
	push @data, [@row];
}

for my $cnum (0..$max_col)
{
	print join $FS, map {$_->[$cnum]} @data;
	print $RS;
}
