#!/usr/bin/env perl

=pod

=head1 NAME

td-select - Show only the specified columns from the input tabular data stream.

=head1 USAGE

td-select [<OPTIONS>] [--] [-]<COLUMN-1> [[-]<COLUMN-2> [...]]

=head1 OPTIONS

=over 4

=item -H, --no--header

do not show headers

=back

=head1 DESCRIPTION

<COLUMN> is either a column name, optionally prefixed with hyphen,
in which case the given column will not be shown,
or one of these special keywords:
  +ALL    - all columns
  +REST   - the rest of columns not given yet in the parameter list

=head1 EXAMPLE

  ls -l | td-trans-ls | td-select -- NAME +REST -INODE -LINKS -MAJOR -MINOR

=cut

do '/usr/lib/tool/perl5/tabdata/common.pl' or die "$@";

process_header(scalar <STDIN>);

@Columns = ();

while($arg = shift @ARGV)
{
	if($arg =~ /^-(.+)$/)
	{
		my $except_column = $1;
		@Columns = grep {$_ ne $except_column} @Columns;
	}
	elsif($arg eq '+ALL')
	{
		push @Columns, @Header;
	}
	elsif($arg eq '+REST')
	{
		push @Columns, grep {not $_ ~~ @Columns} @Header;
	}
	elsif($arg =~ /^(.+)$/)
	{
		push @Columns, $1;
	}
	else
	{
		die "$0: unknown option: $arg\n";
	}
}

# display selected headers
unless($OptNoHeader)
{
	@Output = ();
	for my $col (@Columns)
	{
		push @Output, defined $Header{$col} ? $Header[$Header{$col}] : '';
	}
	print join($FS, @Output).$/;
}


# display selected data fields
while($line = <STDIN>)
{
	chomp $line;
	
	@Input = split $FS, $line;
	@Output = ();
	
	for my $col (@Columns)
	{
		push @Output, defined $Header{$col} ? $Input[$Header{$col}] : '';
	}
	
	print join($FS, @Output).$/;
}
