#!/usr/bin/env perl


=pod

=head1 NAME

td-trans - Transform whitespace-delimited into TAB-delimited lines ignoring sorrounding whitespace.

=cut

no if ($] >= 5.018), 'warnings' => 'experimental::smartmatch';
do '/usr/lib/tool/perl5/tabdata/common.pl' or die "$@";

while(my $line = <STDIN>)
{
	chomp $line;
	$line =~ s/^\s*//g;
	$line =~ s/\s*$//g;

	if($. == 1)
	{
		# the first line considered header,
		# and the number of fields dictates (at most) how many fields are there in the rest of the stream.
		$num_of_fields = scalar split /\s+/, $line;
	}
	
	my @Fields = split /\s+/, $line, $num_of_fields;
	
	print join($FS, @Fields).$RS;
}
