#!/usr/bin/env perl

=pod

=head1 NAME

td2html - Transform tabular data stream into a HTML table.

=head1 SYNOPSIS

td2html

=head1 DESCRIPTION

Takes a tabular data stream on STDIN and outputs a HTML table
enclosed in C<< <table>...</table> >> tags.

=cut

no if ($] >= 5.018), 'warnings' => 'experimental::smartmatch';
do '/usr/lib/tool/perl5/tabdata/common.pl' or die "$@";

sub html_escape
{
	my $str = shift;
	$str =~ s/[><&\t]/'&' . {'>'=>'gt', '<'=>'lt', '&'=>'amp', "\t"=>'Tab'}->{$&} . ';'/eg;
	$str =~ s/\n/<br>/g;
	return $str;
}

print "<table border=\"1\">\n";

print "<tr>";
print "<th>";
$header = <STDIN>;
chomp $header;
print join("</th><th>", map {html_escape(unescape_tabdata($_))} split $FS, $header);
print "</th>";
print "</tr>\n";

while($row = <STDIN>)
{
	chomp $row;
	print "<tr>";
	print "<td>";
	print join("</td><td>", map {html_escape(unescape_tabdata($_))} split $FS, $row);
	print "</td>";
	print "</tr>\n";
}

print "</table>";
