#!/usr/bin/env perl

=pod

=head1 NAME

td2mrkv - Transform tabular data into multi-record key-value (MRKV) format.

=head1 EXAMPLE

getent passwd | tr : "\t" | td-add-headers USER PW UID GID GECOS HOME SHELL | td-select +ALL -PW | td2mrkv

=cut

do '/usr/lib/tool/perl5/tabdata/common.pl' or die "$@";


process_header(scalar <STDIN>);


while($line = <STDIN>)
{
	chomp $line;
	
	@Field = split $FS, $line;
	
	for my $idx (0..$#Header)
	{
		printf "%s\t%s\n", $Header[$idx], $Field[$idx];
	}
	
	print "\n";
}
