#! perl

sub on_start {
   my ($self) = @_;
   $self->{focused} = 0;
   ()
}

sub on_focus_in {
	my ($self) = @_;
	$self->{focused} = 1;
}

sub on_focus_out {
	my ($self) = @_;
	$self->{focused} = 0;
}

sub on_bell {
	my ($self) = @_;
	$self->set_urgency(1) if not $self->{focused};
	()
}
