#!/bin/bash

# Usage:
# execfuse ./autosshfs ~/mnt/ssh -o fsname=autosshfs.$USER,allow_root

# You have to set this in ~/.ssh/config:
#   ControlMaster auto
#   ControlPath ~/.ssh/ctrl/%r@%n(%h):%p.sock

shopt -s nullglob

operation=${0##*/}

connections_subdir=${EXECFUSE_MOUNTPOINT##*/}
attr_parentdir="ino=1 mode=drwxr-xr-x nlink=2 uid=0 gid=0 rdev=0 size=0 blksize=512 blocks=2 atime=0 mtime=0 ctime=0"
attr_rootdir="ino=1 mode=drwxr-xr-x nlink=2 uid=$UID gid=0 rdev=0 size=0 blksize=512 blocks=2 atime=0 mtime=0 ctime=0"
attr_entry="ino=1 mode=drwx------ nlink=1 uid=$UID gid=0 rdev=0 size=0 blksize=512 blocks=2 atime=0 mtime=0 ctime=0"
attr_alias="ino=1 mode=drwx------ nlink=1 uid=$UID gid=0 rdev=0 size=0 blksize=512 blocks=2 atime=0 mtime=0 ctime=0"


declare -A Conn
read_connections()
{
	if [ ${#Conn[@]} = 0 ]
	then
		reread_connections
	fi
}
reread_connections()
{
	local file name
	Conn=()
	for file in ~/.ssh/ctrl/*.sock
	do
		name=${file##*/}
		name=${name%.*}
		Conn[$name]=1
	done
}
get_host_alias()
{
	if [[ $1 =~ @(.+)\( ]]
	then
		echo "${BASH_REMATCH[1]}"
	fi
}

lock_nb()
{
	_lock -n "$@"
}

lock()
{
	_lock '' "$@"
}

_lock()
{
	local dir="/tmp/autosshfs.$USER"
	local flag=$1
	shift
	local conn=$1
	shift
	mkdir -p -m 0700 "$dir"
	flock -x $flag "$dir/$conn" "$@"
}

mount_sshfs_async()
{
	local conn=$1
	local port=$2
	local user=$3
	local host=$4
	local target=$5
	lock_nb "mount+$conn" setsid sshfs -o Port=$port,ControlMaster=no,transform_symlinks,reconnect "$user@$host:/" "$target" >/dev/null 2>&1 &
	# -o sftp_server='sudo /usr/lib/openssh/sftp-server'
}


if [ "$operation" = getattr ]
then
	if [ "$1" = / ]
	then
		printf "$attr_rootdir"
		exit 0
	else
		read_connections
		for conn in "${!Conn[@]}"
		do
			if [ "$1" = "/$conn" ]
			then
				printf "$attr_entry"
				exit 0
			else
				hostalias=`get_host_alias "$conn"`
				if [ "$1" = "/$hostalias" ]
				then
					printf "$attr_alias"
					exit 0
				fi
			fi
		done
		exit 1
	fi

elif [ "$operation" = readdir ]
then
	# first umount all dead connections
	cat /proc/mounts |\
	while read -r dev mp rest
	do
		if [[ $mp =~ ^(.+)/([^/]+)$ ]]
		then
			dir=${BASH_REMATCH[1]}
			subdir=${BASH_REMATCH[2]}
			if [ "$dir" = "$EXECFUSE_MOUNTPOINT" ]
			then
				read_connections
				if [ -z "${Conn[$subdir]}" ]
				then
					lock_nb "umount+$subdir" setsid fusermount -u -z "$mp" >/dev/null 2>&1 &
				fi
			fi
		fi
	done
	
	# list directories to each ssh connection when listing the root directory
	if [ "$1" = / ]
	then
		printf "$attr_rootdir .\0"
		printf "$attr_parentdir ..\0"
		
		read_connections
		for conn in "${!Conn[@]}"
		do
			printf "$attr_entry %s\0" "$conn"
			hostalias=`get_host_alias "$conn"`
			ln -snf "$connections_subdir/$conn" "$EXECFUSE_MOUNTPOINT/../$hostalias"
		done
		
		exit 0
	
	# when listing a subdirectory, mount the corresponding sshfs under it.
	# and return async, so you need to chdir to the directory again to get the actual content.
	else
		printf "$attr_entry .\0"
		printf "$attr_rootdir ..\0"
		
		read_connections
		for conn in "${!Conn[@]}"
		do
			if [ "/$conn" = "$1" ]
			then
				if [[ $conn =~ ^([^@]+)@([^\(]+)\([^\)]+\):([0-9]+) ]]
				then
					user=${BASH_REMATCH[1]}
					host=${BASH_REMATCH[2]}
					port=${BASH_REMATCH[3]}
					
					mount_sshfs_async "$conn" "$port" "$user" "$host" "$EXECFUSE_MOUNTPOINT$1"
					exit 0
				fi
			fi
		done
		
		exit 1
	fi
fi

