#!/bin/bash

set -u

directory=$1

echo "----" >&2
echo "Performing repo management commands..." >&2

(
set -e
set -o pipefail

GIT_DIR="$directory" git show repo-mgmt:access |\
while read -r line
do
	case "$line" in
	(public)
		echo "Making '$directory' public..." >&2
		chmod o+rx "$directory"
		;;
	(private)
		echo "Making '$directory' private..." >&2
		setfacl -b "$directory"
		chmod g-rwx,o-rwx "$directory"
		;;
	(default)
		# leave permissions as they are set at the beginning
		true
		;;
	(delete)
		echo "Deleting '$directory'..." >&2
		rm -rf --one-file-system "$directory"
		;;
	(*)
		echo "Unknown directive: '$line'" >&2
		;;
	esac
done
)

(
set -e
set -o pipefail

default_branch=$(GIT_DIR="$directory" git show repo-mgmt:default-branch)
if [ -n "$default_branch" ]
then
	echo "Setting default branch to '$default_branch'..." >&2
	GIT_DIR="$directory" git symbolic-ref HEAD refs/heads/"$default_branch"
fi
)

(
set -e
set -o pipefail

description=$(GIT_DIR="$directory" git show repo-mgmt:description)
if [ -n "$description" ]
then
	echo "Updating repo description..." >&2
	echo "Previous description was:" >&2
	cat "$directory/description" | perl -pe 's/^\r?\n$//; s/^(.)/  $1/; $last = $_; END { print "\n" unless $last =~ /\n/; }' >&2
	printf %s "$description" > "$directory/description"
fi
)

errstatus=$?
echo "Repo management commands are over." >&2
echo "----" >&2
exit $errstatus
