#!/bin/bash

if [ -n "$ZERONET_DATA" -a ! -d "$ZERONET_DATA" ]
then
	echo "ZERONET_DATA is not a directory." >&2
	exit 1
fi

if [ -n "$ZERONET_URL" ] && ! expr "$ZERONET_URL" : '.*://' >/dev/null
then
	echo "ZERONET_URL does not seem to be an url." >&2
	exit 1
fi

