#!/bin/bash

EPERM=1
ENOENT=2
EIO=5
EAGAIN=11
EACCESS=13
EBUSY=16
EEXIST=17
EINVAL=22
EFBIG=27
ENOSPC=28
ESPIPE=29
ENOSYS=38
ENOTEMPTY=39
EOPNOTSUPP=95

#set -x exec 2>>/tmp/d

fmode=-rw-r--r--
dmode=drwxr-xr-x
lmode=lrwxrwxrwx
GID=0
mtime=''

if [ -z "$ZERONET_URL" ]
then
	ZERONET_URL="http://localhost:43110"
fi


print_entry_dir()
{
	mode=$dmode print_entry "$@"
}

print_entry_file()
{
	mode=$fmode print_entry "$@"
}

print_entry_symlink()
{
	mode=$lmode print_entry "$@"
}

print_entry()
{
	echo -ne "ino=1 mode=$mode nlink=2 uid=$UID gid=$GID rdev=0 size=0 blksize=512 blocks=0 atime=0 mtime=${mtime:-0} ctime=0${1:+ $1\0}"
}

get_zeronet_file()
{
	local nonce
	nonce=`get_zeronet_file_direct "$1" | grep '^wrapper_nonce =' | cut -f2 -d'"'`
	get_zeronet_file_direct "$1?wrapper_nonce=$nonce"
}

get_zeronet_file_direct()
{
	curl -sS "$ZERONET_URL/$1" -H Accept:text/html
}

slice()
{
	local delim=$1
	shift
	local fields=$1
	shift
	cut -d "$delim" -f "$fields" <<<"$*"
}

list_site_domains()
{
	jq -r 'to_entries | .[] | [.key, .value.domain // "-"] | join(" ")' "$ZERONET_DATA/sites.json"
}

list_site_titles()
{
	jq -r '[.address, .title] | join(" ")' "$ZERONET_DATA/"*"/content.json"
}

find_out_zite_address()
{
	local x=`slice / 2 "$1"`
	local y=`slice / 3 "$1"`
	
	case "$x" in
	addr)
		echo "$y"
		;;
	name)
		list_site_domains |\
		while read addr name
		do
			if [ "$name" = "$y" ]
			then
				echo $addr
				break
			fi
		done
		;;
	title)
		y=${y//⁄/\/}
		list_site_titles |\
		while read addr title
		do
			if [ "$title" = "$y" ]
			then
				echo $addr
				break
			fi
		done
		;;
	esac
}

list_zite_files()
{
	local zite=$1
	local prefix=$2
	get_zeronet_file_direct "$zite/content.json" |\
	jq -r "(.files + .files_optional) | keys[] | select(.|startswith(\"${prefix//\"/\\\"}\"))"
}



fuse_operation=${0##*/}

case "$fuse_operation" in
readdir)
case "$1" in
/)
	print_entry_dir addr
	print_entry_dir name
	print_entry_dir title
;;
/addr|/name|/title)
	if [ -n "$ZERONET_DATA" ]
	then
		join -j1 <(list_site_domains | sort) <(list_site_titles | sort) |\
		while read addr name title
		do
			mtime=`stat -c %Y "$ZERONET_DATA/$addr"`
			case "$1" in
			/addr)
				print_entry_dir "$addr"
				;;
			/name)
				if [ -n "$name" -a "$name" != - ]
				then
					print_entry_symlink "$name"
				fi
				;;
			/title)
				if [ -n "$title" ]
				then
					title_safe=${title//\//⁄}
					print_entry_symlink "$title_safe"
				fi
				;;
			esac
		done
	fi
	;;
/addr/*|/name/*|/title/*)
	ZITE=`find_out_zite_address "$1"`
	
	if [ -z "$ZITE" ]
	then
		exit $ENOENT
	fi
	
	PREFIX=`slice / 4- "$1"`
	if [ -n "$PREFIX" ]
	then
		PREFIX=$PREFIX/
	fi
	
	list_zite_files "$ZITE" "$PREFIX" |\
	{
	declare -A dirs
	# TODO: make it faster
	while read -r path
	do
		relpath=${path:${#PREFIX}}
		if [[ $relpath =~ ^([^/]+)/ ]]
		then
			dir=${BASH_REMATCH[1]}
			if [ -z "${dirs[$dir]}" ]
			then
				dirs[$dir]=1
				print_entry_dir "$dir"
			fi
		else
			print_entry_file "$relpath"
		fi
	done
	}
	;;
*)
	exit $ENOENT
	;;
esac
exit 0
;; # readdir

getattr)
case "$1" in
/addr/*/*|/name/*/*|/title/*/*)
	ZITE=`find_out_zite_address "$1"`
	
	if [ -z "$ZITE" ]
	then
		exit $ENOENT
	fi
	
	lookup_path=`slice / 4- "$1"`
	
	list_zite_files "$ZITE" "$lookup_path" |\
	{
		read -r one_path
		if [ -z "$one_path" ]
		then
			exit $ENOENT
		else
			if [ "$one_path" = "$lookup_path" ]
			then
				print_entry_file
			else
				print_entry_dir
			fi
			exit 0
		fi
	}
	exit ${PIPESTATUS[1]}
	;;
/|/addr|/name|/title|/addr/*|/name/*|/title/*)
	print_entry_dir
	;;
esac
exit 0
;; # getattr
esac

exit $ENOSYS
