#!/bin/bash

set -u
set -e

. ./env

echo x >$file1

mkdir $dir1
echo x >$dir1/x

mkdir $dir2
mkdir $dir2/nonwritable
mkdir -m 0775 $dir2/writable

echo x >$dir2/nonwritable/x
echo x >$dir2/writable/x

mkdir $dir2/nonwritableEmpty
mkdir -m 0775 $dir2/writableEmpty
