#!/bin/bash

if [ -z "$1" ]
then
	files=([0-9][0-9]-*.test)
else
	files=("$@")
fi

GROUP=`id -gn`
PASSED=0
FAILED=0


subs_self()
{
	local s=$1
	s=${s/SELF:/$USER:}
	s=${s/:SELF/:$GROUP}
	s=${s/SELF/$USER}
	echo $s
}

sort_by_line_length()
{
	local line
	while read -r line
	do
		echo "${#line} $line"
	done |\
	sort -nr |\
	while read -r x line
	do
		echo "$line"
	done
}


for testfile in "${files[@]}"
do
	tcase=`basename "$testfile" .test`
	echo "TEST CASE $tcase ... RUNNING"
	
	(
		set -e
		set -o pipefail
		
		cat "$testfile" |\
		sed -e '/^\s*\(#\|$\)/d' |\
		{
			testdir=`mktemp -d "_test.$tcase.XXXXXX"`
			
			(
				echo CHDIR "$testdir" >&2
				cd "$testdir"
				status_checked=no
				exit_status=''
				cmd_environ=()
				cmd_environ_unset=()
				
				while read -r section
				do
					case $section in
					setting)
						declare -A chmod=()
						declare -A chown=()
						
						while read -r mode owner file
						do
							if [ $mode = end ]; then break; fi
							
							if [[ $file =~ (.+)\ -\>\ (.+) ]]
							then
								file=${BASH_REMATCH[1]}
								target=${BASH_REMATCH[2]}
								
								mkdir -p "$(dirname "$file")"
								ln -sn "$target" "$file"
							else
								if [ "${file: -1}" = / ]
								then
									mkdir -p "$file"
								else
									mkdir -p "$(dirname "$file")"
									echo -n x >"$file"
								fi
								
								chmod[$file]=$mode
							fi
							
							owner=`subs_self "$owner"`
							chown[$file]=$owner
						done
						
						for file in "${!chmod[@]}"; do echo "$file"; done |\
						sort_by_line_length |\
						while read -r file
						do
							mode=${chmod[$file]}
							chmod $mode "$file"
						done
						
						for file in "${!chown[@]}"; do echo "$file"; done |\
						sort_by_line_length |\
						while read -r file
						do
							owner=${chown[$file]}
							../chown --no-dereference $owner "$file" </dev/null
						done
						;;
					environ)
						while read -r env
						do
							if [ ."$env" = .end ]; then break; fi
							if [ -z "${env//[!=]/}" ]
							then
								cmd_environ_unset=(-u "$env")
							else
								cmd_environ+=("$env")
							fi
						done
						;;
					cleanup-pre-script)
						while read -r cmd
						do
							if [ ".$cmd" = .end ]; then break; fi
							echo "$cmd" >>cleanup-pre.sh
						done
						;;
					action)
						status_checked=no
						exit_status=''
						
						cmd_args=()
						while read -r arg
						do
							if [ ."$arg" = .end ]; then break; fi
							cmd_args+=("$arg")
						done
						
						set +e
						env "${cmd_environ_unset[@]}" "${cmd_environ[@]}" "${cmd_args[@]}" </dev/null 2> >(tee stderr >&2) 1> >(tee stdout >/dev/null)
						exit_status=${PIPESTATUS[0]}
						set -e
						;;
					expections)
						while read -r propname desire file
						do
							if [ $propname = end ]
							then
								if [ $status_checked = no ]
								then
									if [ $exit_status != 0 ]
									then
										echo "Exit status: $exit_status" >&2
										false
									fi
								fi
								break
							fi
							
							expection_failed_msg=''
							operator='=='
							
							case $propname in
							owner)
								fact=`stat -c %U "$file" 2>/dev/null || true`
								desire=${desire/SELF/$USER}
								;;
							group)
								fact=`stat -c %G "$file" 2>/dev/null || true`
								desire=${desire/SELF/$GROUP}
								;;
							size)
								fact=`stat -c %s "$file" 2>/dev/null || true`
								operator=${desire//[0-9]/}
								[ -n "$operator" ] || operator='=='
								desire=${desire//[!0-9]/}
								;;
							exists)
								fact=`stat -c yes "$file" 2>/dev/null || echo no`
								;;
							type)
								fact=`ls -ld "$file" | cut -c1`
								fact=${fact/-/f}
								;;
							status)
								expection_failed_msg="status"
								case "$desire" in
								fail) desire='!=0';;
								success) desire='==0';;
								*) echo "wrong keyword: '$desire'" >&2; exit 255;;
								esac
								
								operator=${desire//[0-9]/}
								[ -n "$operator" ] || operator='=='
								desire=${desire//[!0-9]/}
								
								fact=$exit_status
								status_checked=yes
								;;
							stderr|stdout)
								expection_failed_msg="$propname $desire {$file}"
								
								case "$desire" in
								match) operator='==';;
								not-match) operator='!=';;
								*) echo "wrong keyword: '$desire'" >&2; exit 255;;
								esac
								pattern=$file
								
								set +e
								grep -E -q -m1 "$pattern" "$propname"
								if [ $? = 0 ]; then fact=match; else fact=not-match; fi
								set -e
								;;
							esac
							
							case "$operator" in
							'>=') testoper=-ge;;
							'<=') testoper=-le;;
							'>')  testoper=-gt;;
							'<')  testoper=-lt;;
							'==') testoper='==';;
							'!=') testoper='!=';;
							*)    false;;
							esac
							
							if [ "$desire" $testoper "$fact" ]
							then
								true
							else
								if [ -z "$expection_failed_msg" ]
								then
									expection_failed_msg="$file $propname"
								fi
								echo "Expection failed: $expection_failed_msg - desired $operator '$desire', detected '$fact'" >&2
								false
							fi
						done
						;;
					*)
						echo "WARN: Unsupported section: $section" >&2
						while read -r x y
						do
							if [ $x = end ]; then break; fi
						done
						;;
					esac
				done
			)
			
			# delete test base directory if we can
			echo "INFO: Cleanup $testdir" >&2
			if [ -e "$testdir"/cleanup-pre.sh ]; then ( cd "$testdir" && bash cleanup-pre.sh; ); fi
			rm -r "$testdir" || true
		}
	)
	
	if [ $? = 0 ]
	then
		echo "TEST CASE $tcase ... PASSED"
		PASSED=$((PASSED + 1))
	else
		echo "TEST CASE $tcase ... FAILED"
		FAILED=$((FAILED + 1))
	fi
done

echo "-------------
PASSED $PASSED/$((PASSED + FAILED))" >&2
