#!/bin/bash

set -u
set -e

[ -n "${foreignuser?Please set \$foreignuser to a local unix user name who is not you. Test files will be created in the name of him with sudo.}" ]



testcase()
{
	TESTCASE=$*
	echo "[*] $* ..."
}
end_testcase()
{
	local code=$?
	local result
	
	[ $code = 0 ] && result=PASSED || result=FAILED
	TESTCASES[$TESTCASE]=$result
	echo "[*] $TESTCASE ... $result"
}
fail()
{
	echo "$*" >&2
	false
}
summary()
{
	echo
	echo
	echo == SUMMARY ==
	maxlen=0
	for case in "${!TESTCASES[@]}"
	do
		[ ${#case} -le $maxlen ] || maxlen=${#case}
	done
	for case in "${!TESTCASES[@]}"
	do
		sp=$[maxlen - ${#case}]
		printf "%s%${sp}s ... %s\n" "$case" "" "${TESTCASES[$case]}"
	done
}


declare TESTCASE
declare -A TESTCASES
workdir=`mktemp -d _tests.XXXXXX`


set -E
trap 'end_testcase; summary' ERR



testcase takeown recursive

pwd=$PWD
mkdir -p $workdir
setfacl -m u:$foreignuser:rwx $workdir
dir1=takeownTestDir
(
	cd $workdir && \
	sudo -u $foreignuser $pwd/generate-files $dir1
)
setfacl -b -k $workdir
#sudo -k

generated_files_count=`find $workdir/$dir1 | wc -l`

../../usr/bin/takeown -v -R $workdir/$dir1

! find $workdir/$dir1 -printf '%u %p\n' | grep -vE -m1 "^$USER " || fail file found not owned by $USER
[ $generated_files_count = `find $workdir/$dir1 | wc -l` ] || fail wrong number of files

end_testcase


summary
