#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from __future__ import print_function

import os
import sys
import re
import gtk
import glib


def exit():
	gtk.main_quit()

def on_menuitem_activate(widget):
	text = widget.get_data('text')
	print(text)
	exit()

def popup(menu):
	# Get current pointer position (root coordinates)
	display = gtk.gdk.display_get_default()
	screen, x, y, mods = display.get_pointer()
	# Show the popup at pointer position
	menu.popup(None, None, None, 0, gtk.get_current_event_time())
	menu.show_all()

def keep_sensitive_style(widget, event):
	for prop in ['fg', 'bg', 'text', 'base']:
		getattr(widget, 'modify_'+prop)(gtk.STATE_INSENSITIVE, getattr(widget.get_style(), prop)[gtk.STATE_NORMAL])
	return False

def unescape_path_element(x):
	return re.sub(r'\\(.)', lambda m: m.group(1), x)

def pathsplit(path):
	elements = []
	pairs = ['' if x is None else x for x in re.split(r'(?<!\\)(\\\\)*/', path) + [None]]
	for i in range(0, len(pairs), 2):
		elements.append(pairs[i] + pairs[i+1])
	return ['/'.join(elements[0:-1]), unescape_path_element(elements[-1])]

def create_menu(labelpath):
	if labelpath == '':
		return gtk.Menu()
	parent_label, label = pathsplit(labelpath)
	if parent_label not in menu_by_label:
		menu_by_label[parent_label] = create_menu(parent_label)
	mi = gtk.MenuItem(label=label)
	menu_by_label[parent_label].append(mi)
	menu = gtk.Menu()
	mi.set_submenu(menu)
	return menu

def create_menuitem(label, text):
	mi = gtk.MenuItem(label=label)
	mi.set_data('text', text)
	mi.set_use_underline(False)
	mi.connect('activate', on_menuitem_activate)
	return mi

menu_by_label = {}

if __name__ == "__main__":
	while True:
		line = sys.stdin.readline()
		if line == '': break
		if line[-1] == '\n': line = line[:-1]  # chomp
		
		words = line.split('\t', 3)
		labelpath, tipus, icon, text = words + ['']*(4-len(words))
		if tipus == '': tipus = 'text'
		if text == '': text = labelpath
		
		parent_label, label = pathsplit(labelpath)
		
		if parent_label not in menu_by_label:
			menu_by_label[parent_label] = create_menu(parent_label)
		
		mi = None
		if tipus == 'sep':
			mi = gtk.SeparatorMenuItem()
		elif tipus == 'caption':
			mi = gtk.CheckMenuItem()
			l = gtk.Label()
			l.set_markup('<b>'+glib.markup_escape_text(text)+'</b>')
			l.set_alignment(0, 0)
			l.connect("expose-event", keep_sensitive_style)
			mi.add(l)
			mi.set_sensitive(False)
		elif tipus == 'text':
			mi = create_menuitem(label, text)
		else:
			print("unknown menu item type: "+tipus, file=sys.stderr)
		
		# TODO support icon
		
		if mi is not None:
			menu_by_label[parent_label].append(mi)
	
	menu_by_label[''].show_all()
	menu_by_label[''].connect('deactivate', lambda *x: exit())
	popup(menu_by_label[''])
	gtk.main()
