#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import os
import argparse
import gtk
import gobject
import sys
import pango

from hband_tools.gui import *


class TextFlowViewer(Scrollable):
	__gsignals__ = {
		'loading-started': (gobject.SIGNAL_RUN_LAST, gobject.TYPE_BOOLEAN, ()),
		'loading-finished': (gobject.SIGNAL_RUN_LAST, gobject.TYPE_BOOLEAN, ()),
	}
	
	def __init__(self, fileno):
		self.textview = gtk.TextView()
		self.textview.set_editable(False)
		self._font_size = 10
		self.font_size = self._font_size
		self.textview.add_events(gtk.gdk.SCROLL_MASK)
		self.textview.connect("scroll-event", self.on_scroll)
		super(TextFlowViewer, self).__init__(self.textview)
		self.watch_file(fileno)
	
	def watch_file(self, fileno):
		gobject.io_add_watch(fileno, gobject.IO_IN | gobject.IO_HUP | gobject.IO_ERR, self.on_file_readable)
		self.emit('loading-started')
	
	def append_text(self, text):
		buffer = self.textview.get_buffer()
		end_iter = buffer.get_end_iter()
		buffer.insert(end_iter, text)
		# Auto-scroll
		mark = buffer.create_mark(None, buffer.get_end_iter(), False)
		self.textview.scroll_to_mark(mark, 0.0, True, 0.0, 1.0)
	
	def on_file_readable(self, source, condition):
		chunk = os.read(source, 4096)
		self.append_text(chunk)
		if chunk == '':
			self.on_eof()
			return False
		return True
	
	def on_eof(self):
		self.emit('loading-finished')
		return False
	
	def on_scroll(self, widget, event):
		if event.state & gtk.gdk.CONTROL_MASK:
			if event.direction == gtk.gdk.SCROLL_UP:
				self.font_size += 1
			elif event.direction == gtk.gdk.SCROLL_DOWN:
				self.font_size = max(1, self.font_size-1)
			return True
		return False
	
	@property
	def font_size(self):
		return self._font_size
	
	@font_size.setter
	def font_size(self, pt):
		self._font_size = pt
		self.textview.modify_font(pango.FontDescription("Monospace %d"%(pt,)))


def on_loaded(viewer, window):
	window.title = args.title
	set_icon(window, args.icon)

def set_icon(window, icon):
	if icon is not None:
		icon_size = gtk.icon_size_lookup(gtk.ICON_SIZE_LARGE_TOOLBAR)[0]
		iconfile = find_icon_file(icon, icon_size)
		if iconfile is not None:
			window.set_icon(gtk.gdk.pixbuf_new_from_file(iconfile))



parser = argparse.ArgumentParser(description='GTK-2 text/tail viewer')
parser.add_argument('--title', type=str, default='', help='Window title text')
parser.add_argument('--loading-prefix', type=str, default='[loading…] ', help='In-progress indicator text in the window title')
parser.add_argument('--app-instance', type=str, help='User-defined name of this specific gtail instance')
parser.add_argument('--geometry', type=str, help='Window geometry WxH')
parser.add_argument('--icon', type=str, help='Window icon file name or symbolic name')
parser.add_argument('--loading-icon', type=str, help='Window icon while reading is in progress')
parser.add_argument('--file', type=str, help='File to read instead of stdin')
#parser.add_argument('--follow', type=bool, default=False, help='Watch file for increments')  # TODO implement
args = parser.parse_args()


APPNAME = 'gtail'
if args.app_instance is not None:
	APPNAME += '.' + args.app_instance
gobject.threads_init()

window = Window()
window.title = args.loading_prefix + args.title
set_icon(window, args.loading_icon or args.icon)
if args.geometry is not None:
	width, height = [int(size) for size in args.geometry.split('x')]
	window.set_default_size(width, height)
window.connect('destroy', gtk.main_quit)
if args.file is not None:
	inputfile = open(args.file)
else:
	inputfile = sys.stdin
viewer = TextFlowViewer(inputfile.fileno())
viewer.connect('loading-finished', on_loaded, window)

window.add(viewer)
window.show_all()

gtk.main()
