#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import argparse
import gtk
import gobject
import sys
import pango


class StdinViewer(object):
	def __init__(self, title, reading_indicator_text, width, height):
		self.title_text = title
		
		self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
		self.window.set_title(reading_indicator_text + self.title_text)
		self.window.connect("destroy", gtk.main_quit)
		
		self.textview = gtk.TextView()
		self.textview.set_editable(False)
		self._font_size = 10
		self.font_size = 10
		self.buffer = self.textview.get_buffer()
		
		self.textview.add_events(gtk.gdk.SCROLL_MASK)
		self.textview.connect("scroll-event", self.on_scroll)
		
		scroller = gtk.ScrolledWindow()
		scroller.set_policy(gtk.POLICY_AUTOMATIC, gtk.POLICY_AUTOMATIC)
		scroller.add(self.textview)
		
		self.window.add(scroller)
		self.window.set_default_size(width, height)
		self.window.show_all()
		
		# Add io watch
		gobject.io_add_watch(sys.stdin.fileno(), gobject.IO_IN, self.on_stdin_readable)
		gobject.io_add_watch(sys.stdin.fileno(), gobject.IO_HUP, self.on_stdin_eof)
	
	def append_text(self, text):
		end_iter = self.buffer.get_end_iter()
		self.buffer.insert(end_iter, text)
		# Auto-scroll
		mark = self.buffer.create_mark(None, self.buffer.get_end_iter(), False)
		self.textview.scroll_to_mark(mark, 0.0, True, 0.0, 1.0)
	
	def on_stdin_readable(self, source, condition):
		import os
		try:
			chunk = os.read(source, 4096)
		except OSError:
			return False
		if not chunk:
			return False
		self.append_text(chunk)
		return True
	
	def on_stdin_eof(self, *args):
		self.window.set_title(self.title_text)
		return False
	
	def on_scroll(self, widget, event):
		if event.state & gtk.gdk.CONTROL_MASK:
			if event.direction == gtk.gdk.SCROLL_UP:
				self.font_size += 1
			elif event.direction == gtk.gdk.SCROLL_DOWN:
				self.font_size = max(1, self.font_size-1)
			return True
		return False
	
	@property
	def font_size(self):
		return self._font_size
	
	@font_size.setter
	def font_size(self, pt):
		self._font_size = pt
		self.textview.modify_font(pango.FontDescription("Monospace %d"%(pt,)))



parser = argparse.ArgumentParser(description='GTK2 text/tail viewer')
parser.add_argument('--title', type=str, default='Text', help='Window title text')
parser.add_argument('--reading-text', type=str, default='[reading…] ', help='In-progress indicator text')
parser.add_argument('--geometry', type=str, default='600x400', help='Window geometry WxH')
#parser.add_argument('--file', type=str, help='File to read instead of stdin')
args = parser.parse_args()

width, height = [int(size) for size in args.geometry.split('x')]

gobject.threads_init()
viewer = StdinViewer(args.title, args.reading_text, width, height)
gtk.main()
