#!/bin/bash

set -e

if [ "$1" = --inner ]
then
	mkdir -p /var/lib/notashell
	
	shellnames=(sh dash bash)
	
	for shell in "${shellnames[@]}"
	do
		[ -f /var/lib/notashell/real-$shell ] || true > /var/lib/notashell/real-$shell
		mount -o bind /bin/$shell /var/lib/notashell/real-$shell
	done
	for shell in "${shellnames[@]}"
	do
		mount -o bind /usr/tool/notashell /bin/$shell
	done
	
	shift
	export NOTASHELL_REDIRECT=1
	exec "$@"
else
	exec unshare --mount -- "$0" --inner "$@"
fi
