#!/usr/bin/env perl

$0 =~ s/^.*\/([^\/]+)$/$1/;

if(not $ENV{'BATTERY_LOW_ACTION'})
{
	die "$0: Set BATTERY_LOW_ACTION environment to a command.\n";
}
if(not $ENV{'BATTERY_TIME_THRESHOLD'} and not $ENV{'BATTERY_PERCENTAGE_THRESHOLD'})
{
	die "$0: Set BATTERY_TIME_THRESHOLD and/or BATTERY_PERCENTAGE_THRESHOLD environment to at most how many remaining sec or percentage will trigger the action.\n";
}
if(not $ENV{'MIN_UPTIME'})
{
	die "$0: Set MIN_UPTIME environment to prevent firing action shortly after reboot.\n";
}


open my $fh, '/proc/uptime' or die "$0: $!";
($uptime) = <$fh> =~ /(\d+)/;
close $fh;

if($uptime <= $ENV{'MIN_UPTIME'})
{
	exit 0;
}


$highest_remaining_sec = undef;
$highest_percent = undef;
$batteries_with_sufficient_charge = 0;


open my $pipe, '-|', 'acpi', '-ab' or die "$0: $!";
while(<$pipe>)
{
	chomp;
	$remaining_sec = undef;
	$remaining_time = undef;
	$percent = undef;
	my $battery_has_sufficient_charge = 1;
	
	if(/Adapter.*on-line/)
	{
		warn "$0: $_: No action.\n";
		exit 0;
	}
	if(/(\d\d+):(\d\d):(\d\d) remaining/)
	{
		my ($hour, $min, $sec) = ($1, $2, $3);
		$remaining_sec = $hour * 3600 + $min * 60 + $sec;
		if($remaining_sec > $highest_remaining_sec)
		{
			$highest_remaining_sec = $remaining_sec;
			$highest_remaining_time = "$hour:$min:$sec";
		}
	}
	if(/(\d+)%/)
	{
		$percent = $1;
		if($percent > $highest_percent)
		{
			$highest_percent = $percent;
		}
	}
	
	if($ENV{'BATTERY_TIME_THRESHOLD'} and defined $remaining_sec and $remaining_sec <= $ENV{'BATTERY_TIME_THRESHOLD'})
	{
		$battery_has_sufficient_charge = 0;
	}
	if($ENV{'BATTERY_PERCENTAGE_THRESHOLD'} and defined $percent and $percent <= $ENV{'BATTERY_PERCENTAGE_THRESHOLD'})
	{
		$battery_has_sufficient_charge = 0;
	}
	if($battery_has_sufficient_charge)
	{
		$batteries_with_sufficient_charge++;
	}
}
close $pipe;


$message = sprintf "remaining percentage: %s%%, remaining time: %s, batteries with enough capacity: %d.", $highest_percent // "unknown", $highest_remaining_time // "unknown", $batteries_with_sufficient_charge;


if($batteries_with_sufficient_charge < 1)
{
	my $command = $ENV{'BATTERY_LOW_ACTION'};
	warn "$0: $message Running '$command'.\n";
	system $command;
}
else
{
	warn "$0: $message No action.\n";
}
