#!/bin/bash

	stdbuf -oL tail -n 0 -v -F /var/run/xinetd.dump |\
	{
	pass=''
	while IFS='' read -r line
	do
		if [[ $line =~ ^==\> ]]
		then
			# tail opened the file, it's time to ask xinetd to dump
			pkill -USR1 -F /var/run/xinetd.pid
		fi
		if [[ $line =~ ^INTERNAL\ STATE\ DUMP ]]
		then
			pass=1
		fi
		if [ $pass ]
		then
			printf "%s\n" "$line"
		fi
		if [[ $line =~ ^END\ OF\ DUMP ]]
		then
			pass=''
			break
		fi
	done
	
	# we got enough data, terminate tail
	pipekill 0
	}
